### ISSUE TITLE
Flowblade won't start

### ISSUE THREAD

**Issue by harrwester** [jliljebl/flowblade#965] opened 2021-01-16 20:28 UTC
After installing flowblade-2.6.3-1_all.deb I've tried to (unsuccessfully) run it from terminal (older versions resulted in same error).

```
mint@harwester:~$ flowblade
FLOWBLADE MOVIE EDITOR 2.6.3
----------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.20.0
numpy version: 1.17.4
Application version: 2.6.3
OS: Linux Mint 20
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
GTK+ version: 3.24.20
XDG user data exists.
Locale: en_US
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Initializing Auto Save Options
Gtk version is 3.24.20, Flowblade theme is available.
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 236, in main
    Gtk.Settings.get_default().set_property("gtk-application-prefer-dark-theme", True)
  File "/usr/local/lib/python3.8/dist-packages/pgi-0.0.11.2-py3.8.egg/pgi/obj.py", line 75, in set_property
    raise TypeError("Unknown property: %r" % name)
TypeError: Unknown property: 'gtk-application-prefer-dark-theme'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_flowblade.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 236, in main
    Gtk.Settings.get_default().set_property("gtk-application-prefer-dark-theme", True)
  File "/usr/local/lib/python3.8/dist-packages/pgi-0.0.11.2-py3.8.egg/pgi/obj.py", line 75, in set_property
    raise TypeError("Unknown property: %r" % name)
TypeError: Unknown property: 'gtk-application-prefer-dark-theme'
```

**Comment by jliljebl** [comment] 2021-01-17 08:48
This should not be happening:
  * I have Flowblade running on Linux Mint 20 (Mate) VM here with no issues
  *  'gtk-application-prefer-dark-theme' is available in GTK, someone asked for its removal and was refused: https://gitlab.gnome.org/GNOME/gtk/-/issues/2340

I strongly suspect that the issue is in your system somehow. I'm keeping this open to see if we get additional info, but I will be closing this in coming months unless we get better understanding of the issue.

**Comment by harrwester** [comment] 2021-01-17 15:01
I started using linux little over a month ago so I lack experience. However, I've installed and tried out dozens and dozens of apps and programs since. Flowblade and OBS studio are the only ones I can't even run. It used to be Tartube too, but it was fixed with the newest release (https://github.com/axcore/tartube/issues/245), even though I never learnt what the issue was. I reported the problem to OBS (https://obsproject.com/forum/threads/obs-wont-start.137079/), but no one seems to care, although the "Segmentation fault (core dumped)" message at the end suggests an error related to memory usage according to my quick search, and I've no idea how to fix it if that's the case. The difference is that I was able to ran and play around with OBS for a little while, make a short recording before it crashed and never opened again, but I couldn't open Flowblade even once. Nonetheless, I tend to think that it might be system related (maybe nvidia, memory or both), but how can I tell? Could you check the other reports I pasted here to see if there's a relation? Or how else can I find out more details of what it might be?

**Comment by jliljebl** [comment] 2021-01-17 16:12
You can try installing Flatpak version of Flowblade from Flathub, here are links link that should help.

https://linuxhint.com/flatpak_linux_mint/

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md#installing-flatpak-from-flathub

Your issue is quite mysterious, I just do not have any idea what is problem here.

**Comment by harrwester** [comment] 2021-01-17 20:11
Yap, flatpak works like a charm! I could thought of that sooner, it already happened with other programs (i.e. had to try different ways to install them to get them run and work properly). So what's the difference between flatpak 2.6.1 and deb 2.6.1 versions?

**Comment by jliljebl** [comment] 2021-01-18 09:07
> So what's the difference between flatpak 2.6.1 and deb 2.6.1 versions?

Nothing, the difference is in the environment that application runs on: 
  * **deb 2.6.1** runs on GTK and libs provided by OS (Linux Mint 20 in your case)
  * **flatpak 2.6.1** runs on GNOME Application Platform 3.36 and libs provided by Flathub and me

I'm closing this as unreproduced as it is 99% sure that problem is that for unknown reason your system has a slightly broken GTK install.

**Closed by jliljebl** 2021-01-18 09:07 UTC

**Comment by rain1598** [comment] 2021-07-02 15:29
I have the same problem but on manjaro
FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/pyshared/Flowblade
MLT found, version: 6.26.1
numpy version: 1.20.3
Application version: 2.8.0
OS: Manjaro Linux
Python 3.9.5 (default, May 24 2021, 12:50:35) 
[GCC 11.1.0]
GTK+ version: 3.24.29
CREATED XDG CACHE DIR.
XDG user data exists.
Locale: en_CA
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Initializing Auto Save Options
Gtk version is 3.24.29, Flowblade theme is available.
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/pyshared/Flowblade/app.py", line 242, in main
    Gtk.Settings.get_default().set_property("gtk-application-prefer-dark-theme", True)
  File "/usr/lib/python3.9/site-packages/pgi/obj.py", line 75, in set_property
    raise TypeError("Unknown property: %r" % name)
TypeError: Unknown property: 'gtk-application-prefer-dark-theme'

**Comment by jliljebl** [comment] 2021-09-08 08:19
Eff it, I'll add try...except to combat this. This is a distro issue, but we can paper over this at the cost of user will losing ability to use light themes.

**Comment by jliljebl** [comment] 2021-09-08 08:24
Ok, this no longer crashes. Seems that what is lost here is the ability to request system dark theme variant.
