### ISSUE TITLE
compiling with python3 - SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#658] opened 2019-05-03 09:33 UTC
Hi,

can't compile recent flowblade version on Fedora 30 with python3.
The text should be between rounded brackets.

Example:

    print("D") # Python 3

And

    print "D"  # Python 2

`*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/app.py'...
  File "/usr/lib/python3.7/app.py", line 135
    print "Application version: " + editorstate.appversion
                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Application version: " + editorstate.appversion)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/atomicfile.py'...
  File "/usr/lib/python3.7/atomicfile.py", line 146
    print "Error cleaning up temp file: " + self.tmp_file_path
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Error cleaning up temp file: " + self.tmp_file_path)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/audiosync.py'...
  File "/usr/lib/python3.7/audiosync.py", line 76
    print "Starting clapperless analysis..."
                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Starting clapperless analysis...")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/clipeffectseditor.py'...
  File "/usr/lib/python3.7/clipeffectseditor.py", line 478
SyntaxError: name 'current_filter_index' is used prior to global declaration

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/compositormodes.py'...
  File "/usr/lib/python3.7/compositormodes.py", line 144
    print "COMPOSITOR MODE EXIT PROBLEM at compositormodes.mouse_release"
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("COMPOSITOR MODE EXIT PROBLEM at compositormodes.mouse_release")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/diskcachemanagement.py'...
  File "/usr/lib/python3.7/diskcachemanagement.py", line 137
    print "deleting ", self.folder
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("deleting ", self.folder)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/dnd.py'...
  File "/usr/lib/python3.7/dnd.py", line 238
    print "monitor_drop fail"
                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("monitor_drop fail")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/editevent.py'...
  File "/usr/lib/python3.7/editevent.py", line 282
    print "EDIT_MODE() == editorstate.CLIP_END_DRAG at mouse press!"
                                                                   ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/editorpersistance.py'...
  File "/usr/lib/python3.7/editorpersistance.py", line 104
    print "prefs updated to new version, new param count:", len(prefs.__dict__)
                                                         ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/editorwindow.py'...
  File "/usr/lib/python3.7/editorwindow.py", line 547
    print "No rendering options found"
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No rendering options found")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/glassbuttons.py'...
  File "/usr/lib/python3.7/glassbuttons.py", line 136
    print "_press_event not impl"
                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("_press_event not impl")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/gui.py'...
  File "/usr/lib/python3.7/gui.py", line 167
    print "Selected color NOT detected"
                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Selected color NOT detected")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/guicomponents.py'...
  File "/usr/lib/python3.7/guicomponents.py", line 267
    except GObject.GError, exc:
                         ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/keyframeeditcanvas.py'...
  File "/usr/lib/python3.7/keyframeeditcanvas.py", line 318
    print "_clip_frame_changed not impl"
                                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("_clip_frame_changed not impl")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/keyframeeditor.py'...
  File "/usr/lib/python3.7/keyframeeditor.py", line 487
    print msg, "clip edit keyframes:"
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg, "clip edit keyframes:")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/kftoolmode.py'...
  File "/usr/lib/python3.7/kftoolmode.py", line 385
    print "clip edit keyframes:"
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("clip edit keyframes:")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/lutfilter.py'...
  File "/usr/lib/python3.7/lutfilter.py", line 390
    print str(i) + ":" + str(table[i])
            ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/medialinker.py'...
  File "/usr/lib/python3.7/medialinker.py", line 65
    print "Launching Media Re-linker"
                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Launching Media Re-linker")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/menuactions.py'...
  File "/usr/lib/python3.7/menuactions.py", line 120
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(url)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/mltenv.py'...
  File "/usr/lib/python3.7/mltenv.py", line 41
    print "Detecting environment..."
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Detecting environment...")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/mltfilters.py'...
  File "/usr/lib/python3.7/mltfilters.py", line 372
    print "Loading filters..."
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Loading filters...")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/mltplayer.py'...
  File "/usr/lib/python3.7/mltplayer.py", line 52
    print "Player initialized with profile: ", self.profile.description()
                                            ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/mltprofiles.py'...
  File "/usr/lib/python3.7/mltprofiles.py", line 132
    print "default profile from prefs not found"
                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("default profile from prefs not found")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/mltrefhold.py'...
  File "/usr/lib/python3.7/mltrefhold.py", line 28
    print "len(mlt_objects):", len(mlt_objects)
                            ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/mlttransitions.py'...
  File "/usr/lib/python3.7/mlttransitions.py", line 412
    print "Loading transitions..."
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Loading transitions...")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/monitorwidget.py'...
  File "/usr/lib/python3.7/monitorwidget.py", line 922
    print "MatchSurfaceCreator: waiting for _producer"
                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("MatchSurfaceCreator: waiting for _producer")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/multimovemode.py'...
  File "/usr/lib/python3.7/multimovemode.py", line 222
    print "getting failed ripple delete track info in get_overwrite_data() failed"
                                                                                 ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/patternproducer.py'...
  File "/usr/lib/python3.7/patternproducer.py", line 204
    print "create_mlt_producer not implemented"
                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("create_mlt_producer not implemented")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/persistance.py'...
  File "/usr/lib/python3.7/persistance.py", line 118
    print "Saving project..."  # + os.path.basename(file_path)
                            ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/profilesmanager.py'...
  File "/usr/lib/python3.7/profilesmanager.py", line 296
    print profile_path
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(profile_path)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/projectaction.py'...
  File "/usr/lib/python3.7/projectaction.py", line 125
    print "did not find a file"
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("did not find a file")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/projectdata.py'...
  File "/usr/lib/python3.7/projectdata.py", line 111
    print resource_path
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(resource_path)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/projectmediaimport.py'...
  File "/usr/lib/python3.7/projectmediaimport.py", line 119
    print "Starting media import..."
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Starting media import...")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/propertyedit.py'...
  File "/usr/lib/python3.7/propertyedit.py", line 294
    print "color_selected() not overridden"
                                          ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/propertyeditorbuilder.py'...
  File "/usr/lib/python3.7/propertyeditorbuilder.py", line 115
    print "get_transition_extra_editor_rows fail with:" + editor_name
                                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("get_transition_extra_editor_rows fail with:" + editor_name)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/proxyediting.py'...
  File "/usr/lib/python3.7/proxyediting.py", line 78
    print "proxy render started, items: " + str(len(self.files_to_render)) + ", dim: " + str(proxy_w) + "x" + str(proxy_h)
                                        ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/render.py'...
  File "/usr/lib/python3.7/render.py", line 163
    print "yyyyyyyyy"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("yyyyyyyyy")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/renderconsumer.py'...
  File "/usr/lib/python3.7/renderconsumer.py", line 194
    print "Loading render profiles..."
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Loading render profiles...")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/resync.py'...
  File "/usr/lib/python3.7/resync.py", line 138
    print child_clip.id
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(child_clip.id)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/sequence.py'...
  File "/usr/lib/python3.7/sequence.py", line 409
    print "file does not exist"
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("file does not exist")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/shortcuts.py'...
  File "/usr/lib/python3.7/shortcuts.py", line 70
    print "Shortcuts file " + f + " found, but ignored."
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Shortcuts file " + f + " found, but ignored.")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/syncsplitevent.py'...
  File "/usr/lib/python3.7/syncsplitevent.py", line 108
    print "big fu at _init_select_master_clip(...)"
                                                  ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tlineaction.py'...
  File "/usr/lib/python3.7/tlineaction.py", line 519
    print "Ripple delete"
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Ripple delete")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tlinewidgets.py'...
  File "/usr/lib/python3.7/tlinewidgets.py", line 369
SyntaxError: name 'TRACK_GRAD_ORANGE_STOP1' is assigned to before global declaration

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/NatronRenderModify.py'...
  File "/usr/lib/python3.7/NatronRenderModify.py", line 19
    exec exec_code
                 ^
SyntaxError: Missing parentheses in call to 'exec'

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/batchrendering.py'...
  File "/usr/lib/python3.7/batchrendering.py", line 207
    print "dbus service init"
                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("dbus service init")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/clapperless.py'...
  File "/usr/lib/python3.7/clapperless.py", line 350
    print args.idstr
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(args.idstr)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/gmic.py'...
  File "/usr/lib/python3.7/gmic.py", line 103
    print "G'MIC found"
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("G'MIC found")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/gmicplayer.py'...
  File "/usr/lib/python3.7/gmicplayer.py", line 173
    print "Rendering frames range"
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Rendering frames range")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/natronanimations.py'...
  File "/usr/lib/python3.7/natronanimations.py", line 111
    print exec_str
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(exec_str)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/natronanimationswindow.py'...
  File "/usr/lib/python3.7/natronanimationswindow.py", line 196
    print profile_name
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(profile_name)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/phantomcompositor.py'...
  File "/usr/lib/python3.7/phantomcompositor.py", line 71
    print "Phantom2D launched"
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Phantom2D launched")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/titler.py'...
  File "/usr/lib/python3.7/titler.py", line 258
    print "No font families found in system! Titler will not work."
                                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No font families found in system! Titler will not work.")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/toolnatron.py'...
  File "/usr/lib/python3.7/toolnatron.py", line 41
    print "Natron found"
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Natron found")?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/tools/toolsencoding.py'...
  File "/usr/lib/python3.7/toolsencoding.py", line 386
    print args_vals_list
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(args_vals_list)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/toolsintegration.py'...
  File "/usr/lib/python3.7/toolsintegration.py", line 89
    print self.__class__.__name__ + " does not implement do_export()"
             ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/translations.py'...
  File "/usr/lib/python3.7/translations.py", line 42
    print "Locale:", lc
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Locale:", lc)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/trimmodes.py'...
  File "/usr/lib/python3.7/trimmodes.py", line 836
    print "_build_ripple_data(): supposedly unreachable case hit"
                                                                ^
SyntaxError: invalid syntax

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/undo.py'...
  File "/usr/lib/python3.7/undo.py", line 154
    print "undo:", undo.index
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("undo:", undo.index)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/utils.py'...
  File "/usr/lib/python3.7/utils.py", line 472
    print "old style img seq name for " + asset_file_name
                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("old style img seq name for " + asset_file_name)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/vieweditor/vieweditor.py'...
  File "/usr/lib/python3.7/vieweditor.py", line 22
    print "numpy version:", np.version.version
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("numpy version:", np.version.version)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/vieweditor/vieweditorlayer.py'...
  File "/usr/lib/python3.7/vieweditorlayer.py", line 127
    print "AbstactEditorLayer.mouse_pressed not overridden in" + self.__class__
                                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("AbstactEditorLayer.mouse_pressed not overridden in" + self.__class__)?

*** Error compiling '/home/martin/rpmbuild/BUILDROOT/flowblade-2.0-3.git.git21710f5.fc30.x86_64/usr/lib/python3.7/site-packages/Flowblade/workflow.py'...
  File "/usr/lib/python3.7/workflow.py", line 369
    print "lift"
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("lift")?
`
Regards
Martin

**Comment by jliljebl** [comment] 2019-05-03 09:45
Hi, 2.4 will be the first release of Flowblade to run on Python 3. Current release 2.0 and next release 2.2 will still run on Python 2.

2.4 coming sometime after the summer.

**Comment by martinkg** [comment] 2019-05-03 09:53
ok, thanks for your feedback. +1:

**Comment by jliljebl** [comment] 2019-06-10 19:26
Closing as duplicate of the main Python3 Issue.

**Closed by jliljebl** 2019-06-10 19:26 UTC
Labels: duplicate
