### ISSUE TITLE
Ubuntu 16.04. Does not start

### ISSUE THREAD

**Issue by alexb3d** [jliljebl/flowblade#295] opened 2016-12-13 19:11 UTC
Does not start the program. When I run them from the terminal, it gives me the following error:

alexb3d@alex-home:~$ flowblade
FLOWBLADE MOVIE EDITOR 1.10
---------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT not found, exiting...
ERROR: /usr/lib/python2.7/dist-packages/_mlt.x86_64-linux-gnu.so: undefined symbol: _ZNK3Mlt7Profile8is_validEv

**Comment by jliljebl** [comment] 2016-12-13 19:16
This is duplicate of: https://github.com/jliljebl/flowblade/issues/264

There is more information there, but long story short is that you will need to install MLT 6.4.1.

**Closed by jliljebl** 2016-12-13 19:16 UTC
Labels: duplicate

**Comment by melt99** [comment] 2017-12-28 15:26
Dear, 

I tryed many time to run Flowblade 1.14 on Ubuntu 17.10 but after having installed MLT 6.4.1 the app can't run with attribute error 'GdkWaylandWindow' object has no attribute 'get_xid'  
(https://github.com/jliljebl/flowblade/issues/329)
Can someone explain me more about?

Many thanks in advance

Cristiano

**Comment by jliljebl** [comment] 2017-12-28 16:01
You need to start a X11 session from login screen, you are currently getting the Wayland sesion which is the default i believe. Googlewith words "login screen  X11 session Ubuntu 17.10" for more info.
