### ISSUE TITLE
Using much memory for simple thing

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#203] opened 2016-02-12 19:59 UTC
I am using a simple mkv-file as an input, created as a screencast done with ffmpeg. I use 20 wav-files containing some voice-files and try to put them into it.

While rendering, the memory rises very fast to its maximum, using 8GB of RAM and starting to swap

Flowblade before maxram is used
![05](https://cloud.githubusercontent.com/assets/13347618/13018629/e662c536-d1ca-11e5-957a-e4a23a084c50.png)

![04](https://cloud.githubusercontent.com/assets/13347618/13018630/e6654432-d1ca-11e5-9997-4b028ae7d18b.png)

Calculation when system starts to swap
![03](https://cloud.githubusercontent.com/assets/13347618/13018631/e66aa256-d1ca-11e5-9b2d-8643ba4f4328.png)
![02](https://cloud.githubusercontent.com/assets/13347618/13018632/e66aef68-d1ca-11e5-8d85-fe01fcc6d6ce.png)

After stopping the rendering job, the memory is still in use, only a exit of lowblade frees the memory.
![01](https://cloud.githubusercontent.com/assets/13347618/13018633/e66bd9b4-d1ca-11e5-918a-ca369a8ed58c.png)

**Comment by jliljebl** [comment] 2016-02-12 21:08
Pretty much guaranteed to be an MLT issue. Possibly duplicate of this that has been fixed: https://sourceforge.net/p/mlt/bugs/221/

Are you using MLT version 0.9.2 like in the report?

**Comment by Miniellipse** [comment] 2016-02-12 21:52
I am using mlt 0.9.8

Am 12. Februar 2016 22:08:41 MEZ, schrieb jliljebl <notifications@github.com>:
>Pretty much guaranteed to be an MLT issue. Possibly duplicate of this
>that has been fixed: https://sourceforge.net/p/mlt/bugs/221/
>
>Are you using MLT version 0.9.2 like in the report?
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jliljebl/flowblade/issues/203#issuecomment-183488787

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jliljebl** [comment] 2016-02-12 22:05
Are you experiencing a _clear_ performance/responsiveness slowdown before Flowblade is closed and/or during rendering?

**Comment by Miniellipse** [comment] 2016-02-12 22:22
Its not a shutdown, i could create the screenshots with swapping without much problems.
But i have tried something. I needed a functional videoedit, so i tried to install openshot 2.0 bzr, got it working, and on the same side, flowblade renders without memory problems. perhaps my MLT was on an old version before doingt the openshot-bzr-install? I was not able to look at what was installed, perhaps my MLT was old before ... :) It runs now ...

**Comment by jliljebl** [comment] 2016-02-12 22:38
openshot 2.0 no longer uses MLT, but both use ffmpeg, and there has been some conflicts with some MLT versions / ffmpeg versions, maybe openshot 2.0 pulled a newer version of ffmpeg, hard to know.

Closing as this is clearly not a Flowblade issue.

**Closed by jliljebl** 2016-02-12 22:38 UTC
