### ISSUE TITLE
Audio Filter on Music won't change

### ISSUE THREAD

**Issue by flowblade-vibes** [jliljebl/flowblade#412] opened 2017-06-17 20:51 UTC
I have added a music below a scene but I want the scene to be loud enough so you can hear it. I want to lower the music volume. I put in a volume filter and write in 25 or 35. The volume is the same. Sometimes it works but then I try to change it and nothing happens. Is this some bug or am I doing it wrong?

**Comment by bigalgeorge** [comment] 2017-06-18 03:08
As my previous bug post - you need to move the slider. Entering a value wont work.

**Comment by flowblade-vibes** [comment] 2017-06-26 07:25
Wait please explain further.

Do you mean if I type in 0 on the value nothing will happen? Now I'm in a project where I'm editing scenes but the music suddenly changes between them. I wanted the second scene to be quiet but for the audio to slowly fade in. Could you explain this in detail?

**Comment by Efenstor** [comment] 2017-07-02 14:09
There's really nothing to explain. It's a bug. Entering a value and hitting 'Enter' must work but it doesn't.

**Comment by Efenstor** [comment] 2017-07-02 14:18
This is a duplicate of https://github.com/jliljebl/flowblade/issues/409

**Comment by jliljebl** [comment] 2017-07-08 13:43
Yes, closing as duplicate of #409, which is confirmed.

**Closed by jliljebl** 2017-07-08 13:43 UTC
Labels: duplicate
