### ISSUE TITLE
Window can't be downsized

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#452] opened 2017-11-10 17:03 UTC
**Steps to reproduce:**

1. In a two-monitor setup (in my case, 1366x768 + 1920x1080), open Flowblade fullscreen on the small screen.
2. Drag Flowblade to the big screen, go fullscreen and decrease the size of the timeline view by dragging the handle down.
3. Move window back to the small screen, go fullscreen.
4. Notice that the timeline is partly beyond the screen and the view can't be resized back to its original size.

EDIT: It seems that Flowblade can't be resized down beyond 1216x857 which wasn't the case before.

**Comment by smolnp** [comment] 2017-11-18 17:28
I have the same problem. Moreover, if the system uses an outdated gtk theme, the minimize / maximize button appears and even works, but it looks awful.

**Comment by jliljebl** [comment] 2017-11-28 10:45
Thanks, I'll need to set a two monitor test sometime to take a look at this.

**Comment by jliljebl** [comment] 2017-11-28 10:48
SIngle monitor works with going to full screen and back.

**Comment by jliljebl** [comment] 2018-01-03 13:42
I'm 99% sure that the fix for #467 fixed this too, having one or two monitors does not matter here. We had a regression on vertical space with new additions to GUI forcing part of timeline of the screen.

I'm closing this as fixed. If you wish to confirm, test the repository code on affected systems.

**Comment by jliljebl** [comment] 2018-03-22 10:02
This issue is resulting from the same factors as #482, and causes are explained there.

This is very likely not fixed but I do not have a clear path forward as explained in the other issue.

I'm reopening this but do plan to work on it in the immediate future, maybe some solution will occur but currently it seems unfixable, suggestions for logic to work this out can be offered.

**Comment by jliljebl** [comment] 2018-10-11 18:21
There is a fix in repo for 1378px width screens, the middlebar had creeped too wide for screens < under 1420. We got 8 moe pixels for 768px height screens too.

It will likely fix this too., will be in next release. Please reopen of problem persists in next release.

**Closed by jliljebl** 2018-10-11 18:21 UTC
Labels: fixed

**Comment by blackPantherOS** [comment] 2019-05-01 08:36
Main window size is too big on 1600x900 resolution and over stretch as the screen.. Can't resize to smaller under Plasma. look:

![flowblade](https://user-images.githubusercontent.com/12883566/57010449-ffdb3f00-6bfc-11e9-8dfa-33ed7dd0b3b2.png)

**Comment by jliljebl** [comment] 2019-05-01 08:45
Does not reproduce here on 1600x900 (oic below). Can you post the print out from terminal if you start the application from terminal  with command 'flowblade'?
![Screenshot from 2019-05-01 11-41-19](https://user-images.githubusercontent.com/1823444/57010679-a1b35980-6c06-11e9-97df-8fac8b77eb58.png)

**Comment by blackPantherOS** [comment] 2019-05-01 09:10
The several monitors cause this problem ..
Main monitor is 1600x900 and I have two 1920x1080 on same laptop

```
> xrandr | grep connected
> DP-1 connected primary 1600x900+1071+1080 (normal left inverted right x axis y axis) 382mm x 215mm
> HDMI-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
> DVI-I-1-1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 406mm x 229mm

```
 The detected resolution is wrong

```
> /usr/bin/flowblade 
> FLOWBLADE MOVIE EDITOR 2.0
> Launch script dir: /usr/bin
> Running from installation...
> modules path: /usr/lib/python2.7/site-packages/Flowblade
> MLT found, version: 6.14.0
> numpy version: 1.15.1
> Application version: 2.0.0
> OS: blackPanther OS v18.1 (Renegade)
> Python 2.7.15 (default, Sep  5 2018, 10:19:47) 
> [GCC 8.2.1 20180824]
> GTK+ version: 3.22.30
> User dir: /home/XXX/.flowblade/
> Locale: None
> Found translations at /usr/share/locale, using those.
> Use OS locale language.
> Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
> Keyboard shortcuts file: flowblade.xml
> Loading shortcuts: Flowblade
> Screen size: 3840 x 1980
> Small height: False
> Small width: False
> Detecting environment...
> ---
> video_codecs:
> ( unrelevant )
> ---
> audio_codecs:
> ( urelevant )
> ---
> formats:
> ( unrelevant )
> ...
> MLT detection succeeded, 169 formats, 97 video codecs and 74 audio codecs found.
> 590 MLT services found.
> Loading render profiles...
> Loading filters...
> Brightness dropped, MLT version too high for this filter.
> Brightness Keyframed dropped, MLT version too high for this filter.
> Loading transitions...
> RGB Adjustment dropped for Color Adjustment
> Hue dropped for Color Adjustment
> Gamma dropped for Lift Gain Gamma
> G'MIC found
> Natron not found
> Player initialized with profile:  HD 1080i 25 fps
> 
> (flowblade:25048): Gtk-WARNING **: 10:47:31.564: Theme directory actions32@2x of theme breeze-dark has no size field
> 
> Selected color NOT detected
> BG color detected
> Create SDL1 consumer...
> Autosave started...
> Saving project..
> 
```

**Comment by jliljebl** [comment] 2019-05-01 09:38
> Screen size: 3840 x 1980

Ok, its this one again, but with a twist.The problem from application point of view is that were using vertical height info to determine GUI rendering since the optimal GUI requires about 1000px height. We are giving screens with smaller height modified GUIs but you are getting the default one which doesn't fit your screen.

We seem to have available
> gtk.gdk.Screen.get_n_monitors()  # Get number of monitors. 
> get_monitor_geometry(monitor_num)

These will be enough to detect multiple monitors and their sizes but application can't know on which monitor it is displayed on so we need to present GUI for user to select which monitor used or if combined area is used to determine GUI rendering.

I'll add new issue for this but fix will be post Python 3 port, were at feature freeze for 2.2 and Python 3 port will come after that.
