### ISSUE TITLE
Titler -- Titles are offset to right. 16:9 Problem?

### ISSUE THREAD

**Issue by 666c796e6e** [jliljebl/flowblade#183] opened 2015-12-15 06:10 UTC
Hi,

I used flowblade for the first time. Really nice program and quite stable.

One issue I noticed is that all of my titles are offset to the right, which renders the title generator unusable. If texts are extending over all of the screen, they are offset and part of them is trimmed off.

I'm Attaching an example. The word "title" in the png-file was centered (using the >|< Button) but when exporting the png (see ttitle.png) it's offset to the right.

Could it be a 16:9-Problem? I'm using the DVD/PAL-WIDESCREEN Project default and the png does look like it's 4:3!

I'm referring to flowblade 0.14, I installed it from the repository of ubuntu 15.04 . 

Thanks for your help!

![ttitle](https://cloud.githubusercontent.com/assets/7996648/11803273/8cabb872-a2f9-11e5-8d28-a88de0fc32a6.png)
![titler-bug_-_titler](https://cloud.githubusercontent.com/assets/7996648/11803292/c55f836a-a2f9-11e5-9df9-fee6bd3ef60d.png)

**Comment by jliljebl** [comment] 2015-12-16 17:47
Hi, I cannot fix old versions of the application. You will need to download and install the latest version and see if the problem still exists. Install package for latest version 1.4 is available for download here: 
https://www.dropbox.com/s/xe94cjwmf195de2/flowblade-1.4.0-1_all.deb?dl=0

Comment here whether or not the problem still exists.

**Comment by 666c796e6e** [comment] 2015-12-25 20:59
Hi,

thanks for your help! I cloned the trunk and tried it there. No luck, it still keeps offsetting the titles. 
Steps to reproduce:

1) clone: git clone https://github.com/jliljebl/flowblade.git
2) Note to all ubunt-arians: You will want to apt-get install gir1.2-gtk-3.0, otherwise python will somehow burst into flames when flowblade tries to import gtk (saying:
traceback (most recent call last):
  File "app.py", line 30, in <module>
    from gi.repository import Gtk
ImportError: cannot import name Gtk)
3) Create a new project Datei/File -> Neu/New. Choose DVD/DV Widescreen PAL.
4) Create a title. Enter "Test", center it on the screen. Save the title
5) Pull the title on the first video track. The text you centered in the title-editor now appears off-center.

**Comment by jliljebl** [comment] 2015-12-27 02:29
Does using Compositor "Dissolve" and checking box "Distort" fix the issue? You will need to put title on track V2 to and put a black clip (or some other clip) on track V1. The saved titles are PNGs with alpha channel and are supposed to be used to together with compositors.

**Comment by 666c796e6e** [comment] 2015-12-27 10:07
Hi,

alas I think that's not the problem. The title is offset and partly moved
off screen even before I add it to the timeline.

Here's what I get:

In the titler everything looks 16:9 and centered:

[image: Inline-Bild 2]

After Saving the title is already misplaced and mutilated. Watch the
thumbnail!

[image: Inline-Bild 3]

This is how it all ends up (Note: I used vlc for the screenshot. It also
has a 16:9 bug. While it displays the Video in 16:9 allright, the
screenshot is taken in 4:3.)


​

Best regards!


2015-12-27 3:29 GMT+01:00 jliljebl <notifications@github.com>:

**Comment by jliljebl** [comment] 2016-02-03 22:16
Ok, there was a bug and it is working much better now for profile DVD/DV Widescreen PAL.

However it still not perfect, there is still some inaccuracy between Titler view and created graphic which seems to increase when: a)font size gets bigger, 2) pixel aspect ratio gets less square. It may be that the error is caused by the technology used, and I'm actually inputting correct numbers into APIs, but I will have to investigate that later.

I'm closing this as fixed.

**Closed by jliljebl** 2016-02-03 22:16 UTC

**Comment by 666c796e6e** [comment] 2016-02-04 12:14
Hi,

great! Will test this as soon as I have some time to spare! Thanks for your
effort!

Best regards!

2016-02-03 23:16 GMT+01:00 jliljebl <notifications@github.com>:
