### ISSUE TITLE
Dark theme doesn't apply with flatpak

### ISSUE THREAD

**Issue by didli** [jliljebl/flowblade#512] opened 2018-05-25 12:57 UTC
Flowblade 1.16 flatpak in Fedora 28 x64
Since I can't use the distrib package for flowblade (running into this segfault : https://github.com/jliljebl/flowblade/issues/508), I'm using the flatpak version, but I can't switch to a dark theme unless I run this from a terminal : 
`GTK_THEME=Adwaita:dark flatpak run io.github.jliljebl.Flowblade`
Is there a workaround I could try ?

**Comment by eszlari** [comment] 2018-05-25 18:29
Try
```
$ flatpak search theme
```
and install the theme you want to use inside flatpak.

**Comment by didli** [comment] 2018-05-25 19:38
Thank you for your answer eszlari. Unfortunately, no changes. Config folder was already removed when I ran into this issue (I removed it again just to be sure, without success). I didn't know about the themes available through flatpak. Maybe I should test with Adwaita.

**Comment by Efenstor** [comment] 2018-08-18 19:02
That's not the case for me. I have installed Flowblade from Flatpak only a couple of days ago and can change the theme. May be it was fixed? Or probably the problem was not in Flowblade but somewhere in the accompanying Gnome libraries. Can anybody else test it?

**Comment by jliljebl** [comment] 2019-02-17 21:42
We have so many confirmed working Flatpak installations with Adwaita dark theme, that I believe this some glitch, and if it is a bug, it is Flatpak, not Flowblade. Closing as *unreproduced.*

**Closed by jliljebl** 2019-02-17 21:42 UTC
Labels: unreproduced
