### ISSUE TITLE
Monitor/computer standby during open flowblade

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#281] opened 2016-11-11 15:44 UTC
When flowblade is running, monitor standby (as example black screen) and also hibernate dosnt work.
It seems that flowblade sends al few seconds an input to the computer to go not in standby.

When rendering a bigger project, this is a nice feature because hibernate of the computer will be disable.

But this should not be when flowblade ist just started.

**Comment by jliljebl** [comment] 2017-02-01 08:14
This very likely duplicate of:

#194

**Closed by jliljebl** 2017-02-01 08:14 UTC
Labels: duplicate, wontfix
