### ISSUE TITLE
Make default for "Render" panel "File" area "Folder:" selection user settable

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#689] opened 2019-08-26 14:55 UTC
Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:

1) Check Preferences to see if 'Remember last render directory' is ticked. If not, tick, close preferences and restart Flowblade.
2) Create a new project and render to a non-default directory.
3) Close Flowblade and reopen it.
4) Check Render tab. The default render directory is again the HOME directory.

I'm pretty sure this worked at some point, but I can't find when it stopped working.
Also, from version 2.0 on there is no longer a possibility to select default Thumbnail and Render directories in the Preferences -> General tab
I used that to point to my default Render directory which is probably why I didn't notice it no longer worked.

Was this removal accidental? I didn't see it in the release notes.

**Comment by jliljebl** [comment] 2019-08-26 15:04
The render directory is saved per Project, it is not a persistent property of the application, so if you do not save project after rendering it this wont work. Works here as designed currently.

Thumbnail and Render directories are not user settable anymore since we decided to support XDG user data spec, all this kind data is now saved in XDG directories specified in the system.

**Comment by jliljebl** [comment] 2019-08-26 15:07
I updated the release notes to make clear that Thumbnail and Render directories are not user settable now.

**Comment by dvdlvr** [comment] 2019-08-26 15:25
Fair enough for the Render directory.

However, I do not see why I cannot set a specific Default Render 
directory. I want to keep my Renders away from my standard Video 
directory and I don't want to change it everytime I render a video.
I can understand it would default to the VIDEOS directory (It doesn't, 
BTW, it defaults to my HOME directory) but I should definitively be able 
to change that somehow.

Unless there is some other way I can seperate this that I'm not aware of?

$ xdg-user-dir VIDEOS
/home/svdbeek/Videos



Thanks & regards,
Steveh.

**Comment by jliljebl** [comment] 2019-08-26 15:35
The  Render directory was where stuff like render single track transitions and compound clips went, these were *parts* of sequences, sort of hidden small bits data. These are now going to XDG  folder.

If I understood correctly you want to set default folder for "Render" panel "File" area "Folder:" selection to be something else then HOME?

**Comment by dvdlvr** [comment] 2019-08-26 15:39
Yes, you understood correctly

**Comment by jliljebl** [comment] 2019-08-26 15:42
This we can certainly do for 2.4 without it conflicting with XDG spec which really meant for sort of hidden data. I'll add this into feature list. If you do the patch great, otherwise I'll look into this at end of cycle.

**Comment by dvdlvr** [comment] 2019-08-26 15:49
OK, thanks, i'll happily do the patch.

**Comment by jliljebl** [comment] 2020-01-19 08:54
I did the patch, closing the easy Issues right now, will be in 2.6.

**Closed by jliljebl** 2020-01-19 08:54 UTC
Labels: in feature queue
