### ISSUE TITLE
Select specific audio track from source file?

### ISSUE THREAD

**Issue by HugLifeTiZ** [jliljebl/flowblade#865] opened 2020-05-26 04:05 UTC
Flowblade 2.4.0
MLT 6.18.0
Flatpak package

I poked around the UI a lot, but I couldn't find what I was looking for. I automatically record gameplay footage and like to make gameplay clips, and would like the ability to select a specific audio track from source files. I record three tracks: game audio, mic audio, and a blend of the two.

It might be overkill to use Flowblade for that, but it seemed intuitive enough to figure out and use up until the point where I wanted to pick which audio track from the source file would get used, and I couldn't find that at all. Am I missing something, or is that not possible yet?

Thanks kindly. :)

**Comment by dvdlvr** [comment] 2020-05-26 06:02
Hi, that is not possible yet. There is a limited workaround using an MLT XML export and a shell script, but that workaround only allows you to select 1 specific audio track for the entire project. I expect you want to select the audio track for every segment on the timeline. I have done some work on that, but it's far from complete, as I'm currently working on something else. It IS possible to do it using the MLT XML export, but it would require manually modifying the XML, which is rather complex. Another workaround could be to create a new clip with the correct audio for each clip you want to use using the export method ed and my script and then using those clips in your final project. Only clips with audio track 2 or 3 need to be created, because the default used by Flowblade is 1.If you want more info on my script let me know.

**Comment by HugLifeTiZ** [comment] 2020-05-26 14:19
Hey there, thanks for responding. Fortunately for my usecase, it's not a huge deal right now because my audio tracks are blended audio, mic audio only, and game audio only. So for my usecase I only need to hear the first track to know if I need to use one of the other two.

**Comment by jliljebl** [comment] 2021-01-13 09:29
I'll add this into feature queue, this surely a useful feature. Not sure about immediate prospects but I'll look around in next cycle and update here.

**Comment by jliljebl** [comment] 2023-07-18 15:34
This was a duplicate of another Issue I just closed after doing some programming tests for it. There seems to be no plausible way forward with this issue, so I'm closing this as 'wotfix'.

**Closed by jliljebl** 2023-07-18 15:34 UTC
Labels: in feature queue
