### ISSUE TITLE
Difficulty recognizing MLT

### ISSUE THREAD

**Issue by nitrocalcite** [jliljebl/flowblade#288] opened 2016-11-30 23:11 UTC
I'm running Ubuntu 16.04.  The flowblade version in the repository - 0.14 - works just fine.  However, the .deb file for flowblade 1.8 does not recognize MLT.  I have tried `sudo apt install -f` and have checked that all my MLT versions are 6.0.0-2.  However, running `flowblade` in the command prompt returns this:
```
FLOWBLADE MOVIE EDITOR repository 1.8
-------------------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT not found, exiting...
ERROR: No module named mlt
```

This behavior is consistent when I tried downloading the 1.8 source.  I eventually figured out that if I run `sudo flowblade` then both the 1.8 source and the provided .deb function properly.  Is MLT installed or configured improperly?

**Comment by jliljebl** [comment] 2016-11-30 23:34
This is weird. If you give command "locate mlt.py" do you get these lines?

/usr/lib/python2.7/dist-packages/mlt.py
/usr/lib/python2.7/dist-packages/mlt.pyc

Maybe reinstalling everything by doing the following commands helps:

sudo apt-get remove flowblade mlt kdenenlive openshot

sudo apt autoremove

sudo apt-get install flowblade  (or maybe leaving this out omn second try of needed)

and then reinstalling the 1.8 package.

I don't know why MLT requires root to run. The problem is clearly with MLT installation.

**Comment by nitrocalcite** [comment] 2016-12-01 04:01
When I run `locate mlt.py` I get nothing back.  I've already tried the commands you suggested.  As an aside, the chroma key button randomly started doing nothing, even with variance turned all the way up.  I've tried restarting the program.  Could it be related?

**Comment by jliljebl** [comment] 2017-02-01 15:14
I'm closing this because I have no idea what could be the cause here.

**Closed by jliljebl** 2017-02-01 15:14 UTC
Labels: wontfix
