### ISSUE TITLE
Titler grey-screen

### ISSUE THREAD

**Issue by lodurr-voluspa** [jliljebl/flowblade#1065] opened 2022-09-15 23:43 UTC
I just upgraded from Ubuntu 20.04 to 22.04 and am running into an issue with the Titler.  

Flowblade version 2.8
MLT version 7.4.0
Ubuntu 22.04

When attempting to open the Titler it brings up the titler with a grey screen instead of the video image snapshot.  A pop-up in the main window then appears stating that only one instance of the titler may be open at a time even if there were no prior instances of the titler open.  The titler can generate png title images, however it seems to have no frame of reference to the video so there is no way to know where or if the text will appear.

I see the following error after opening the Titler.

Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/cairoarea.py", line 97, in _button_release_event
    self.release_func(event)
  File "/usr/share/flowblade/Flowblade/glassbuttons.py", line 520, in _release_event
    release_func()
  File "/usr/share/flowblade/Flowblade/tools/titler.py", line 97, in show_titler
    _titler.show_current_frame()
  File "/usr/share/flowblade/Flowblade/tools/titler.py", line 666, in show_current_frame
    rgbdata = PLAYER().seek_and_get_rgb_frame(frame)
  File "/usr/share/flowblade/Flowblade/mltplayer.py", line 284, in seek_and_get_rgb_frame
    rgb = frame.get_image(int(mlt.mlt_image_rgb24a), int(self.profile.width()), int(self.profile.height()))
AttributeError: module 'mlt7' has no attribute 'mlt_image_rgb24a'. Did you mean: 'mlt_image_rgba'?

**Comment by jep-fa** [comment] 2022-09-28 10:19
Flowblade version 2.8
MLT version 7.4.0
Ubuntu 22.04

Error in "/usr/share/flowblade/Flowblade/mltplayer.py", line 284, in seek_and_get_rgb_frame

**Replace**
rgb = frame.get_image(int(mlt.mlt_image_rgb24a), int(self.profile.width()), int(self.profile.height()))
**by**
rgb = frame.get_image(int(mlt.mlt_image_rgba), int(self.profile.width()), int(self.profile.height()))


Then a new error appears in /usr/lib/python3/dist-packages/mlt7.py line 648  :
**Replace**
def get_image(*args): return _mlt.frame_get_image(*args)

**by**
def get_image(*args): return _mlt7.frame_get_image(*args)

Then a new error appears in "/usr/share/flowblade/Flowblade/vieweditor/vieweditor.py  line 249
**Replace**
buf.shape = (self.profile_h + 1, self.profile_w, 4) # +1 in h, seemeed to need it

**by**
buf.shape = (self.profile_h, self.profile_w, 4) # NO +1 in h

Now the titler seems to work (not completely tested). First make a copy of the original files before modification.

**Comment by jliljebl** [comment] 2023-05-31 06:30
This one is fixed for upcoming Flatpak but I need to do a bug report upstream when I get around to it.

**Comment by jliljebl** [comment] 2023-10-05 16:21
This duplicate of #1094, I'll continue commenting on progress there.

**Closed by jliljebl** 2023-10-05 16:21 UTC
Labels: upstream bug
