### ISSUE TITLE
Lockup after Export Current Frame

### ISSUE THREAD

**Issue by taintedsushi** [jliljebl/flowblade#517] opened 2018-05-31 15:21 UTC
Please include the following information.
1) Flowblade version Z: 1.16.0
2) MLT version 6.6.0
3) Your distribution : Ubuntu Bionic Beaver

'Export Current Frame' is locking up Flowblade on my system.  It only happens when trying to export video frames, if you have an frame that is an imported picture, it works fine.

I compiled and installed the latest ffmpeg (4.0) but the problem persists.

If you run flowblade with -v and then [ctrl-c] when after the lockup, this is the output :+1: 

> [image2 @ 0x7f678002ce60] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
> 
> ^CTraceback (most recent call last):
>   File "/usr/share/flowblade/Flowblade/editorwindow.py", line 182, in <lambda>
>     ('ExportScreenshot', None, _('Current Frame'), None, None, lambda a:exporting.screenshot_export()),
>   File "/usr/share/flowblade/Flowblade/exporting.py", line 387, in screenshot_export
>     render_screen_shot(frame, get_displayed_image_render_path(), "png")
>   File "/usr/share/flowblade/Flowblade/exporting.py", line 436, in render_screen_shot
>     time.sleep(0.05)
> 

The deprecation warning occurs with good captures as well so likely has little to do with it.

Further dicking around reveals that it seems to be something about my particular project that is causing the error.  If I can figure out why I'll let you know.

Hope this helps.
Cheers.

**Comment by taintedsushi** [comment] 2018-05-31 16:26
Here's the scoop.

Create a project HD 1080p 23.98 fps.
Drop in media which it detects as 4K UHD 2160p 30fps
Media is actually 640x360
If I keep my current profile, export works fine
If I change it to the media profile, export no work.

I changed the project profile back to 1080p and now the export current frame works.

In the end this seems to be a media detection issue.

**Comment by jliljebl** [comment] 2018-06-01 22:48
Ok, will look at this.

**Comment by jliljebl** [comment] 2019-02-26 13:43
I was able to reproduce this.The underlying reason is probably that such extreme differences in image sizes exceed what MLT code can handle.

I see no point in spending energy trying to patch MLT for this, but I'll give a quick look on the profile detection side of things.

The lockup its self will get *wontfix* and mention in known Issues.

**Comment by taintedsushi** [comment] 2019-02-26 13:48
OK.  No problem.  Thanks for the update.

2.0 looks great by the way.  

Cheers.

**Comment by jliljebl** [comment] 2019-02-26 13:55
I patched the profile matching heuristic to penalize profiles with 2x size difference, which sort of fixed this because the suggested profile was HD 720p 30fps.

Otherwise I think the lockup will remain unfixed.

**Closed by jliljebl** 2019-02-26 13:55 UTC
