### ISSUE TITLE
.png images glitch. Compositor.

### ISSUE THREAD

**Issue by rredesigns** [jliljebl/flowblade#182] opened 2015-12-14 18:00 UTC
Hello everyone. 

I found this to be a real problem. I was trying to do some basic motion graphics test with the first non-linear editor that won't crash on me, which is Flowblade, but something weird is happening.

I use the Affine filter to move around some bars I made, and it does work but the original images show in the background through the whole scene, and also are written in the render.

[Here's a screencap](http://i.xomf.com/rfncv.png)

I can also provide the project file if needed. Thanks in advance.

**Comment by jliljebl** [comment] 2015-12-16 17:41
Can you do "Save Backup Snapshot..." and then make the folder with its contents available to download? It is not clear to me from your explanation and screenshot what is happening and I'm unable to reproduce anything similar on my system.

**Comment by rredesigns** [comment] 2015-12-22 23:52
Ok, the snapshot is ready, you can find it [here](http://www.mediafire.com/download/4udxnpl7g0qgphq/Flowblade+Backup+Snapshot.zip)

Sorry this took so long, I had a storme recently and brought the phone line down, so I had no internet. 

Regards.

**Comment by jliljebl** [comment] 2015-12-22 23:59
Thanks, I downloaded it. I will look at this after Christmas break in January.

**Comment by vencax** [comment] 2016-10-04 13:36
Anything new? I have experienced similar (maybe the same problem). I prepared title image in kdenlive, saved to png and when importing to bin, it is "blured".
![orig - sharp edges](https://cloud.githubusercontent.com/assets/1184334/19076175/0a6ba4d0-8a48-11e6-9300-0fb2fb703d90.png)
![blured in rendered video (its blured even in clip explorer)](https://cloud.githubusercontent.com/assets/1184334/19076174/0a67bae6-8a48-11e6-81e6-7e75538fb84a.png)

**Comment by jliljebl** [comment] 2016-10-04 14:10
Are you getting the same result when using e.g. "Dissolve" and "Affine Blend" Compositors? They use different underlying tech to do the composite and "Affine Blend" should produce better results.

**Comment by rredesigns** [comment] 2016-10-04 14:10
I don't think this is the same issue at all. My problem was that the png's I was using still showed up in the background. I blurred them on purpose.

**Comment by jliljebl** [comment] 2016-10-04 14:17
So you are using "Affine" filter, not Compositors to do the Affine transformation?

**Comment by jliljebl** [comment] 2016-10-04 14:27
One thing that can happen is that you are not using *any* Compositor and the edge smoothing information is on alpha channel, and it is not used because no compositing is done. Then you only get full black and white pixels.

Does using Compositor to place title on top of another image smooth the edges.

**Comment by rredesigns** [comment] 2016-10-04 14:51
@vencax why are you using Kdenlive in a first place? I don't know how the export process is from that application, but you shold try compositing all png's inside Flowblade first to know if it is a Flowblade issue after all. You can't get some other package involved.

**Comment by jliljebl** [comment] 2016-10-04 16:37
@rredesigns, yeah, I agree that vencax issue is not same as your earlier issue.

 @rredesigns, I have to admit that "Affine" filter is on my "do-not-waste-time-on-this" list because it just does not seem to work correctly, and fixes would require a lot of work in MLT. This cannot be fixed in Flowblade

For simple motion graphics  in Flowblade I recommend using multiple tracks and "Affine Blend" Compositor. The next improvement on this front will be Natron integration work, and after that a completely new affine transform filter may be developed some time later.

But for now, I'm unfortunately going to close this as wontfix.

**Closed by jliljebl** 2016-10-04 16:37 UTC

**Comment by jliljebl** [comment] 2016-10-04 16:39
I'll add a known issue item.

**Comment by rredesigns** [comment] 2016-10-05 18:51
Good. I will do motion graphics in Blender now. I will still use Flowblade since it has better stability than Openshot and Kdencrash. But for complicated stuff I will stick to Blender. Cheers. :D

**Comment by vencax** [comment] 2016-10-05 19:36
And what about my problem? Should I create another issue for it? Because its not caused by MLT since I did my vids corectly today with kdenlive (which uses MLT as well).

**Comment by jliljebl** [comment] 2016-10-05 22:14
@vencax Yes, filing a new Issue is best here. Please:
- Add detailed verbal description of the problem
- Add here a screen shot of application with clips and Compositors on the timeline in positions triggering the problem 
- Add here the .png file causing the problem

@rredesigns Node compositors are better for surprisingly simple motion graphics in my view, so using Blender or Natron is often the right choice. The "Affine" filter isn't the only missing piece in developing Flowblade as motion graphics tool, this is going to be a long process.
