### ISSUE TITLE
Gmic Render Error

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#373] opened 2017-04-21 06:50 UTC
```
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file '/home/benrob0329/.flowblade/gmic/session_1492757175532/render_frames/frame_0267.png' at position 0 (1 image 1920x1080x1x3).
[gmic]-1./ Apply raindrops deformation on image [0], with amplitude 80, density 0.1, wavelength 1 and 0 merging steps.
[gmic]-1./ Output image [0] as  file '/home/benrob0329/YouTube', with pixel type 'float'.
[gmic]-1./ Input file 'Stuff/gmic' at position 1
[gmic]-1./ [0;31;59m[1m*** Error *** Unknown filename 'Stuff/gmic'.[0;0;0m

Return code:255
```

**Comment by jliljebl** [comment] 2017-05-14 09:57
Does this happen always when trying to render with Gmic tool or just in some cases?

**Comment by jliljebl** [comment] 2017-07-31 16:11
This has not been updated and single G'Mic render errors can happen for reasons unrelated to Flowblade so I will be closing this. as *not a bug* as causes er very likely to be unrelated to Flowblade source code.

**Comment by jliljebl** [comment] 2017-08-15 08:51
Seems that installing G'MIC plugin for gimp from Ubuntu PPA: ppa:otto-kesselgulasch/gimp causes this.

The exact cause of this is unknown so far but this is either :
1) G'MIC has changed interface
2) Gimp plugin causes some environmental changes that break Flowblade G'MIC tool.

**Comment by jliljebl** [comment] 2017-08-15 09:53
@benrob0329 Hi, could you answer a few questions:
1) Which distro you are using?
2) Do you have G'MIC plugin for Gimp installed?
3) Did you install it from ppa:otto-kesselgulasch/gimp or some other way?
4) Which version G'MIC you are using command 'gmic' on termminal gives the answer?

**Comment by benrob0329** [comment] 2017-08-15 12:39
I don't use that install anymore, but I'll try and give as many details as I can remember:

1: KDE Neon (Ubuntu 16.10)
2: Yes
3: Not as far as I know
4: Whatever the base version is on 16.10

This might not be 100% accurate, but since that install is long gone its hard to say.

**Comment by jliljebl** [comment] 2017-08-15 13:00
Thanks.

The important factor in play here is that I discovered that G'MIC Gimp plugin installs a *different version* of gmic binary then that which is in Ubuntu repos, at least on my Ubuntu 17.04.

This new gmic binary *does not* support the command line switches like "-gimp_8bits" used by Flowblade G'MIC tool and so the plugin breaks it.

But if you no longer have the same install we can't confirm this on your system.

On my system the evidence is conclusive: installing gmic binary from  PPA: ppa:otto-kesselgulasch/gimp breaks Flowblade G'MIC tool.

**Comment by IvanDSM** [comment] 2017-10-30 16:23
To fix the command line switches issue, one just needs to change -gimp to -fx, so "-gimp_8bits" would become "-fx_8bits". I have started using Flowblade as my editor and have already processed around 8 clips in this way! :)

On @benrob0329's issue, this happened to me while using a path that had spaces, for example "/home/IvanDSM/The Video Folder". This issue is not present when using a path that has no spaces, such as "/home/IvanDSM/the_video_folder".

**Comment by jliljebl** [comment] 2017-10-30 18:34
Thanks, I'll try this.This could make it possible to have Flowblade working with G'MIC Gimp plugin on all systems.
*  The command line switches could have changed for some newer version, so if I can figure out the version when change happened I can give different switches for different gmic binary versions
* I could also try to do some test render on startup to detect which switches cause errors, but this is quite hacky

I'll also test the 'spaces in path' problem to see if I can reproduce.

**Comment by IvanDSM** [comment] 2017-10-30 18:45
I'm pretty sure it was a change introduced in a new version. I was using 2.0.4 on my desktop when I saw that. I'll test out different G'MIC versions as soon as I am able to and see if I can find the version where they changed the switch.

**Comment by jliljebl** [comment] 2017-12-01 17:28
This is like @IvanDSM suspected, G'MIC >= 2 changes "*gimp_*" to "*fx_*". The application has been patched to work with both versions and starting from 1.16 works with both.

WORKAROUND: **Change all switches starting with -gimp to -fx, so e.g.
"-gimp_8bits" becomes "-fx_8bits".**

**Comment by jliljebl** [comment] 2018-04-22 16:36
1.16 is out for a while, we can close this now.

**Closed by jliljebl** 2018-04-22 16:36 UTC
Labels: fixed, workaround in comments
