### ISSUE TITLE
High GPU usage with Flowblade open and empty.

### ISSUE THREAD

**Issue by DroWnThePoor** [jliljebl/flowblade#898] opened 2020-08-02 03:58 UTC
Please include the following information.
1) Flowblade version (Help->About): Flatpak 2.4.0(but applies to prior versions too)
2) MLT version (Help->Runtime Environment): MLT 6.18
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Simply open Flowblade and monitor GPU temps.
With Flowblade simply and with no project or content just a blank interface, my Nvidia Quadro temps can go up to 79C degrees.
It can also occur with a project open and minimized. However it is not consistent. In the course of writing this, the temp has fallen to 68C after remaining at 79C for at least 5 minutes. 
I know this may seem ambiguous, but it's somewhat important in my opinion.
If there's anything else I can do to help figure this out let me know.

**Comment by jliljebl** [comment] 2020-08-02 14:46
Flowblade should not run anything on GPU currently, no idea on the cause here. Keeping this open for until issue is understood better.

**Comment by jliljebl** [comment] 2020-10-31 08:58
I'm closing this as *unreproduced*. 

This could be related to Flowblade continually producing frames to display at all times and thus causing GPU work on composited systems but this will only addressed when a new video consumer is created.

**Closed by jliljebl** 2020-10-31 08:58 UTC
Labels: unreproduced
