### ISSUE TITLE
can't maximise the screen

### ISSUE THREAD

**Issue by sh2515** [jliljebl/flowblade#246] opened 2016-06-20 22:47 UTC
ubuntu 16.04
flowblade 1.6

when open the screen is too wide, so I try and maximize the screen and nothing happens.

**Comment by jliljebl** [comment] 2016-06-21 08:00
What is the screen size of your computer?

Please also post a screenshot of the problem after the attempted maximize. 

 Do you mean the you try to maximize the monitor displaying the video output?

**Comment by ManticoreII** [comment] 2016-06-30 10:05
Same problem in SUSE Tumbleweed - flowblade 1.6.
Screen size 1280x1024
Flowblade 1331x883
No maximize - resize works only vertically.

**Comment by jliljebl** [comment] 2016-10-02 16:13
Confirmed.

**Comment by jliljebl** [comment] 2016-10-02 17:31
This has now been improved for all accepted screen sizes and application maximizes on all screen sizes.

The fix is in repository and will be in release 1.10.

**Comment by KJ2ME** [comment] 2016-12-22 22:50
I have same problem on Ubuntu-Gnome 16.04 using the release 1.10.

**Comment by jliljebl** [comment] 2016-12-22 23:03
@KJ2ME Could you please *at least* state the resolution you have, and in addition a screen shot of the problem would be helpful.

"I have same problem on Ubuntu-Gnome 16.04 using the release 1.10." provides no actionable information.

**Comment by KJ2ME** [comment] 2016-12-22 23:07
Sorry, my resolution is 1600x900 (16:9)

Capture: http://imgur.com/a/0zFgX

**Comment by jliljebl** [comment] 2016-12-22 23:10
Ok, 1600x900 is a resolution I did not test for 1.10, so now I now what to test to fix the problem.

**Comment by jliljebl** [comment] 2017-02-07 09:03
I'm unable to test this. I have 2 monitors and a laptop but none of them had 1600x900 resolution available.

I'm going to need a patch from somebody who can work on this resolution. Post here if you are looking into working on this, and need some pointers for where to look for a fix.

**Comment by galindro** [comment] 2017-02-08 20:55
This problem is occurring with me too. I'm using Debian 8. This is my screen specs:

Size: 14"
Resolution: 1366x768 (16:9)

**Comment by jliljebl** [comment] 2017-02-09 10:02
@galindro Can you post screen a screenshot? My Ubuntu 16.10 with Flowblade 1.10+ and Gnome Shell looks fine:
![screenshot from 2017-02-09 11-57-53](https://cloud.githubusercontent.com/assets/1823444/22778415/88b6cd34-eebf-11e6-935f-d65437527314.png)

**Comment by dvdlvr** [comment] 2017-02-11 15:13
I tested this on both 1600x900 and 1366x768 on Ubuntu 16.10 (Unity) with Flowblade 1.10 installed yesterday and Flowblade would automatically open maximized. 
I could then both Unmaximize and Maximize without a problem.

Note that if you open Flowblade using a higher screen resolution and THEN switch to a lower screen resolution you may not be able to maximize to the new, lower, resolution.

**Comment by jliljebl** [comment] 2017-02-11 16:48
Ok, test by @dvdlvr is believed to be reliable and I'm closing this as *invalid*. I will reopen if further info on the problem is provided.

**Comment by timbze** [comment] 2020-07-21 01:50
I had the same issue in 1366 x 768 and 1360 x 768
Flowblade 2.6.0.1
Ubuntu 20.04

But my taskbar (dock) was pinned to the bottom. After I enabled "Auto-Hide dock" in Ubuntu settings, Flowblade automatically opened maximized and I was able to unmaximize/maximize

**Comment by jliljebl** [comment] 2020-08-14 16:02
Reopening.

**Comment by jliljebl** [comment] 2020-12-22 11:45
I have updated layout code completely for 2.8 so all possible problems on this front are new best handled in a new Issue if discovered.

**Comment by Anifyuli** [comment] 2024-01-22 13:58
I get same issue on my system. I can't maximize with keyboard shortcut or with maximize button
Distro : Ubuntu 23.10
Version : 2.12.0.2
Source : Flatpak

**Comment by jliljebl** [comment] 2024-01-23 07:52
@Anifyuli Hi, could you post a screenshot and give info on the desktop environment you are using?

**Comment by Anifyuli** [comment] 2024-01-23 08:07
I'm using Ubuntu 23.10 with GNOME 45.2

![Screenshot from 2024-01-23 15-02-45.png](https://github.com/jliljebl/flowblade/assets/73734843/77754b5b-ee44-4e59-b046-b6f822ec967c)

If I use it sometimes, its window will be a regular rectangle and missing it rounded corners

**Comment by jliljebl** [comment] 2024-02-19 14:22
This was fixed for 768px height screens, now working again, fix will be in next release 2.14.

**Closed by jliljebl** 2024-02-19 14:22 UTC
Labels: bug
