### ISSUE TITLE
Deshake (vid.stab)

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#723] opened 2019-10-06 12:09 UTC
I've noticed MLT 6.16 on newer Ubuntu versions are built with the vid.stab library.

I've tried to enable the singlepass version, like so (in filters.xml):

```
    <filter id="deshake">
        <name>Deshake</name>
        <group>Fix</group>
        <property name="shakiness" args="range_in=1,40">4</property>
        <property name="accuracy" args="range_in=1,15">4</property>
        <property name="smoothing" args="range_in=0,100">15</property>
        <property name="optzoom" args="range_in=0,2">2</property>
        <property name="zoomspeed" args="range_in=0,1">0.25</property>    
    </filter>
```

But somehow flowblade locks up on start.

`melt -query filter=deshake`

Does confirm deshake is available.

**Comment by jliljebl** [comment] 2019-10-06 12:25
Yes, your xml is correct but some MLT filters don't work on Flowblade. Anything with Qt crashes immediately and generally anything attempting to use GPU does also.

Qt stuff will not be worked but GPU stuff will be in time.

With this particular filter, I don't know what the problem is but fixing it will require deep dive in MLT and  I'm not going to do this for the moment.

I'll close with a "soft" *wontfix* meaning that this Issue can be returned into and contributions will be accepted but for now it is clearly not on agenda, so I'm closing it.

**Closed by jliljebl** 2019-10-06 12:25 UTC

**Comment by pmjdebruijn** [comment] 2019-10-06 13:01
Fair enough. I guess one could argue, giving how stabilization affects the image, a two pass variant under "Tools" for pre-processing material could make more sense, as opposed to a filter that's applied on the fly.

**Comment by jliljebl** [comment] 2019-10-06 15:10
Yes, that would be a good tool that nicely fits with the Flowblade concept of offering helper tools.

I think it is possible to pull stabilization from **ffmpeg** in a similar way that your end credits idea worked (or maybe from OpenCV which has Python bindingsr ) so this is quite doable.
