### ISSUE TITLE
Pictue in Picture stutters when zooming

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#293] opened 2016-12-13 06:20 UTC
Hello,

the zoom effect should be modified. Whe zooming a picture or video its not smooth. Its jerking.
Please see the video.

Regards, Mario!

https://www.youtube.com/watch?v=FJnrwsrtwCc&feature=youtu.be

**Comment by jliljebl** [comment] 2016-12-13 08:11
Could you post a screenshot of the timeline for the video showing clips
effect and compositor used to create the video, or a detailed text
description of effects /compositors used.

**Comment by oluja1973** [comment] 2016-12-13 12:08
Its very simple. Black background on v1. Picture on v2 and a picture in picture effect with two keyframes. Butt see both screenshots.
![p1](https://cloud.githubusercontent.com/assets/23220631/21139861/3dda80ba-c135-11e6-9058-710bfd65b52d.png)
![p2](https://cloud.githubusercontent.com/assets/23220631/21139863/41c7d1be-c135-11e6-8b06-28b045373660.png)

**Comment by jliljebl** [comment] 2016-12-13 12:51
Confirmed, for Picture In Picture, but Affine Blend does not display this problem, right.

Affine Blend does however show the background through in a way that is not optimal if the zoom is not fully contained with in the image.

The situation is that:
a) Picture In Picture uses some old code in MLT and Dan Dennedy has (if I remember correctly) stated that he will not redo it because it uses code algorithm that causes these type of effects and would require complete rewrite using other algorithms. So fixing Picture in Picture is out. But Picture in Picture gets the beckground right.

b) With Affine Blend zoom is smooth but it is showing the background. Problem is that it is composited using frei0r library with a plugin I wrote years ago and it gets that background thing wrong because it provided with the image in a wrong way.

c) Using the filter to transform does not work very well in MLT and will again require fixes in MLT.

I will look more carefully if I have missed some way to do this right using existing API.

Situation needs to be improved but it will take some time to get better before the correct approach is decided on and fix implemented. In my view the best way forward would be to move the Cairo based solutions (like Affine Blend)  inside MLT but I'm going to have to contribute this myself.

**Comment by jliljebl** [comment] 2016-12-13 13:33
There is a workaround described in the screenshot:
1 )set black color clip on track V1
2) set transformed image on track V2 and composite it using Affine blend on track V1
3) set black color clip on track V3 and composite in on track V1 using Picture in Picture by setting destination track to V1

This works,
![workaround](https://cloud.githubusercontent.com/assets/1823444/21142141/7bb18aaa-c149-11e6-91a2-ed0c9a8b4965.png)
 but is obviously very much a bit silly.

**Comment by oluja1973** [comment] 2016-12-14 15:11
Yes thanks. The affine blend is much more smoother then the Picture in Picture. But ist not neccessary to add the second color clip on v3. Ist working also without the v3 Clip.

Regards, Mario!

**Comment by jliljebl** [comment] 2017-02-01 08:36
Closing this as *wontfix* because no fix is in sight and affine blend works better and is an acceptable work around.

**Closed by jliljebl** 2017-02-01 08:36 UTC
Labels: wontfix
