### ISSUE TITLE
Too small screen because of 2X scaling in a HiDPI screen

### ISSUE THREAD

**Issue by bjesus** [jliljebl/flowblade#492] opened 2018-04-29 10:34 UTC
Hi,
I tried running Flowblade on my X1 Yoga (2nd Gen). My screen is a HiDPI 2560x1440 screen, but Flowblade sees it as 1280x720 screen and gives me the "Too small screen" error upon running.

Is there any solution to that? Or is this by design?

```
FLOWBLADE MOVIE EDITOR 1.16
---------------------------
modules path: /usr/share/pyshared/Flowblade
MLT found, version: 6.6.0
numpy version: 1.14.2
OS: Arch Linux
Python 2.7.14 (default, Apr 16 2018, 20:08:15)
[GCC 7.3.1 20180406]
GTK+ version: 3.22.30
```

**Comment by jliljebl** [comment] 2018-04-29 16:49
So the problem is that GTK is running with scale factor = 2 and this makes screen apper too small to run Flowblade.

There is no way Flowblade can be made work to with 720pix height screen, so we need to run Flowblade with scale factor = 1.

Can you try the following:

1. Start Flowblade from terminal with command:

```bash
 env GDK_BACKEND=x11 GDK_SCALE=1 flowblade %f
```

2. Select from menu: *Edit->Preferences* and from *View* panel select *Track Heights: Double HiDPI - 100px, 50px*

Does this work for you?

**Comment by bjesus** [comment] 2018-04-29 17:02
Thank you, it works beautifully.

I'm wondering, can't Flowblade detect the current scale factor and then run regularly? Is there a technical problem to do it? I can try and submit a pull request if it's needed.

**Comment by jliljebl** [comment] 2018-04-29 17:14
I don't know if that can be done, but I will certainly pull a patch that does that.

**Comment by jliljebl** [comment] 2019-09-27 07:05
There is info on this in https://github.com/jliljebl/flowblade-forum now.

i don't think we can affect scaling factors from inside application, closing the issue.

**Closed by jliljebl** 2019-09-27 07:05 UTC
Labels: workaround in comments
