### ISSUE TITLE
Profiles double

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#284] opened 2016-11-21 15:09 UTC
Hello,

found that this profiles double exists in flowblade:
HD 720p 25 fps
HD 720p 29.97 fps
HD 720p 50 fps
HD 720p 59.94fps

Regards, Mario!

**Comment by jliljebl** [comment] 2017-02-01 15:03
They have different frames per second values, and are as such different profiles, closing this s *invalid*.

**Comment by oluja1973** [comment] 2017-02-01 15:07
Im sorry but this is wrong. There are exactly the same profiles double. e.g. HD 720p 25 fps exists 2 times and have they same values

**Comment by jliljebl** [comment] 2017-02-01 15:51
So it seems. There two profile files for each, one starts with "atsc_" and other one with "hdv_" but the files have the same contents.

I cannot remove one set of these files because then all projects made with these profiles will fail. I will need to write some special code to hide some files from selection lists.

**Comment by jliljebl** [comment] 2017-02-06 17:33
Fixed by contribution, will be in 1.12.

**Comment by jliljebl** [comment] 2017-02-07 10:30
The fix caused a regression and was reverted.

**Comment by jliljebl** [comment] 2017-04-06 12:49
The dvdlvr fix was correct and has been reactivated. This is fixed will be 1.14.

**Closed by jliljebl** 2017-04-06 12:49 UTC
Labels: bug
