### ISSUE TITLE
Does not start, crashes

### ISSUE THREAD

**Issue by mrkaato** [jliljebl/flowblade#477] opened 2018-02-07 11:39 UTC
1.14-1 and v1.0.r318.ga807cf7-1
both crash immediately upon launch.
Manjaros after the last update has come.
Linux 4.14.16-1

**Comment by jliljebl** [comment] 2018-02-07 12:57
Since Manjaro is Arch based, this likely duplicate of fixed Issue #445, see the latest comments. @mrkaato  Can you confirm?

**Comment by mrkaato** [comment] 2018-02-07 18:49
Yes, sorry for the duplicate.

**Comment by jliljebl** [comment] 2018-02-08 09:11
Closing as duplicate of #445.

**Closed by jliljebl** 2018-02-08 09:11 UTC
Labels: duplicate, fixed upstream
