### ISSUE TITLE
filter "freeze" segfaults flowblade

### ISSUE THREAD

**Issue by protonenfalter** [jliljebl/flowblade#240] opened 2016-06-08 16:05 UTC
environment:
flowblade 1.6 executed as script (no .deb) on Ubuntu Gnome 14.04

workflow:
- add medium (video, .mp4 or .mov)
- put video on track V1
- cut off some at the beginning and the end (so that about 15 sec. of video are left out of the middle)
- apply filter "freeze" by dragging and dropping from the menu onto track V1

expected result:
filter is applied to V1

actual result:
flowblade segfaults (message in console: segfault (core dumped))

**Comment by jliljebl** [comment] 2016-08-20 12:37
Closing as duplicate of:

https://github.com/jliljebl/flowblade/issues/86

**Closed by jliljebl** 2016-08-20 12:37 UTC
Labels: duplicate
