### ISSUE TITLE
Flowblade installed via flatpak does not import images

### ISSUE THREAD

**Issue by LeosWelt** [jliljebl/flowblade#559] opened 2018-10-25 10:58 UTC
Please include the following information.
1) Flowblade 1.16.0
2) MLT 6.11.0
3) Pure Arch Linux (installed by ZEN-Installer)

When i launch the flatpak-version installed like shown in https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md everything works fine.
The rendering functions do what they should do, the arch-linux-version installed by pacman does not do this in my case, so i tried the flatpak version.

But i can not add a png-file as clip. The clip is shown as a white rectangle, and a process named "python2" is started below Flowblade, and it starts consuming all memory. I have 32GB of RAM, and a 60GB swap-SSD, and it grows and grows. This python2-process can be stopped the hard way, Flowblade is not aborted, it can be used, but the image is not shown. When double clicking the images it is shown correct in the preview, but it can not be used on the timeline.

![bildschirmfoto zu 2018-10-25 12-43-05](https://user-images.githubusercontent.com/43585766/47495517-a7457680-d854-11e8-8839-97115d9cf08b.jpg)
The konsole shows

[image2 @ 0x7f6f04200f00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

when trying to insert the image, it hangs there until the python2-process is killed the hard way

Thanks a lot

Hartmut

**Comment by jliljebl** [comment] 2018-10-25 11:18
Ok, thanks for info, will look at this after next release.

This is getting fucking annoying with the constant upstream breakage, and I will probably need to fork MLT eventually, but that will take some time.

**Comment by awiprayitno** [comment] 2019-01-07 05:02
Same thing happened for me with the flatpak version. Flowblade 2.0 with MLT 6.6 does NOT have this issue.

**Comment by awiprayitno** [comment] 2019-01-07 05:05
Probably for the same reason, flowblade flatpak (mlt 6.11) cannot render title as well.

**Comment by eszlari** [comment] 2019-02-04 12:57
@jliljebl The MLT version bundled with the flatpak can be changed to any version or git commit!

**Comment by jliljebl** [comment] 2019-02-04 16:26
I did a pull request https://github.com/jliljebl/io.github.jliljebl.Flowblade/pull/1 to use 6.12, lets use that first.

**Comment by jliljebl** [comment] 2019-02-04 16:32
Here's a good one https://github.com/jliljebl/io.github.jliljebl.Flowblade/pull/2

**Comment by eszlari** [comment] 2019-02-06 00:41
I found the cause of this issue: gtk2 was missing (It was removed from the GNOME flatpak runtime in v3.30), which is needed for importing images.

https://github.com/flathub/io.github.jliljebl.Flowblade/commit/e00ccc920c1155b343bcfd409287d72912c42a73

**Comment by jliljebl** [comment] 2019-02-06 12:20
I build Flatpak with updates and can confirm, this is now fixed with Flatpak for Flowblade 2.0. Great. The glitch with build bugging out on gmic the first time, but completing successfully the second time (?1?) persisted, but it worked.

I sort of figured this myself in the evening too, I didn't yet get working solution, but now we have it.

**Closed by jliljebl** 2019-02-06 12:20 UTC
