### ISSUE TITLE
The distutils package is deprecated and slated for removal in Python 3.12

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#1034] opened 2021-12-12 12:51 UTC
Hi when running flowblade-2.8.0.3 on Fedora 35 i get the following error message:

```
[martin@fc35 SPECS]$ flowblade 
FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /usr/bin
Running from installation...
/usr/bin/flowblade:39: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.sysconfig import get_python_lib
/usr/bin/flowblade:39: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils.sysconfig import get_python_lib
MLT not found, exiting...
ERROR: No module named 'mlt'
```

1) Flowblade version : flowblade-2.8.0.3
2) MLT version : mlt-7.2.0
3) Your distribution : Fedora 35

**Comment by martinkg** [comment] 2021-12-13 11:05
After run this command the program core dumps.

```
[root@fc35 tmp]# find  /usr/lib/python3.10/site-packages/Flowblade/ -type f -name "*.py" -exec sed -i 's/import mlt$/import mlt7 as mlt/g' {} +
[root@fc35 tmp]# sed -i 's/import mlt$/import mlt7 as mlt/g' /usr/bin/flowblade
```
[fb-coredump.txt](https://github.com/jliljebl/flowblade/files/7703208/fb-coredump.txt)

**Comment by smolnp** [comment] 2021-12-13 11:54
Flowblade won't start on Fedora linux #928

**Comment by jliljebl** [comment] 2021-12-26 14:54
This is not a *distutils* related issue this  is duplicate of #1020 because: *ERROR: No module named 'mlt'*.  I'll make all modules import both mlt and mlt7.

**Comment by jliljebl** [comment] 2021-12-27 09:41
@martinkg  I Installed Fedora 35 on VM and turns out that it has MLT 6.26. Did you install mlt-7.2.0 from source? If so, can you try current repo Flowblade and see if that works, I pushed a patch that makes Flowblade import mlt7 too?

**Comment by martinkg** [comment] 2021-12-27 10:26
> @martinkg I Installed Fedora 35 on VM and turns out that it has MLT 6.26. Did you install mlt-7.2.0 from source? If so, can you try current repo Flowblade and see if that works, I pushed a patch that makes Flowblade import mlt7 too?

I created a rpm package from the current mlt-7.4.0 mlt sources. You can find the src.rpm package here:
https://martinkg.fedorapeople.org/Packages/mlt/
I will try your current patch and see if it can import mlt7.

**Comment by martinkg** [comment] 2021-12-27 11:32
mlt-7.4.0 is installed 
rpm -qa |grep mlt

```
mlt-7.4.0-1.fc35.x86_64
mlt-devel-7.4.0-1.fc35.x86_64
mlt-freeworld-7.4.0-1.fc35.x86_64
python3-mlt-7.4.0-1.fc35.x86_64
```
but flowblade fails with:

```
[martin@fc35 flowblade-trunk]$ ./flowblade 
FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /home/martin/rpmbuild/BUILD/flowblade-995313a509b80e99eb1ad550d945bdda5995093b/flowblade-trunk
Running from filesystem...
MLT found but version info not available. MLT probably too old to work reliably...
numpy version: 1.21.1
Application version: 2.8.0
OS: Fedora Linux 35 (Workstation Edition)
Python 3.10.1 (main, Dec  7 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
GTK+ version: 3.24.31
XDG user data exists.
Locale: de_DE
Translations at /usr/share/localeru/LC_MESSAGES/flowblade.mo were not found, using /usr/share/locale translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Gtk version is 3.24.31, Flowblade theme is available.
Using Full Screen size for layout: 1920 x 1200
Small height: False
Small width: False
Detecting environment...
```

**Comment by jliljebl** [comment] 2021-12-27 12:53
Well, I'll try to get Flowblade going with mlt7 or later, haven't tried it yet here, may take a while.

**Comment by smolnp** [comment] 2021-12-27 19:25
I have MLT 6.26 and the terminal gives the same thing
[995313a509b80e99eb1ad550d945bdda5995093b.txt](https://github.com/jliljebl/flowblade/files/7781515/995313a509b80e99eb1ad550d945bdda5995093b.txt)
.

**Comment by jliljebl** [comment] 2022-01-12 10:02
Ok, putting a breakk here for a few weeks, will look at when activity resumes.

**Comment by jliljebl** [comment] 2023-06-16 08:05
Opened new Issue for this #1091, closing this as merged.

**Closed by jliljebl** 2023-06-16 08:05 UTC
Labels: Python issue
