### ISSUE TITLE
title causes distortion in mixed aspect ratio project

### ISSUE THREAD

**Issue by notklaatu** [jliljebl/flowblade#258] opened 2016-08-24 09:06 UTC
This is probably an edge case, but if I have 4:3 footage in a 16:9 project, when I apply a Title to my clip along with an Affine Blend, there is massive distortion along the pillarboxes.

Attached is a photo.

![titledistort](https://cloud.githubusercontent.com/assets/2211671/17924842/799166b2-6a3e-11e6-9156-8c206b5fbe2f.png)

Version info:
Slackware 14.2
flowblade-1.6-x86_64
frei0r-1.4-x86_64
mlt-master-6-2-0-x86_64

**Comment by jliljebl** [comment] 2016-10-04 21:36
Confirmed. Trying this clip arrangement on KDEnlive crashes immediately when frame pointer is on area desplaying this issue on Flowblade.

A work around using different clip arrangement exists, and is shown on screencap below:
![screenshot from 2016-10-05 00-29-55](https://cloud.githubusercontent.com/assets/1823444/19093247/0859264a-8a93-11e6-9a36-2923ed72a4f6.png)

I'm closing this as wonfix because:
a) this is a marginal Issue
b) workaround exists
c) fixing would require unknown amount of work on MLT, this is not Flowblade issue.

**Closed by jliljebl** 2016-10-04 21:36 UTC
