### ISSUE TITLE
Not working Edit values for timeline clips

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#883] opened 2020-07-08 11:48 UTC
Following the guide "Step 3: Set values for timeline clips" I select the frame of the clip, click "Preview" but nothing happens, flowblade freezes.

The dialog does not close, Flowblade windows do not react to anything.

terminal output:

Loading transitions...
Blender render complete.
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/family/flowblade-master/flowblade-trunk/Flowblade/jobs.py", line 651, in run
    job.callback_object.update_render_status() # Make sure these methods enter/exit Gtk threads.
  File "/home/family/flowblade-master/flowblade-trunk/Flowblade/containeractions.py", line 816, in update_render_status
    self.program_editor_window.preview_render_complete()
  File "/home/family/flowblade-master/flowblade-trunk/Flowblade/tools/simpleeditors.py", line 168, in preview_render_complete
    self.preview_panel.preview_surface = cairo.ImageSurface.create_from_png(self.get_preview_file())
cairo.Error: file not found
------------------------------------------------

Flowblade 2.6 commit 6106d8bef821fd62b99458d0862fbb9352f21409

**Comment by smolnp** [comment] 2020-07-08 12:01
![flowblade_bag](https://user-images.githubusercontent.com/26217756/86916140-cc167600-c12b-11ea-9eae-665bd6f615ab.png)
![flowblade bag2](https://user-images.githubusercontent.com/26217756/86916144-ce78d000-c12b-11ea-8a83-78133fc731ae.png)

**Comment by jliljebl** [comment] 2020-07-11 07:50
Ok, thanks, this feature clearly needs more work still.Works here, need to figure out diff to your system.

**Comment by smolnp** [comment] 2020-07-18 21:09
It can't depend on the Blender version?
log_blender_project_init:
Blender 2.83.0 (hash unknown built 2020-06-21 00:00:00)
Read prefs: /home/family/.config/blender/2.83/config/userpref.blend
Read blend: /home/family/Downloads/colors.blend
Error: Not freed memory blocks: 8, total unfreed memory 0.008789 MB

**Comment by jliljebl** [comment] 2020-07-21 07:38
I don't think this is about version, versions 2.82+ should work.

> Error: Not freed memory blocks: 8, total unfreed memory 0.008789 MB

 At least there is another reproduction target here, if I see this I know I'm hitting the same issues as you are.

**Comment by jliljebl** [comment] 2021-01-09 16:26
Ok, I have tested this on 4 systems: Ubuntu 20.04, 20.10 and on VM with Linux Mint 20 and Fedora 33. This works on all these systems.

The

    Error: Not freed memory blocks: 8, total unfreed memory 0.008789 MB

thing seems to be a long standing issue that should not have effect on this.
 
https://developer.blender.org/T44127
https://developer.blender.org/T48027
https://stackoverflow.com/questions/44136128/using-blender-from-pydev

I'm closing this as *unreproduced* as the described Issue is not present on any tested system.

**Closed by jliljebl** 2021-01-09 16:26 UTC
