### ISSUE TITLE
Kubuntu 16.04

### ISSUE THREAD

**Issue by Goddard** [jliljebl/flowblade#262] opened 2016-09-22 00:42 UTC
$ flowblade 
## FLOWBLADE MOVIE EDITOR repository 1.6

Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.0.0
Failed to import module app.py to launch Flowblade!
ERROR: cannot import name Gtk
Installation was assumed to be at: /usr/share/flowblade/Flowblade

**Comment by dvdlvr** [comment] 2016-09-27 09:56
I can't remember the exact error I had, but there is a problem in the latest mlt-python bindings.
undefined symbol: _ZNK3Mlt7Profile8is_validEv
If you get this, then the problem is with the mlt-python bindings, not with Flowblade.
I reported it to the maintainer months ago but never got an answer - possibly the maintainer email for mlt-python bindings is not up-to-date.

The solution to the problem I described is to downgrade python-mlt (For instance, using Synaptic, select python-mlt, go to Package -> Force version and select version 6.0.0-2 (xenial) and it should work again).

**Comment by jliljebl** [comment] 2016-10-04 08:15
I just installed Flowblade **1.8** on Kubuntu in Virtualbox fresh installation and everything worked prefectly.

Please make sure to install 1.8 and not 1.6 as 1.6 did miss some dependencies that probably caused this.

I'm leaving this open for info for now.

**Comment by jliljebl** [comment] 2017-02-01 16:03
This is essentially a duplicate of #264 or invalid.

**Closed by jliljebl** 2017-02-01 16:03 UTC
Labels: duplicate
