### ISSUE TITLE
Clip length inconsistencies

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#404] opened 2017-06-04 15:57 UTC
If a clip was put into the timeline before switching to proxy editing it produces bizarre consequences, first of which is abnormal shortening of its length in the timeline: https://youtu.be/GKTGqhnS_5M

**Comment by jliljebl** [comment] 2017-06-06 11:17
This does not usually reproduce, this is the first test case of proxy editing work flow, but I will look to reproduce this. I may have caused a regression after the last larger proxy editing tests I have done.

**Comment by jliljebl** [comment] 2017-06-06 11:20
Ok, first quick test does not reproduce. Does this happen with all media and all workflows?

**Comment by jliljebl** [comment] 2017-06-06 11:36
Yeah, can't get my system to do what happens in your video, we will need to keep looking for ways to get reproduction.

**Comment by Efenstor** [comment] 2017-06-06 15:45
I tested more files and it seems only some of them produce this problem. Try this file, for example: https://yadi.sk/i/P1nwu7A93Jt4Ye

**Comment by jliljebl** [comment] 2017-06-06 18:06
I downloaded your clip and will test later, this may be hard to reproduce.

**Comment by Efenstor** [comment] 2017-06-10 11:41
Solved it. It's about the number of threads (I see that setting somehow causes a lot of troubles). Steps to reproduce:

1. Set "Render Threads" in the preferences to more than 1. The more threads you use the shorter is the proxy file. The difference is length equals the length of the non-clickable tail at the end of the clip.
2. Load a clip which has no proxy file created before.
3. Create the proxy but don't switch to the proxy media.
4. Add the clip to the timeline.
5. Switch to the proxy media.
6. The good portion at the end of the clip becomes unavailable.

The "Render Threads" value of 1 also produces the non-clickable tail but it's very short. May be the problem has something to do with the quirks of the H264 format. May be the length of the soundtrack sometimes is a bit longer than the video track? Then it's obviously better to cut off a bit of audio, than to lose precious frames and get into problems with time synchronization.

Here is a test file I made especially to test frame precision and synchronization:
https://yadi.sk/i/zYqsnZqS3JzZQi

**Comment by jliljebl** [comment] 2017-06-10 12:06
Thank you for working on this. I will do tests to confirm your findings and then apply needed fixes in the coming days.

The "Render Threads" setting is indeed becoming a problem. The mere existence of it encourages users to set the value higher then "1" which has now proven to cause problems.

However, if it in some cases gives e.g. 2x render speed, then having the option available is valuable to users.

I will consider either removing it or giving users warning info when changing the value, depending on what kind of actual performance boosts I can find in tests before the next release.

**Comment by jliljebl** [comment] 2017-06-10 12:10
@Efenstor Are you using Github repository version (master development branch) or the 1.12 release?

I ask because after looking at the code this should not be possible in repository version at all. When doing proxy editing, we always set:

        consumer.set("real_time", -1)

meaning no drop frames and one thread.

**Comment by Efenstor** [comment] 2017-06-10 13:33
Oh. I'm still using the 1.12 release. I'll test the master branch tonight and report the results.

**Comment by jliljebl** [comment] 2017-06-10 14:57
I did a quick test with your files  S2230089.MP4, S2360005.MP4 and was unable to reproduce.

**Comment by Efenstor** [comment] 2017-06-10 17:57
Confirmed. The problem is _mostly_ resolved in the git master - there's still a small area at the end remains, which is non-clickable. That is pretty awkward when I try to use the Trim tool - I click the end of the clip but can't move it.

The reason is in duration discrepancy between the original and proxy files. For example, for S2360005.MP4 mediainfo reports video track duration=8 s 509 ms and frame count=204, and for the proxy it is 8 s 426 ms and 202 frames.

If somehow there's no neat solution for this (i.e. without losing any frames) then at least it can be made like this:

1. Add an option to the preferences for either: a) Auto-trim each clip according to the proxy duration; b) Keep the original duration and display the last existing frame for all the non-existent frames.

2. After creating a proxy file save the original clip duration in an additional "sidecar" text file in the proxy directory;

3. Then check for the discrepancy of durations and proceed according to the option in the preferences.

**Comment by Efenstor** [comment] 2017-08-07 11:43
This is probably unrelated but still almost the same problem: there's always a redundant frame at the end of every clip, at least when using proxies. Here is the screencast: https://youtu.be/bVN-cpkKGKU

**Comment by jliljebl** [comment] 2021-11-15 16:27
I'm pretty sure that this is at least now fixed with switching to tractor producers for proxy rendering.

**Closed by jliljebl** 2021-11-15 16:27 UTC
Labels: bug
