### ISSUE TITLE
Old flowblade project cannot be opened

### ISSUE THREAD

**Issue by gubi80** [jliljebl/flowblade#223] opened 2016-03-19 19:42 UTC
Hi,

due to a system crash I reinstalled flowblade. Issue: if I try to open an existing flowblade-project 
the process starts, the window reads "unpickling"... Currently the system tries for more then half an hour to open a project file of a 5 minutes video clip.

No error message, nothing. System is Linux Mint 17.3 Cinnamon. No extras.

Any help's appreciated.

Thx Gunnar

**Comment by jliljebl** [comment] 2016-03-24 09:06
Please provide more information:

1. Which version of Flowblade you are using?
2. What is the terminal print out when this happens?

**Comment by gubi80** [comment] 2016-03-24 11:41
Hi,

version is Flowblade 1.6. Terminal output I can provide if you give me a 
hint what you want to have: syslog ? Logfile of flowblade (where do I 
find it?) ?

Thanks for your help ;- )

Am 24.03.2016 10:06 schrieb jliljebl:

**Comment by jliljebl** [comment] 2016-03-24 23:15
1) Open program called "Terminal"
2) Write "flowblade" and hit return 
3) Try to open the problematic file 
4) Once this fails copy text from terminal (usually with Shitf + CTRL + C) and paste that text here

One other question, which version of Flowblade you used previously?

Also could you attach the problematic .flb file here, since problem is in the unpickling phase, the media you have used in the project is not needed here.

**Comment by gubi80** [comment] 2016-03-25 11:33
Hi,

thanks for the clarification.

code: flowblade > /home/gunnar/flowblade_1.6.log.txt 2>&1

returned the logfile attached. Please find also the project file 
attached. The previous version was 1.4 I guess (90% sure).

best regards,
Gunnar

N.B. I suspected it to be aproblem with the file name (more precisely 
the german character "ö"). So I renamed it once for testing but it 
didn't help.


Am 25.03.2016 um 00:15 schrieb jliljebl:
> 1) Open program called "Terminal"
> 2) Write "flowblade" and hit return
> 3) Try to open the problematic file
> 4) Once this fails copy text from terminal (usually with Shitf + CTRL +
> C) and paste that text here
>
> One other question, which version of Flowblade you used previously?
>
> Also could you attach the problematic .flb file here, since problem is
> in the unpickling phase, the media you have used in the project is not
> needed here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jliljebl/flowblade/issues/223#issuecomment-201068945>
>

FLOWBLADE MOVIE EDITOR repository 1.6
-------------------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 0.9.0
OS: Ubuntu 14.04.4 LTS
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
GTK+ version: 3.10.8
User dir: /home/gunnar/.flowblade/
Locale: de_DE
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Small height: False
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - asv1
  - asv2
  - bmp
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - qtrle
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v410
  - wmv1
  - wmv2
  - xbm
  - xwd
  - zlib
  - zmbv
  - libopenjpeg
  - libschroedinger
  - libtheora
  - libvpx
  - libx264
  - libxvid
...
---
audio_codecs:
  - comfortnoise
  - aac
  - ac3
  - ac3_fixed
  - alac
  - eac3
  - flac
  - mp2
  - nellymoser
  - real_144
  - vorbis
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s16be
  - pcm_s16le
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s32be
  - pcm_s32le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopus
  - libspeex
  - libvorbis
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - asf
  - ass
  - asf_stream
  - au
  - avi
  - avm2
  - cavsvideo
  - crc
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - ffm
  - ffmetadata
  - filmstrip
  - flac
  - flv
  - framecrc
  - framemd5
  - g722
  - gif
  - gxf
  - h261
  - h263
  - h264
  - hls
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ismv
  - ivf
  - latm
  - m4v
  - md5
  - matroska
  - matroska
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - null
  - nut
  - ogg
  - oma
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtsp
  - sap
  - segment
  - smjpeg
  - smoothstreaming
  - sox
  - spdif
  - srt
  - swf
  - 3g2
  - 3gp
  - truehd
  - rcv
  - voc
  - wav
  - webm
  - yuv4mpegpipe
  - alsa
  - oss
...
MLT detection succeeded, 112 formats, 59 video codecs and 49 audio codecs found.
282 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service frei0r.alphagrad not found.
MLT service frei0r.alphaspot not found.
MLT service frei0r.alpha0ps not found.
MLT service frei0r.select0r not found.
MLT service frei0r.spillsupress not found.
MLT service lumakey not found.
MLT service frei0r.vignette not found.
MLT service frei0r.emboss not found.
MLT service frei0r.dither not found.
MLT service frei0r.colorhalftone not found.
MLT service frei0r.softglow not found.
MLT service frei0r.IIRblur not found.
MLT service frei0r.rgbnoise not found.
MLT service lumaliftgaingamma not found.
MLT service lift_gamma_gain not found.
Brightness dropped, MLT version too low for this filter.
MLT service rgblut not found.
MLT service rgblut not found.
MLT service frei0r.coloradj_RGB not found.
MLT service frei0r.coloradj_RGB not found.
MLT service frei0r.colgate not found.
MLT service frei0r.posterize not found.
MLT service frei0r.colortap not found.
MLT service frei0rException in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 100, in run
    project = persistance.load_project(self.filename)
  File "/usr/share/flowblade/Flowblade/persistance.py", line 324, in load_project
    project.name = project.name.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

**Comment by jliljebl** [comment] 2016-03-25 22:21
The project file was not attached, probably because it seems that only some file types are supported: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

Could you pack in .gz or .zip file and re-attach in a new comment?


    PNG (.png)
    GIF (.gif)

    JPEG (.jpg)

    Microsoft Word (.docx), Powerpoint (.pptx), and Excel (.xlsx) documents
    Text files (.txt)

    PDFs (.pdf)

    ZIP (.zip, .gz)

**Comment by gubi80** [comment] 2016-03-28 15:43
Sure...



Am 25.03.2016 um 23:21 schrieb jliljebl:

**Comment by jliljebl** [comment] 2016-03-28 17:07
You can't answer with e-mail and add attachment to the _email_. It will not become available to me either via e-nail or in the Issue page.

You must navigate to Github issue page using a web browser, log in, and then do as they instruct: "To attach a file to an issue or pull request conversation, drag and drop it into the comment box." I repeat,  e-mailed attachments will be lost.

**Comment by gubi80** [comment] 2016-03-28 17:12
sorry, wasn't clear to me. I'll do...

Am 28.03.2016 um 19:07 schrieb jliljebl:

**Comment by gubi80** [comment] 2016-03-28 17:14
[Kösssen_Tandem_Projekt.flb.zip](https://github.com/jliljebl/flowblade/files/192164/Kosssen_Tandem_Projekt.flb.zip)

**Comment by jliljebl** [comment] 2016-03-28 17:15
Ok, confirmed, will fix.

**Comment by gubi80** [comment] 2016-03-28 17:15
If you need more, just let me know. Sorry for the inconvenience.

**Comment by jliljebl** [comment] 2016-03-28 17:17
Thanks, no need for further files, this demonstrates the problem perfectly.

**Comment by gubi80** [comment] 2016-04-11 20:55
Hi,

I just wondered if you could provide a 1.4 package meanwhile as I really need to work on that video. Problem is, I cannot find the older version somewhere...

Cheers,
Gunnar

**Comment by jliljebl** [comment] 2016-04-11 21:26
This link should work for 1.4 .deb, which should not have this bug:

https://www.dropbox.com/s/xe94cjwmf195de2/flowblade-1.4.0-1_all.deb?dl=0

**Comment by jliljebl** [comment] 2016-05-10 16:55
Fixed in repository.

**Closed by jliljebl** 2016-05-10 16:55 UTC
Labels: bug

**Comment by gubi80** [comment] 2016-05-18 12:56
Hi. Thanks for the fix and sorry for that stupid question: how can I get / use the fixed version?  Best regards, Gunnar

**Comment by jliljebl** [comment] 2016-05-19 07:58
So "Installing Using Development Repository Version" here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md
