### ISSUE TITLE
creating proxy files

### ISSUE THREAD

**Issue by ghost** [jliljebl/flowblade#574] opened 2018-12-09 17:27 UTC
Please include the following information.
1) Flowblade version (Help->About): 1.16
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 16.04.5 LTS
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
(My systemlanguage is  german, so the buttons might be named different in english)
-Open Flowblade
-Check the proxymanager ->  Proxy media is highlighted, so it should be in the use orginal mode
-Adding a movie
-trying to click the proxy generate button, next to the movie remove button.
->Nothing happens, no menu, no proxy, no file change in the /.flowblade directory
Do you have any idea, what could be wrong, where I can check if something is missing.
Thanks for the help

**Comment by algofh** [comment] 2018-12-09 17:30
-for sure I selected the movie
-I also tried the right mouse click ... rendering proxy
->nothing

**Comment by smolnp** [comment] 2018-12-09 21:36
Use English texts on localized OS
![_2018-12-10_00-11-56](https://user-images.githubusercontent.com/26217756/49703214-5080da00-fc13-11e8-9483-37c4ca8b70ff.png)

**Comment by smolnp** [comment] 2018-12-09 22:08
I have everything working... https://youtu.be/DbuOnMvrwx0

**Comment by algofh** [comment] 2018-12-10 07:49
Thanks for the help and video. It show's the way I expected it.
I did all the steps shown in the video. But, when I do the right click on the media ... Render proxy file
nothing happens -> in the movie there comes the attached dialog ... in my version ...nothing

![bildschirmfoto_2018-12-10_08-39-48](https://user-images.githubusercontent.com/45738390/49717733-4503d200-fc58-11e8-845c-e2ce57a1364d.png)
![bildschirmfoto_2018-12-10_08-49-25](https://user-images.githubusercontent.com/45738390/49717814-88f6d700-fc58-11e8-93fd-f9320dbb977f.png)

**Comment by jliljebl** [comment] 2018-12-10 16:38
Ok, can you start flowblade from terminal with command 'flowblade' and do all the steps you do to create proxy files and then post the output here?

**Comment by algofh** [comment] 2018-12-10 21:04
here is the output:
[tmp.txt](https://github.com/jliljebl/flowblade/files/2664972/tmp.txt)

**Comment by jliljebl** [comment] 2018-12-11 08:23
So are you sure you are in "Using Original Media" mode when trying to render proxy files?

When you see this dialog,

![proxy_error](https://user-images.githubusercontent.com/1823444/49787033-3c7dcb00-fd2e-11e8-8ce7-72f86130aeb5.png)

do the following:

1) Select menu item Project -> Proxy Manager
2) Press "Use Original Media" button and close manager.
3) Now try to render proxy files.

You should only see the dialog if you are in "Using Proxy Media" state. You can't render proxy files in "Using Proxy Media" state.

**Comment by algofh** [comment] 2018-12-11 09:17
I tried both.
1. When I use original Media... Nothing happens (no Dialog, no rendering)
2. When I use proxy files (no dialog, no rendering.

**Comment by jliljebl** [comment] 2018-12-11 12:10
Ok, I have to look for more possible explanations. This does not reproduce here, but it would be good to know why this happening on your system.

**Comment by smolnp** [comment] 2018-12-11 14:52
«You can't render proxy files in "Using Proxy Media" state.» -  How can not? I just do that, which can be seen from the video above at 0:54 second

**Comment by algofh** [comment] 2018-12-11 17:29
How Can I help you. 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: jliljebl <notifications@github.com> Datum: 11.12.18  13:10  (GMT+01:00) An: jliljebl/flowblade <flowblade@noreply.github.com> Cc: algofh <fh5@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [jliljebl/flowblade] creating proxy files (#574) 
Ok, I have to look for more possible explanations. This does not reproduce here, but it would be good to know why this happening on your system.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jliljebl/flowblade","title":"jliljebl/flowblade","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jliljebl/flowblade"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jliljebl in #574: Ok, I have to look for more possible explanations. This does not reproduce here, but it would be good to know why this happening on your system."}],"action":{"name":"View Issue","url":"https://github.com/jliljebl/flowblade/issues/574#issuecomment-446180771"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jliljebl/flowblade/issues/574#issuecomment-446180771",
"url": "https://github.com/jliljebl/flowblade/issues/574#issuecomment-446180771",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jliljebl/flowblade] creating proxy files (#574)",
"sections": [
{
"text": "",
"activityTitle": "**jliljebl**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jliljebl",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jliljebl/flowblade\",\n\"issueId\": 574,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jliljebl/flowblade\",\n\"issueId\": 574\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jliljebl/flowblade/issues/574#issuecomment-446180771"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 422111524\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jliljebl** [comment] 2018-12-12 11:38
1) Right now the only thing I can think of is if you try to change the format in "Proxy Encoding" area in Proxy Manager and see if that makes a difference.

2) For next release coming in mid January I'll add some more print outs to see how proxy rendering can fail with out any trace in terminal.

3) if we still cannot get idea what is going on, then we are at a situation that to get this fixed we will probably need someone with affected system to debug and fix this and provide a pull request.

**Comment by jliljebl** [comment] 2019-09-26 16:56
This is be closed as *unreproduced*, we have no actionable clues to fix this and everything works on development system just fine.

**Closed by jliljebl** 2019-09-26 16:56 UTC
