### ISSUE TITLE
Spot White Balance

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#733] opened 2019-10-12 12:42 UTC
Flowblade 2.2 (MLT 6.16)

Currently the Color Balance filter can be tweaked manually (by eye), however it would be super convenient if Flowblade's Color Balance filter had a color picker tool, which would allow users to essentially do a spot white balance, by selecting a square area in the video frame in preview area of a greycard that was included in the footage at the start of the recording.

**Comment by jliljebl** [comment] 2019-10-13 12:50
This is duplicate of https://github.com/jliljebl/flowblade/issues/596  When we do this, we do it in way that every color picker gets it. There are some complications, see comments.

**Closed by jliljebl** 2019-10-13 12:50 UTC
