### ISSUE TITLE
"Clip Filters Stack" confused filter menu buttons

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#641] opened 2019-03-13 21:01 UTC
Using the "Clip Filters Stack" context menu, select "Move Up". Assuming the filter moves up (1 screenshot), but in fact the filter has been moved Down (2 screenshot).

1 screenshot
![Снимок экрана от 2019-03-13 23-43-31](https://user-images.githubusercontent.com/26217756/54314063-b783a580-45eb-11e9-977a-08ecea3b560a.png)

2 screenshot
![Снимок экрана от 2019-03-13 23-48-05](https://user-images.githubusercontent.com/26217756/54314066-b9e5ff80-45eb-11e9-9567-b2ce1c51e426.png)

**Comment by jliljebl** [comment] 2019-03-14 08:58
There indeed seems to be some problems, I have created a regression a some point.

**Comment by jliljebl** [comment] 2019-04-29 16:37
This is fixed now, will work in 2.2. No idea how this has reached production, very silly bug.

**Closed by jliljebl** 2019-04-29 16:37 UTC
Labels: bug
