### ISSUE TITLE
White frames + static added to end of file when rendering

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#640] opened 2019-03-13 06:00 UTC
Flowblade Version 2.0.0
GTK Version 3.24.5
MLT Version 6.13.0
Fedora 29

Hi there. Occasionally when I render a video the output has about 100 plain white frames at the end with a horrible screeching static noise in the audio track. Last time it happened I was rendering a 1080p25 .mp4 file at 1000kb/s. Audio codec was AAC 44100kHz.

I haven't worked out how to replicate the issue yet but it's happened more than once so I thought I should open this ticket.

**Comment by jliljebl** [comment] 2019-03-14 09:04
Ok, so maybe we can add some info:

1) Does this happen?
  a) Sometimes on some projects, never on some other projects.
  b) Sometimes on all projects.

2) Are we getting exactly 100 frames always or are we getting 4 x fps which would be 4 x 25 frames here?

It may be that you don't have the exact answers for these yet, but if you get this info, post here.

**Comment by thennicke** [comment] 2019-03-27 06:32
Hi there again, I've been trying to collect more information on this bug.

Attached is a screenshot of it happening in the editor itself. Note the position of the playhead -- everything between the end of the video and where the playhead itself is, is just white frames and static.

I counted how many white frames there are and for this video there are 90 (at 30fps that's exactly 3 seconds). I'll add more info if I can continue to reproduce this bug.

![Screenshot from 2019-03-21 22-23-02](https://user-images.githubusercontent.com/25953969/55055085-11896e00-50b6-11e9-81d3-516370870f6e.png)

**Comment by jliljebl** [comment] 2019-03-27 14:07
Ok, thanks, so it seems to be exact seconds, thank gives some direction, but unfortunately not quite sue where to look yet,

**Comment by thennicke** [comment] 2019-03-29 13:51
Okay I think I've figured out how to reproduce the bug.

It seems to occur (reliably) when I trim the video by dragging the end of the clip on the timeline, as opposed to using "x" to cut the clip and then deleting the end section.

For example, I have a 17-second clip which I cut at 10 seconds with "x" (and deleted the end section). All was fine. I then trimmed the left-over clip to 7 seconds by dragging the end of the clip from 10s to 7s, and this left 3 seconds of white space (up until 10 seconds).

I hope that helps!

**Comment by jliljebl** [comment] 2019-03-29 21:16
Ok, I was able to reproduce something very similar:
  * bug only appears if trim still active when rendering is started (the trim overlay is displayed on timeline)
  * we do not get static, we get the clip rendered until end, its too long compared to timeline, but no static

I'll fix this my bug, first, maybe it will fix your similar but maybe not completely same bug too.

**Comment by thennicke** [comment] 2019-03-30 02:15
Well considering the weird static was ONLY on the section with the white bit, I suspect that fixing this bug will also fix whatever was happening there.

Thanks for all the great work!

**Comment by thennicke** [comment] 2019-03-30 09:44
By the way, do you think #571 might be the same bug?

**Comment by jliljebl** [comment] 2019-03-30 21:17
Quite possible, has similar characteristics; white noise, trimming is mentioned. Once we have a fix in I will certainly ask for a test from the reporter.

**Comment by jliljebl** [comment] 2019-03-31 18:49
@thennicke I pushed the fix for my discovered bug, can you test if the repository version fixes your issue as well?

**Comment by thennicke** [comment] 2019-04-02 05:07
Doesn't seem to have fixed it. Cursor can still go past the end of the trim as per screenshot attached (sorry it's a multi-monitor image; ignore the bottom half). I rendered this video and got the exact same output as before the fix -- white screen and horrible static.

![Screenshot from 2019-04-02 16-02-49](https://user-images.githubusercontent.com/25953969/55377566-3d4a9f00-5561-11e9-95f5-f73542571148.png)

**Comment by jliljebl** [comment] 2019-04-02 06:53
Ok, we currently have no info on terminal output yet.

Could start the application with command *flowblade* from terminal, go through all the steps to create the problem and post the terminal output here?

**Comment by thennicke** [comment] 2019-04-02 09:09
Sure, my terminal output is in the file attached

[terminal_output_flowblade.txt](https://github.com/jliljebl/flowblade/files/3033121/terminal_output_flowblade.txt)

**Comment by jliljebl** [comment] 2019-04-03 07:20
Nothing here to help us.

One more thing I can think of, does changing the **Encoding Format** from dropdown menu make any difference in behavior?

**Comment by thennicke** [comment] 2019-04-03 14:15
Here, see if this screencast gives more context on how easily reproduced the bug is and when it occurs. I'm pretty sure it's not an encoding issue, so I haven't even bothered fiddling with those settings.

https://www.youtube.com/watch?v=wNpaGnYyx3k

**Comment by jliljebl** [comment] 2019-04-03 14:48
Ok, I was able to reproduce the "play goes beyond the clip end" thing, I think we have something here I can work with.

Somehow my patterns of using he application have not  produced this.

**Comment by jliljebl** [comment] 2019-04-03 14:51
I clearly mostly  use the cut/delete pattern so I do not see this easily. This can now be fixed as soon as I figure out the exact problem.

**Comment by jliljebl** [comment] 2019-04-03 16:33
This involves one of the uglier hack in the app, does this

**Comment by thennicke** [comment] 2019-04-03 23:30
That commit fixes the issue, thanks. I rendered the file just to be sure, and it was fixed there too.

**Comment by jliljebl** [comment] 2019-05-06 15:31
Closing as fixed, will reopen later if need be, but looks good now.

**Closed by jliljebl** 2019-05-06 15:31 UTC
Labels: bug
