### ISSUE TITLE
Transforms filters not working

### ISSUE THREAD

**Issue by dpack4** [jliljebl/flowblade#943] opened 2020-12-15 17:38 UTC
Attached information in text file. (Github was chopping the first part off for some reason when posting here.)

[Error Report.txt](https://github.com/jliljebl/flowblade/files/5697587/Error.Report.txt)

**Comment by jliljebl** [comment] 2020-12-16 08:12
> 3) Adjusting X and Y moves video as expected as well as Height but adjusting Width does nothing. Manually adjusting the rectangle to affect width verses entering numerical value does not adjust video either but the rectangle does reflect width changing when adjusting the numerical value


So the feature does not support changing aspect ratio of the image which leads to these behaviours. Basically the feature is "Position Scale" not "Position Scale Aspect". I will look for a way to make the GUI more consitant with this more limited capability, now user expection yo be able to change image aspect ratio will feel that    



> 3) Adjusting "X Scale" and "Y Scale" does nothing to affect video size but all other sliders work and properly adjust video.

Confirmed, I don't know what has happened along the way here.


> 3) Adjusting "X Scale" and "Y Scale" does nothing to affect video size but all other sliders work and properly adjust video. 

Confirmed.

Transform filters are currently broken, some how underlaying bahavior has changed and I have missed how and when.

**Comment by jliljebl** [comment] 2020-12-16 08:14
I had a special 'AffineScaleProperty' editable property working on these which had some quite interesting code in it. MLT must have changed some behaviour because now these are no longer working.

**Comment by jliljebl** [comment] 2020-12-16 08:28
Ok, in affine filter  'transition.geometry' has been deprecated and 'transition.rect' now does scaling (but not aspect ratio change) and 'transition.scale_x' and 'transition.scale_y' are completely ignored.

What ever I was doing with AffineScaleProperty is now irrelevant.

**Comment by jliljebl** [comment] 2020-12-16 08:35
On Shotcut it uses the same 'affine' filter but only lets setting size, not x and y scale independently.

I will need to redo the GUI here and deprecate current "Rotae" and "Shear" they will not be working

**Comment by jliljebl** [comment] 2020-12-16 08:36
On your original use case of changing aspect ratio you will need use the Affine blend work around ifn the future too.

**Comment by dpack4** [comment] 2020-12-16 12:59
Thanks for looking! I'm glad I was able to help identify a problem. I will continue to use Affine Blend for the current and future projects needing the aspect ratio adjusted.

**Comment by jliljebl** [comment] 2020-12-17 07:37
Ok, damn, I broke this my self. The X and Y scale are now again working in "Rotate" and "Shear" filters. That fixes the bug. You can now adjust aspect ratio with those filters, but not with "Position Scale".

I will look what to do "Position Scale" filter so that UX better corresponds with what actually can be done with the filter.

**Comment by jliljebl** [comment] 2020-12-17 07:47
I just needed to change one property value, now it is possible to aspect ratio with "Position Scale" too. All is fixed, thanks for the report, closing.

**Closed by jliljebl** 2020-12-17 07:47 UTC
Labels: fixed
