### ISSUE TITLE
Dark Theme: Tone Down Bright Blues

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#708] opened 2019-09-29 13:16 UTC
Currently Flowblade 2.2's dark theme (which in general I like quite a bit), has some really bright blues, which seem a bit out of place.

Changing 195093 to 2a3c52 (same hue, brightness and saturation similar to a purple used elsewhere) in the CSS makes for a nicer (calmer) experience in my opinion.

But that still leaves:
1. Bright blues in the menus, which should probably be toned down as well
2. Bright blues in some UI elements like for example the checkbox, which might be better in greyscale???

**Comment by jliljebl** [comment] 2019-09-29 14:06
For my part I won't be working on the theme in for at least 3-4 releases. It is actually quite an involved and time consuming process to get every element in the theme working together. So I'll close this as *wontfix*.

However, if you provide a pull request that presents a nice looking theme I will be happy to make it available with the application, even as the default theme if I judge it to be better then the one we have now.

**Closed by jliljebl** 2019-09-29 14:06 UTC
Labels: wontfix

**Comment by pmjdebruijn** [comment] 2019-09-29 14:31
Fair enough...

The images in res/css/assets, have they been generated from an SVG source? Or if not, how did they come to be?

**Comment by jliljebl** [comment] 2019-09-29 15:01
The Flowblade theme is just a modified Arc Dark and the assets are the original ones. The SVGs might be available where they host the theme development, don't know.

**Comment by pmjdebruijn** [comment] 2019-09-29 16:22
Ah indeed... for reference, specifically:
https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/assets.svg
https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/render-assets.sh
https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/assets.txt

**Comment by pmjdebruijn** [comment] 2019-09-29 16:41
BTW, the color for the menuitem's seem to be inherited from the system theme, and I'm having trouble figuring out how to override that. The arc-theme is... erhm... complicated...

**Comment by jliljebl** [comment] 2019-09-29 17:14
I had the same problem with buttons and asked about it:

https://discourse.gnome.org/t/custom-css-button-colors-are-ignored-when-system-theme-is-adwaita/1442

So the problem is that system theme has some CSS property and Flowblade theme *does not have that property* so the system theme value gets displayed. I tried to find the menu item thing in Adwaita and compare with Flowblade theme, but like you said, it is annoyingly difficult.

I am very happy to hear if you find the CSS property at fault here.

**Comment by pmjdebruijn** [comment] 2019-09-29 17:24
Oh, there's all sorts of juju happening with regard to the selected_bg_color in gui.py

**Comment by pmjdebruijn** [comment] 2019-09-29 18:11
Aaaaah, xubuntu's Greybird sets a background-image (as in a linear gradient) that overrules background-color, so background-image needs to be set to none;

**Comment by pmjdebruijn** [comment] 2019-09-29 18:16
#709 is ready for a initial review
