### ISSUE TITLE
color adjustment & saturation filters inop

### ISSUE THREAD

**Issue by GHMToday** [jliljebl/flowblade#1156] opened 2024-04-18 01:25 UTC
Flowblade 2.14.0.1
MLT 7.23.0
Lubuntu 22.04.4 LTS / LXQT / X11

I can no longer add color adjustment or saturation filters to a clip. This first occurred after recent updates, but I'm not sure if it was after the update to 2.14.0.1, or after one of the many ubuntu debian / flatpack OS updates.

Other filters I commonly use -- for example, contrast, brightness, curves -- no problems. When I right click to add either color adjustment or saturation, the clip shows the filter added icon, but the filter does not appear in the "edit" area above the clips, so it can't be used / configured.

Strange note: grayscale works, but does not appear in the edit area. Since it doesn't have editable parameters it doesn't matter, but maybe a clue?

Thank you for this tool, it is a great video editor.

**Comment by jliljebl** [comment] 2024-04-23 15:34
I tested this, *Color Adjustment* filter is indeed broken but *Saturation* still works here. I'll do further testing and try to do a hotfix release for this latest next week. Thanks for the report, this is some regression that has gone unnoticed by me.

**Comment by jliljebl** [comment] 2024-04-24 08:29
I fixed the *Color Adjustment* issue which was a quite straight forward regression problem caused by some changes I made to editor initialization for 2.14. *Saturation* worked everywhere and was not affected by changes in 2.14, so I think that problems with that filter were caused by  *Color Adjustment* editor initialization causing a crash and stopping all other editors for filter being created.

I made a hotfix release 2.14.0.2 with fix for this Issue, and it has been published and pushed to Flathub. Closing as fixed. If problems with *Saturation* continue with the latest version comment here or file a new issue.

**Closed by jliljebl** 2024-04-24 08:29 UTC
Labels: bug

**Comment by GHMToday** [comment] 2024-04-25 16:27
you are an amazing person, thank you. i'm wrapped up in something now, but will download and test tonight. again, thank you.

Richard Marin

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by jliljebl** [comment] 2024-04-26 06:23
Seems that Flathub is not updating to 2.14.0.2 yet even if pull request was successfully tested and merged 2 days ago. This seems to happen every now and then, and unfortunately there is not much to do but wait for the update to happen.

**Comment by GHMToday** [comment] 2024-04-26 16:22
you are such a "class act" (americanism). thank you, i'm sure it's frustrating for you as an amazingly responsive developer, but i'm perfectly happy to wait, just great to know it's in the pipeline.

**Comment by GHMToday** [comment] 2024-05-08 15:01
Mr Jliljebl -- As you're likely aware, Flathub finally posted the 2.14.0.2 hotfix. Thank you very much, it works perfectly.

The fools at Flathub show the hotfix as 2.14.01 but it is, in fact, 2.14.02. I've attached screen shots documenting this additional incompetence at Flathub.

Again, thank you for your wonderful tool.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by jliljebl** [comment] 2024-05-08 17:35
Great that update came through. I future I'll have to look to maybe use third semantic numbers for updates, like 2.14.1, 2.14.2 etc. maybe Flathub will somehow automatically push those updates faster. The main release  updates come through quickly enough.
