### ISSUE TITLE
Changing profile for rendering changes image scaling / positioning for compositors.

### ISSUE THREAD

**Issue by denjello** [jliljebl/flowblade#120] opened 2015-06-17 09:40 UTC
I noticed that if I create a project in let's say HD 720p 25fps, I cannot change this profile anywhere. During rendering I can change the target, however compositors / filters receive broken image scaling / positioning. (Such as compositor:picture in picture / Filter:Alpha:Crop).

Is there any way at the moment to change the Project Profile?

**Comment by jliljebl** [comment] 2015-06-17 16:24
No, there is no way to change Project Profile, but changing that would not help here.

The problem with compositors is that the data is saved as absolute pixel values, not as 0-1 normalized floats, so changing the render profile does not change the positioning or scaling correctly (x pos of 50 pix produces different positions on image depending on the .

In principal this can be fixed, but this will be very difficult and would require fixing up to 50 different code sites, and attempting will this is almost guaranteed to cause regressions.

The current proposed solution is to render using original screen dimensions.

I'm not marking this wontfix because I would like to fix it, but not commitment is made to fix this. Maybe same save/load hack combined with Project Profile change functionality might work.

**Comment by denjello** [comment] 2015-06-22 09:43
Then maybe a way to deal with this issue is to notify the user when creating their project that the project profile is permanent and not changeable after they begin their work.

**Comment by jliljebl** [comment] 2015-06-22 20:02
Good idea, I'll add some text making that point into project creation Dialog.

**Comment by jliljebl** [comment] 2016-02-04 23:37
Closing this as known issue as I'm not planning to any work on this. I'm not sure that a etxt at project creation dialog is actually appropriate here.

**Closed by jliljebl** 2016-02-04 23:37 UTC
Labels: bug
