### ISSUE TITLE
 "Add Fade In"and"Add Fade Out" buttons to Compositor editor

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#204] opened 2016-02-13 23:01 UTC
**Steps to reproduce:**
1. Insert a video track on V1.
2. Insert a full-frame PNG with transparency (watermark) on V2.
3. Add a Dissolve compositor V2 > V1.
4. Render fade outs on both V1 and V2 (Important! It works OK if just V1 is faded).
5. Observe V1 blacking out instantly at the first frame of the rendered fade.

As a workaround I use Brightness filter to do the fade out.

**Comment by jliljebl** [comment] 2016-02-27 12:12
Confirmed.

What happens here is:
1) Rendered Fade Outs are actually "fade to color" not "fade to zero alpha". You can see how it fails by just rendering a Fade Out on a single PNG with alpha using some other color then black 
2) For obvious disk space reasons rendered fades are stored as video clips, not as frame sequences, and as such _cannot contain alpha information._ So at the first frame of rendered frame at track V2 all transparency disappears.

Workaround: Use **Opacity** keyframe is **Dissolve** compositor to fade the graphic on track 2.

This cannot be fixed without introducing a "Fade To Transparency" version of the rendered Fade In/Outs. I'm not sure it is doable on MLT at all, and the required effort may not justified because workaround exists, so this may remain unfixed for the time being.

But it would be a useful feature, so I'm leaving this open and will investigate for the next release.

**Comment by apienk** [comment] 2016-02-27 13:28
Thank you for looking into this issue.

As a matter of fact, some video clips **can** contain alpha information. I'm using it daily with flowblade. Just use _png_ format in _mov_ container.

On the other hand, it might be equally reasonable to implement fading using the Opacity keyframes you mentioned instead of rendered video tracks. You could just add an option to set the frames automatically.

**Comment by jliljebl** [comment] 2016-02-27 18:52
An "Add" button with spin button for length would easily fit in the left panel of composite editor, it is actually quite empty currently. I'll try this for 1.8.

**Comment by jliljebl** [comment] 2017-06-07 13:18
These Fade -buttons and some other additional features improving this use case will be in 1.14.

**Closed by jliljebl** 2017-06-07 13:18 UTC
Labels: feature added
