### ISSUE TITLE
Can not find a way to LOOP a video clip in monitor preview - no GUI hint about such basic feature

### ISSUE THREAD

**Issue by softwarelimits** [jliljebl/flowblade#623] opened 2019-02-14 21:03 UTC
I can not find a way to loop a video clip in the video preview window, this is totally annoying and frustrates me. I investigated all menus, all preferences, tried to quickly scan the manual - btw the manual needs a search function urgently! - no way to LOOP! WTF? 

Maybe I have a strange way of doing things, maybe I do not understand how to use Flowblade, yes, I am going to study the manual deeply on some rainy day in the future, but this is not some advanced feature, I just want to LOOP the playback - it should be immediately visible by _looking at the GUI_ how to perform such basic tasks as switching the playback to LOOP mode - this is something that needs to be accessible very easily. 

I understand that I have to study the manual for advanced editing tasks, but this is a GUI and usabiity issue - every media software I know allows the user to understand how to to change the play mode just by looking at the play controls or some icons nearby. This is missing in Flowblade.

**Comment by jliljebl** [comment] 2019-02-14 23:06
This feature is indeed missing and we can add it as a preference item. 

One thing that may not be in the immediate future is autoplay on adding clip to monitor, that had some crash caused by libraries were callin and was not solvable from Flowblade code.

Search function for docs will require code contribution.

**Comment by jliljebl** [comment] 2019-03-11 17:18
Fix in repo will be in 2.2..

There is a white flash between loops but that can't be removed with current approach, we are not having event per every frame only once every 0.2 secs, so we are not updating fast enough to avoid the flash. No fix for this is planned for now.

**Closed by jliljebl** 2019-03-11 17:18 UTC
Labels: in feature queue
