### ISSUE TITLE
Split Audio error

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#770] opened 2019-11-15 20:59 UTC
Please include the following information.
1) Flowblade version (Help->About): Fresh install from current master source (15-Nov)
2) MLT version (Help->Runtime Environment): 6.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
4) On the command line I see the following error when I select the 'Split Audio' option in the Clip menu. This is both on my work copy (which is a bit older) and in a fresh install from the source master I just did, to make sure it wasn't of my doing.
It doesn't seem to impact anything, but I can't be sure as I don't usually use 'Split Audio'.
I have tried this on multiple files from multiple sources and it always happens, whether there is 1 audio track or multiple.

Traceback (most recent call last):
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/clipmenuaction.py", line 98, in _clip_menu_item_activated
    handler(data)
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/syncsplitevent.py", line 64, in split_audio
    _do_split_audio_edit(popup_data)
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/syncsplitevent.py", line 96, in _do_split_audio_edit
    action.do_edit()
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/edit.py", line 329, in do_edit
    self.redo()
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/edit.py", line 394, in redo
    self.redo_func(self)
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/edit.py", line 2125, in _audio_splice_redo
    filter = _create_mute_volume_filter(current_sequence())
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/edit.py", line 182, in _create_mute_volume_filter
    return mltfilters.create_mute_volume_filter(seq)
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/mltfilters.py", line 542, in create_mute_volume_filter
    mute_filter = seq.create_filter(get_volume_filters_info())
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/sequence.py", line 557, in create_filter
    filter_object = mltfilters.FilterObject(filter_info)
  File "/media/svdbeek/Storage/github/flowblade-master-20191115/flowblade-master/flowblade-trunk/Flowblade/mltfilters.py", line 208, in __init__
    self.properties = copy.deepcopy(filter_info.properties)
AttributeError: 'NoneType' object has no attribute 'properties'

**Comment by jliljebl** [comment] 2019-11-16 02:29
This does not reproduce. 

Because the code path creates a filter and you have a development MLT (6.17, maybe self compiled)  it is possible that the MLT environment isn't fully functional in your system. Leaving this open for more info.

**Comment by jliljebl** [comment] 2020-05-05 07:04
Closing as this probably is not relevant right this moment, let's see if we get similar reports after 2.6

**Closed by jliljebl** 2020-05-05 07:04 UTC
Labels: unreproduced
