### ISSUE TITLE
Double click on media item when empty timeline and monitor crashes

### ISSUE THREAD

**Issue by fandali** [jliljebl/flowblade#466] opened 2017-12-08 17:57 UTC
I open this issue report to find the reason why Flowblade crash on many distros.
As it was reported here : https://github.com/jliljebl/flowblade/issues/445 the problem seems to touch 
also Ubuntu (17.04 or 17.10) (I use many machines affected by the same problem)
I use Flowblade version 1.14.
On some machines it's libmlt 6.4.1 or 6.5.0 (this comes for the kdenlive repository)
(Not every machine have kdenlive repository installed but it crash anyway)
On all those machines, it's X11 (and not Wayland).
Can we identify if the problem comes from GTK or MLT (SDL vs SDL2) ?
As you suggest it in the 445 issue, I will try to put some print in app.py to check where this problem come from and I'll be back to this issue report.

**Comment by jliljebl** [comment] 2017-12-08 18:20
I'm still assuming the SDL2 issue until otherwise proven.

6.5.0 from KDEnlive repository is guaranteed to crash Flowblade with x11 crash because MLT repository is currently in a state that breaks Flowblade and KDEnlive pulls that.

I don't know how 6.4.1 would crash Flowblade but if SDL2 somehow gets involved e.g via FFmpeg we could have similar symptoms.

If purging Flowblade, KDEnlive PPA and MLT from Ubuntu system and then installing Flowblade from .deb fixes system on Ubuntu, then we know its the SDL2 thing.

**Comment by fandali** [comment] 2017-12-08 21:38
I test on a first workstation with the following default libs/packages:
(no PPA was added to the system, Flowblade 1.14 was installed with the *.deb archive)

Ubuntu 17.10
FFmpeg 3.3.4
libmlt 6.4.1

It crash in the main loop Gtk.main()
It seems indeed that the version of FFmpeg  provided with Ubuntu 17.10 use SDL2 (FFmpeg > 3.1.2 use SDL2 instead of SDL1.1)

I think users should check that FFmpeg is <= 3.1.2 to use Flowblade at this time.
(Note that other editing program like Kdenlive are also highly unstable with those versions of FFmpeg)

I'm a long time user of FFmpeg in backend processing but unfortunately, I have no knowledge in MLT. It's difficult for me to know if the problem comes from MLT and SDL2 or from GTK3 and SDL2?
Did you try Flowblade with SDL2 support because I've seen that you make some changes related to SDL2 in flowblade-trunk?

**Comment by dvdlvr** [comment] 2017-12-08 21:40
I run Flowblade 1.14 on Ubuntu 17.04 with X11, ffmpeg 3.2.4 and MLT 
6.4.1 and it doesn't crash.
I don't know how to tell which version of SDL is being used. I have both 
installed (1.2 and 2.0)

**Comment by fandali** [comment] 2017-12-08 21:54
Oops... After checking on the website again, I think that FFmpeg 3.2 branch is still using SDL1.1.
The 3.3 (and 3.4) branch use SDL2.

**Comment by jliljebl** [comment] 2017-12-09 09:42
Ok @fandali , I'm also running Ubuntu 17.10 on my development system and I'm not seeing this, so we need some way to find out the differences on installed software on our systems

I would still assume that the issue is not hardware related unless you are running a 32-bit Ubuntu, . 

We could do a diff between our installed packages. You can list all packages in your system with command like:

    dpkg-query -l > fandali_packages

The resulting file is 300kB+ on my system so it may best to send it to me as an attachment on email to janne.liljeblad@gmail

It might be possible to post it here also if Github accepts 300kb Issue comments.

**Comment by theychx** [comment] 2017-12-09 11:36
On my Debian Sid box, Flowblade does not crash.

```
ii  ffmpeg         7:3.4-4      amd64        Tools for transcoding, streaming 
ii  flowblade      1.14.0-1     all          Non-linear multitrack video edito
ii  libgtk-3-0:amd 3.22.26-2    amd64        GTK+ graphical user interface lib
ii  libmlt6        6.4.1-6+b1   amd64        multimedia framework (runtime)
ii  libsdl1.2debia 1.2.15+dfsg2 amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0: 2.0.7+dfsg1- amd64        Simple DirectMedia Layer
```

Interestingly:

```
$ apt-cache depends ffmpeg | grep sdl
  Depends: libsdl2-2.0-0
$ apt-cache depends libmlt6 | grep sdl
  Depends: libsdl1.2debian
```

**Comment by fandali** [comment] 2017-12-09 12:08
I share 2 links (valid until tuesday):
Packages:
https://nextcloud.alltv4eu.com/s/tA78OHcyhEDyfOP
And a recordmydesktop session:
https://nextcloud.alltv4eu.com/s/SmgCT22JUs8zT4R
Kdenlive is also installed from the Ubuntu repo (but no PPA added)
As you can see in the recorded session, I try to open a *.mp4 and a *.mov (Grass Valley HQX Codec) and as soon it try to display, it crashes.

**Comment by jliljebl** [comment] 2017-12-09 12:14
Thanks, I downloaded the files, might take a few days to see if I find something.

**Comment by jliljebl** [comment] 2017-12-10 11:33
Some points after looking at the data:
  * I dont think that this is SDL issue here, it should crash on startup
  * it is not proven that this crashes inside X11 like issue #445, we need gdb backtrace
  * I installed all media apps like Audacity which I fandali had and I didn't but those did not have any affect

@fandali could you do gdb back trace https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/GDB.md and post it here.

Also could try without these drivers to see if they have an effect on this:

    ii mesa-va-drivers:amd64 17.2.4-0ubuntu1~17.10.1 amd64 Mesa VA-API video acceleration drivers
    ii mesa-vdpau-drivers:amd64 17.2.4-0ubuntu1~17.10.1 amd64 Mesa VDPAU video acceleration drivers

**Comment by jliljebl** [comment] 2017-12-10 11:38
**If anyone has Ubuntu 17.10 that crashes when opening media** could you do:

    dpkg-query -l > yourName_packages

and make output available.

Even packages list from 17.10 that works with Flowblade could help.

**Comment by fandali** [comment] 2017-12-10 20:51
Here is the gdb back trace : 
https://nextcloud.alltv4eu.com/s/2ZLOlOv4vUDqPWH
May be it's less complex that what we expect... By pure coincidence I realize that when I double clic on a media, it crashes BUT when I do a right-clic on the media and choose "Open File in Clip Monitor", it works !
After opening the first clip in this way (Open File in Clip Monitor), then you can open all others clips by double clicking on it.
And it's not related to video, because I try with an audio file and the principle is the same:
If I double click on the 1st imported media (even if it's an audio file), it crashes.
To make it works, I always have to open the FIRST MEDIA in the monitor with right click -> Open in clip monitor

**Comment by fandali** [comment] 2017-12-10 21:00
I've recorded the session (if it can help):
https://nextcloud.alltv4eu.com/s/jUAZQ3b2Czj8T4O

**Comment by jliljebl** [comment] 2017-12-10 21:18
Confirmed. This new, something changed underneath, this really has historically not been the case

**Comment by theychx** [comment] 2017-12-10 21:49
Double-clicking on a media item with an empty timeline and monitor does not make Flowblade crash on my Debian Sid box.

**Comment by jliljebl** [comment] 2017-12-10 21:55
Ok. Probably requires Ubuntu 17.10. to trigger, I would have seen this
otherwise many times.

10.12.2017 11.49 ip. "theychx" <notifications@github.com> kirjoitti:

**Comment by jliljebl** [comment] 2018-01-03 11:26
Fixed in repo, will be in 1.16. This could benefit from additional testing on affected systems, bug seems to be somehow timing related and fix might not work everywhere, even though it probably should.

**Comment by jliljebl** [comment] 2018-11-12 09:04
I did clicking around in Ubuntu 18.04 and didn't get this, but I'll reopen for more info to come in

**Comment by dvdlvr** [comment] 2018-11-12 09:11
I tried it a couple of times and sometimes it crashes and sometimes it 
doesn't.
No error messages when started from command line. Just a standard core 
dumped message:
Segmentation fault (core dumped)

**Comment by reinout** [comment] 2018-11-12 09:58
Heisenbug: I added the print statements, but now I haven't been able to get it to crash anymore. Sigh :-)

In the double-click-handling-method I simply copied all the individual lines and put a `print("...")` around the copied line. One thing that looks weird to me is that the double click seems to be handled twice:

	Loading Project, SAVEFILE_VERSION: 5
	Player initialized with profile:  HD 1080p 30 fps
	Create SDL1 consumer...
	Autosave started...
	Saving project...
	before widget.grab_focus()
	before self.clear_selection()
	before media_object.widget.override_background_color(Gtk.StateType.NORMAL, gui.get_selected_bg_color())
	before self.selected_objects.append(media_object)
	before self.widget.queue_draw()
	before GLib.idle_add(self.double_click_cb, media_object.media_file)
	before return
	before widget.grab_focus()
	before self.clear_selection()
	before media_object.widget.override_background_color(Gtk.StateType.NORMAL, gui.get_selected_bg_color())
	before self.selected_objects.append(media_object)
	before self.widget.queue_draw()
	before GLib.idle_add(self.double_click_cb, media_object.media_file)
	before return

I'll keep the print statements in place and I'll hope for a crash later today.

**Comment by dvdlvr** [comment] 2018-11-12 12:09
I couldn't reproduce it with version 1.18. Tried half a dozen times. It 
crashes after only 2 tries on 1.16. I don't know if that was just a 
fluke or if it just solved itself in 1.18.

**Comment by jliljebl** [comment] 2018-11-12 12:11
> One thing that looks weird to me is that the double click seems to be handled twice:

This could be it. i just came across this when doing double-click-to-open-sequence, GTK sends 2 events for double click and app needs to discard the first one.

I pushed a patch that does the same for guicomponents.MediaPanel and it already opened the clip faster in monitor and could likely help here as this is the diff between opening from poopup  menu and double click.

If you apply code in this patch https://github.com/jliljebl/flowblade/commit/ba626776a4235a9f45f38e017304f92affa4ccd4 does it fix things for you?

**Comment by jliljebl** [comment] 2018-11-12 12:44
I had to revert https://github.com/jliljebl/flowblade/commit/ba626776a4235a9f45f38e017304f92affa4ccd4 , it broke drag'n'drop on timeline, I'll do it some other way instead.

**Comment by jliljebl** [comment] 2018-11-12 12:59
I pushed https://github.com/jliljebl/flowblade/commit/5b4267f25ec7a529d8e3e399ec2125f2ec4b1b26 that blocks the first event at another module so  drag'n'drop on timeline is not affected.

**Closed** 2019-02-16 21:59 UTC
Labels: fixed
