### ISSUE TITLE
H.264 / .mp4 Fade for single track clip not working

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#791] opened 2019-12-25 22:52 UTC
Please include the following information.
1) Flowblade version (Help->About): 2.4
2) MLT version (Help->Runtime Environment): 6.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10
rendering "Fade Out" and "Fade In" do not work, with the parameters set by default (h.264 / .mp4).
![screen](https://user-images.githubusercontent.com/26217756/71451187-cce44d80-2781-11ea-94bc-aff08e95e291.jpg)
terminal:
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0045a1ac0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0044c5800] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0045d5940] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc004577840] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc00452f3c0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0044b7580] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0066d22c0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0069c4380] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc006981f80] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
Player initialized with profile:  HD 1080p 30 fps                              
Create SDL1 consumer...
[mp3 @ 0x7fc00000da80] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                                          
Autosave started...                                                            
Saving project...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc000c39040] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc000c3a100] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x26cb000] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                           
producer_tractor length:31                                                     
FileRenderPlayer started, start frame: 0, stop frame: 30
[aac @ 0x2650980] Too many bits 85333.333333 > 12288 per frame requested, clamping to max                                                                     
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbfb80044c0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbfb8126d40] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mp4 @ 0x2915cc0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.                                       
[mp4 @ 0x2915cc0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.                                       
[aac @ 0x2650980] Input contains (near) NaN/+-Inf                              
[consumer avformat] error with audio encode: -22 (frame 2)                     
[aac @ 0x2650980] Input contains (near) NaN/+-Inf
[consumer avformat] error with audio encode: -22 (frame 2)                     
[aac @ 0x2650980] Input contains (near) NaN/+-Inf
[consumer avformat] error with audio encode: -22 (frame 3)                     
[aac @ 0x2650980] 5 frames left in the queue on closing
FileRenderPlayer stopped, producer frame: 30                                   
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc000951040] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]                                                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc00086be40] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]

**Comment by jliljebl** [comment] 2019-12-26 19:26
Confirmed. This was certainly working, so this regression has to be either external or Python 3 related.

**Comment by jliljebl** [comment] 2020-01-19 09:04
Ok, what the hell, this has now **stopped reproducing** on my system.

Two possible explanations:
* some Ubuntu updates have been coming in so maybe there was some Issue ffmpeg libs
* I did work on rendered transitions that could have had some effect on this

@smolnp Seems that you are using Ubuntu 19.10 like me, can you test  if the issue is still happening on your system with repo head  Flowblade code and all Ubiuntu updates appllied?

**Comment by smolnp** [comment] 2020-01-20 12:40
I would be happy, but I use debian unstable, I used the sid repository to install flowblade. I tried in openmandriva cookie, there is the same error.

**Comment by axelsimon** [comment] 2020-04-09 13:57
I'm using Flowblade 2.4.0 on Fedora 30 (MLT version: 6.2.0, GTK version: 3.24.11), and rendering a fade out to black on a clip just yields 15 frames of solid white.
To be specific, this is a clip that was added to the track by first setting in and out marks. However there is no solid white anywhere in the original source clip, so it's very strange.

**Comment by domotic-29** [comment] 2020-04-09 14:39
Same (white screen) on Manjaro, Flowblade 2.4.0, MLT 6.20.0 GTK 3.24.17

**Comment by smolnp** [comment] 2020-04-09 15:08
The development version has not yet been fixed. Alternatively, maybe it’s worth changing the default encoding settings until this error is fixed?

**Comment by axelsimon** [comment] 2020-04-09 15:17
Do i understand correctly that there is a workaround by changing the encoding of the rendering of the fade out/in?

**Comment by domotic-29** [comment] 2020-04-09 15:49
Indeed it works in .ogv or .mkv
Thanks for the workaround

**Comment by smolnp** [comment] 2020-04-09 16:51
Yes, look here https://github.com/jliljebl/flowblade/issues/792. The problem appeared after the default H.264 / .mp4 was used in flowblade.

**Comment by thennicke** [comment] 2020-04-10 02:05
Thanks for explaining this smolnp, this particular bug has been really causing me problems. I'll try the other encoding options.

**Comment by oorail** [comment] 2020-04-16 05:01
Setup:
Flowblade version 2.4.0
MLT: 6.18.0
GTK: 3.24.16
OS: 16.04.6 LTS (Server with desktop packages added)

Using the latest flatpak build. 

Details:
We also ran into this problem, although the "rendering" never completes it sits there with about 90% complete and never progresses. If you hit cancel, we get the same white rendering as mentioned above. I ran strace on the flowblade process and it seems to be continuously polling in a loop. It happens with:

Fade In / Fade Out / Color Dip
Encoding: H.264 / H.264 Lossless

Attempts with MPEG-4 encoding work but the audio is messed up (sounds pixelated?). 

With H.264 Tried it at all the rates from 200 to 12000.

One interesting thing to note is that the dissolve transition between two clips works okay but it too renders all the way to 90%, takes a brief pause, then completes. 

We switched to using mkv and it worked fine.

Other things I noticed were:

1. The fade in/out doesn't hang if you use less than 30 frames (anything from 1 to 29 works, but you still just get a white rendering)

2. The fade in/out at 90 frames seems to stop around frame 30.

3. The color selected doesn't have any impact.

4. The frame rate of the project has an impact, if you set the frame rate to 24 or 30 fps it behaves as above, but with the frame rate of the project set to 60 fps, it seems to hang around above 30 frames.

![flowblade-90](https://user-images.githubusercontent.com/13627791/79416413-a2f7a680-7f7d-11ea-8dbe-a821d9ff04d3.png)
![flowblade-3](https://user-images.githubusercontent.com/13627791/79416416-a3903d00-7f7d-11ea-8e7a-5848a904bfbd.png)
![flowblade-strace](https://user-images.githubusercontent.com/13627791/79416417-a3903d00-7f7d-11ea-9119-ef8c018809be.png)
![flowblade-2](https://user-images.githubusercontent.com/13627791/79416418-a428d380-7f7d-11ea-85df-c0910d484c57.png)
![flowblade-1](https://user-images.githubusercontent.com/13627791/79416419-a428d380-7f7d-11ea-9c89-907c5d6a3b42.png)

**Comment by jliljebl** [comment] 2020-04-20 10:38
I will get back to this during this cycle and try get this fixed for next release.

**Comment by jliljebl** [comment] 2020-04-20 19:58
@smolnp @thennicke  @domotic-29 et. al. can anyone try changing args in */res/render/renderencoding.xml* so that all instances of "acodec=aac", are changed to "acodec=flac".

**Comment by jliljebl** [comment] 2020-04-21 06:59
Never mind the AAC replace, this needs to be fixed in some other way.

**Comment by dvdlvr** [comment] 2020-04-23 15:45
This is certainly linked to the aac codec in this part of the code.
The producer.frame() always seems to stop at 27, no matter what length you enter (Unless you enter less than 27).
This is why it 'hangs' if the value is above 25 (i.e. it stays in the while loop. Hitting Cancel will end).

It happens in renderconsumer.py -> FileRenderPlayer.run in the while loop, around line 420.

It is always accompanied by the following error messages:
[mp4 @ 0x7f5fb4000f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x7f5fb4000f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[aac @ 0x7f5fb4003880] Input contains (near) NaN/+-Inf
[consumer avformat] error with audio encode: -22 (frame 1)
[consumer avformat] error with audio encode: -22 (frame 2)
[consumer avformat] error with audio encode: -22 (frame 2)

It looks like this could be an mlt bug.

I did some extensive testing, changing the aac parameters like bitrate, buffer size, coder etc. Nothing makes any difference. I tested with different input files and different parts of the file.
There was always an error on frame 27.

I hope this helps.

**Comment by dvdlvr** [comment] 2020-04-25 15:05
Ok, I found something.
This is related to an old issue in ffmpeg. See https://video.stackexchange.com/questions/25246/how-to-resolve-ffmpeg-error-input-contains-near-nan-inf
Basically the aac codec needs to be set to 16bit integer samples. I couldn't find an option to do that in mlt.
However, adding the ar parameter to the line in renderencodings stops the 'hanging' error from producing. The counter goes to the end and the video is created properly.
The audio is not created at all, but at least there is some progress.

So, the line should be something like this:
... acodec=aac **ar=256k** ab=256k pix_fmt=yuv420p ...
I tried several values for ar but I couldn't get the audio back. I don't know enough about that to understand why.
In the above you can also just remove the ab=256k - the result will be the same.

**Comment by dvdlvr** [comment] 2020-04-25 16:13
If you enter an incorrect audio parameter in the renderencodings line, you will get the following error message:
consumer_avformat.c: Unable to encode audio - disabling audio output.
This means the audio is not being produced BUT the process will continue properly and the fade is actually produced correctly.
During the fade there is no audio, though.
You could add
ac=20
(Audio channel = 20 - it goes to 16)
and you will get the fade in as many frames as you want, without audio and finishing properly.
But basically, the aac part of ffmpeg is broken.
Remains the mystery why it doesn't work properly here, but when rendering a full project in the render tab it works without a problem?

**Comment by DasJott** [comment] 2020-09-19 12:22
I just try out some video editors for Linux and was disappointed from (not only) this one.
Inserting a video was no problem. Then fade in already didn't work. Simply nothing happens with that effect.
The same for proxy clips that are also simply not working.
Basic things that one would expect are not working at all. I come back to Flowblade later I guess..

**Comment by jliljebl** [comment] 2021-01-06 09:00
This is now fixed by removing the possibility to use H.264 / .mp4 Fade for single track

**Closed by jliljebl** 2021-01-06 09:00 UTC
Labels: bug
