### ISSUE TITLE
Scales of "affine" filter ignored while loading a save 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jliljebl/flowblade#78] opened 2015-04-01 10:51 UTC
```
What steps will reproduce the problem?
1. Use the filter "affine" on a sequence
2. In the options, change scale X and scale Y to 200
3. Save your project
4. Close Flowblade
5. Open Flowblade again
6. Open your project

What is the expected output? What do you see instead?
Expected output : the  save should keep the "zoom" of the affine filter
Actual output : the scale X and scale Y are "reset" to 100 in the preview 
window and in the rendered video. Nevertheless, if you try to edit the filter, 
you can see that scale X and scale Y are still set to 200, they just do 
nothing. Changing the value to 201 (for example) and 200 again allows to have 
the expected output again.

What version of the product are you using? On what operating system?
Flowblade 0.12.0
Linux Mint 15, MATE 1.6.0

Please provide any additional information below.
It seems that those two params are ignored while the save file is loaded.
```

Original issue reported on code.google.com by `tapata.t...@gmail.com` on 8 Jun 2014 at 3:33

**Comment by jliljebl** [comment] 2015-08-25 15:56
It seems that filter properties "transition.geometry" and "transition.scale_x" and "transition.scale_y" which all affect the width and height of the produced image interfere with each other in away that is not manageable from the application level. Situation is also logically a bit unclear; several parameters affect the same observed property of the displayed image. 

For these reasons the fix was to simply remove "Scale X" and "Scale Y" sliders, and leave only the "Size/Height" control available. This should cover about 95% of use cases for this filter. A separate filter for free scale manipulation or an updated version for this filter will be provided later.

**Comment by Miniellipse** [comment] 2015-08-27 09:29
For me, the size/height-Value does do nothing comparable to the scale-parameters. When size is set to 100 percent, the changing of the height-value only affects the midpoint of the tranlated media (by the x and y-values), and does no effect on the size.
The scale-values are not applied when loading fresh from the file, you can get them to work if you change the values (in my example value 20 to 19 and back to 20 for scale x and scale y works.

https://youtu.be/4oXCmDtCcUA

**Comment by jliljebl** [comment] 2015-08-27 17:20
Yeah, this needs work. I will have to read the MLT "affine" -filter code to get a better idea what is happening here.

The problem is that "affine" does not have an anchor point to define unambiguously the rotation center point and scale center point. The "transition.geometry" acts as if the anchor point was at top left and "transition.scale_x" and "transition.scale_y" act as if anchor point was at the center of source image. I'll look into this a bit further.

**Comment by jliljebl** [comment] 2015-08-27 19:04
Okay now I got the scaling working, will push something later today . You were right, the "Size/height" thing worked incorrectly. I had a code comment which said "width does not work" but now it does work...I dunno what's going on here. 

The anchor point for scaling is now destination top left, but anchor point for rotation it is destination center. This is wrong, anchor points should always determined in source cood-space and preferably in center of source.

Also the width and height scaling cannot be controlled independently, I can't make it work any other way... but scaling does work now and saving too. Before next release I'll look into making these keyframable.

**Comment by jliljebl** [comment] 2015-08-27 22:30
Key framing does not work for rotate, shear or scale and the geometry works in such a strange way  that it is not usable for animation. 

But scaling works now, closing this again. We need a new affine filter with anchor points and GUI for that, this is something I can add to MLT sometime if we get Cairo included.

**Closed by jliljebl** 2015-08-27 22:30 UTC
Labels: auto-migrated, bug, Priority-Medium, Type-Defect
