### ISSUE TITLE
flowblade on ubuntu mate loads 50% of the processor

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#600] opened 2019-02-04 20:13 UTC
The user writes: "Good day. I start to learn Flowblade. The Ubuntu Mate system just running the program loads 50% or more. Something is wrong ... version 1.16. Now I will be updated to 2.0"
![1](https://user-images.githubusercontent.com/26217756/52234224-35a8aa00-28d2-11e9-9ec3-2497ba4b1066.jpg)
"on version 2.0, the same trouble. All applications are closed except for Flowblade and the system monitor. I did not find the Flowblade process itself in the monitor, but I found another one..."
![2](https://user-images.githubusercontent.com/26217756/52234315-6852a280-28d2-11e9-9d8b-c2dbc102446a.jpg)

**Comment by smolnp** [comment] 2019-02-05 14:53
"Ubuntu 18.04.1 LTS (Bionic Beaver) x86_64
Linux 4.15.0-45-generic x86_64
MATE 1.20.1"

**Comment by jliljebl** [comment] 2019-02-05 18:14
This is duplicate of #194.

Flowlbade works like an allways-on conveyor belt. Once you start it, it keeps displaying frames, doesn't matter if playback pressed or not.

**Comment by smolnp** [comment] 2019-02-06 22:06
I could not fully describe the situation. The user did not download the project, he simply launched the video editor and checked how much it consumes resources. I checked on three machines (rosa r11, lubuntu 04/18/1 and kde neon) did not reveal this problem, but the screenshots of the user show that the problem is present.

**Comment by jliljebl** [comment] 2019-02-07 08:04
Ok, I'll test this on virtual machine with Ubuntu Mate sometime.  There was another report on Mate system so I can bet info on both when I get around to testing this.

**Comment by parti-zanu** [comment] 2019-08-21 10:10
> The user did not download the project, he **simply launched the video editor** and checked how much it consumes resources. 

Same: open flowblade, load nothing, touch nothing, CPU usage is ~20% each core

strace looks like this

`
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 6575) = 1 ([{fd=6, revents=POLLIN}])
recvmsg(6, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\241 ]=\7\0\340\5\221\1\0\0\26\4\0\0\0\0\0\0\245Wa\263\n\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 0 (Timeout)
poll([{fd=6, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=6, revents=POLLIN|POLLOUT}])
recvmsg(6, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\241 ]=\7\0\340\5\222\1\0\0\24\4\0\0\0\0\0\0\324\224\0\0\33A\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
writev(6, [{iov_base="5\30\4\0\374\v\340\5\7\0\340\5\24\0\364\1\213\4\6\0\375\v\340\5\374\v\340\5*\0\0\0"..., iov_len=772}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 772
`

[flowblade-strace.txt](https://github.com/jliljebl/flowblade/files/3524779/flowblade-strace.txt)

fd 6 is a socket @/tmp/.X11-unix/X0
fd 8 is a socket @/tmp/dbus-W9zKa0YKHI

- flowblade 2.0
- MLT found, version: 6.16.0
- numpy version: 1.15.2
- OS: Linux Mint 19.2
- Python 2.7.15+
- GCC 7.3.0
- GTK+ version: 3.22.30

**Comment by jliljebl** [comment] 2019-09-27 06:26
This *really* is duplicate of #194.

Once you start Flowblade is starts putting frames on screen at current displayed FPS. If user hasn't loaded anything, it displays just the black frame visible on monitor.

**Constant processor load immediately after application start is expected behavior.**

**Closed by jliljebl** 2019-09-27 06:26 UTC

**Comment by parti-zanu** [comment] 2019-09-27 10:57
maybe this should be included in a README as a "Known issue - won't fix" because every new user is bound to report it. Just a thought.

**Comment by jliljebl** [comment] 2019-09-27 11:22
@parti-zanu I think you are right, we will add this into F.A.Q. and known issues list.
