### ISSUE TITLE
Hangs up when trying to add Clips

### ISSUE THREAD

**Issue by extremMiSt** [jliljebl/flowblade#455] opened 2017-11-19 16:31 UTC
Every time I try to add Clips I get this error in the console:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 224, in run
    gui.media_list_view.fill_data_model()
  File "/usr/share/flowblade/Flowblade/guicomponents.py", line 869, in fill_data_model
    media_object = MediaObjectWidget(media_file, self.media_object_selected, bin_index, self.monitor_indicator)
  File "/usr/share/flowblade/Flowblade/guicomponents.py", line 913, in __init__
    self.matches_project_profile = media_file.matches_project_profile()
  File "/usr/share/flowblade/Flowblade/projectdata.py", line 401, in matches_project_profile
    best_media_profile_index = mltprofiles.get_closest_matching_profile_index(self.info)
  File "/usr/share/flowblade/Flowblade/mltprofiles.py", line 177, in get_closest_matching_profile_index
    fps = round(float(float(fps_num)/float(fps_den)), 1)
ZeroDivisionError: float division by zero
```

**Comment by jliljebl** [comment] 2017-11-28 10:10
I'm unable to reproduce this. Which MLT version you are using, see (Help-> Runtime Environment)?

**Comment by jliljebl** [comment] 2018-05-09 15:02
We are not getting any follow-up, closing as *unreproduced.*

**Closed by jliljebl** 2018-05-09 15:02 UTC
Labels: unreproduced

**Comment by All-The-Foxes** [comment] 2023-07-03 00:13
I have just reproduced this using a 1440p webm. The error is as follows:

[matroska,webm @ 0x7f8bb4036a40] Could not find codec parameters for stream 0 (Video: vp9, none(tv, bt709), 2560x1440): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x7f8bb408f880] Could not find codec parameters for stream 0 (Video: vp9, none(tv, bt709), 2560x1440): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x7f8bb40b69c0] Could not find codec parameters for stream 0 (Video: vp9, none(tv, bt709), 2560x1440): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x7f8bb40a46c0] Could not find codec parameters for stream 0 (Video: vp9, none(tv, bt709), 2560x1440): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[image2 @ 0x7f8bc0000bc0] The specified filename '/home/munch/.cache/flowblade/thumbnails/ea28df8ca3793ea14b529c64c0ba1844.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x7f8bc0000bc0] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 275, in run
    gui.media_list_view.fill_data_model()
  File "/usr/share/flowblade/Flowblade/guicomponents.py", line 1280, in fill_data_model
    media_object = MediaObjectWidget(media_file, self.media_object_selected, self.release_on_media_object, self.monitor_indicator)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/flowblade/Flowblade/guicomponents.py", line 1325, in __init__
    self.matches_project_profile = media_file.matches_project_profile()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/flowblade/Flowblade/projectdata.py", line 427, in matches_project_profile
    best_media_profile_index = mltprofiles.get_closest_matching_profile_index(self.info)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/flowblade/Flowblade/mltprofiles.py", line 226, in get_closest_matching_profile_index
    fps = round(float(float(fps_num)/float(fps_den)), 1)
                      ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
Killed

**Comment by All-The-Foxes** [comment] 2023-07-03 00:26
Here's a photo so you can see what the carets are pointing at.

![Screenshot from 2023-07-02 20-23-58](https://github.com/jliljebl/flowblade/assets/116322192/c2d7a8cd-e989-48d0-b870-ef5aae2885bf)
