### ISSUE TITLE
Odd CPU usage when idle

### ISSUE THREAD

**Issue by shiba89** [jliljebl/flowblade#315] opened 2017-01-19 11:35 UTC
I think it's quite odd that Flowblade stays at a constant ~16% CPU usage even when idle, just started and empty workspace in this case. Is this to be expected?

![schermata del 2017-01-19 12-30-41](https://cloud.githubusercontent.com/assets/3816409/22105207/40268b68-de43-11e6-94c6-4cf34a741a5b.png)

Flowblade 1.10

**Comment by dvdlvr** [comment] 2017-01-23 16:01
I get between 8-10% CPU when Flowblade is idle. I guess it's normal.

**Comment by jliljebl** [comment] 2017-01-23 16:16
This very likely duplicate of:

https://github.com/jliljebl/flowblade/issues/194

Basically the cause for this is that Flowblade displays frames always at Project Ppofile fps even if there is no playback. You always getting full fps playback, even if video is paused you're getting 25 fps playback of paused frame or even just black screen.

I'm not planning to revisit this issue in foreseeable future.

**Closed by jliljebl** 2017-01-23 16:16 UTC
Labels: duplicate
