### ISSUE TITLE
Several obvious bugs in the development version

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#939] opened 2020-11-30 19:33 UTC
![Screenshot_20201130_221728](https://user-images.githubusercontent.com/26217756/100654967-ac425180-335b-11eb-8f0b-978a33cbce3b.png)
1) The scroll bar overlaps the delete filter icon
2) Filters in the new filter panel are not translated, although localization works in the filter selection panel.
3) The keyframe tool works only with sound, and does not work with brightness and other filters. If any other filter has already been added to the clip, the keyframe tool does not work at all.

**Comment by jliljebl** [comment] 2020-12-02 06:34
Ok, I knew about 1 and 3, but 2 was new.

**Comment by jliljebl** [comment] 2020-12-03 09:46
1 and 2 now fixed, 3 will require maybe 200+ lines of code, will take some more time still.

**Comment by jliljebl** [comment] 2020-12-15 07:27
3. was a one line regression bug instead of happening because of removing multipart filters, should be fixed now.

**Closed by jliljebl** 2020-12-15 07:27 UTC
