### ISSUE TITLE
FLATPAK - Batch render queue doesn't show

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#849] opened 2020-04-23 10:01 UTC
Please include the following information.
1) Flowblade version (Help->About): 2.4.0 **FLATPAK**
2) MLT version (Help->Runtime Environment): 6.18
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening:
Open Flowblade.
Go to Render -> Batch Render Queue
Nothing happens.
I then put something on the timeline and added it to the batch render queue to check if it wasn't because the queue was empty, but still no Batch Render Queue shows up.

I could not find any error messages.

**Comment by jliljebl** [comment] 2020-04-23 11:44
Can you look at file *USER_HOME/.cache/flowblade/log_batch_render* and see if there are any error messages?

**Comment by dvdlvr** [comment] 2020-04-23 11:51
I looked at it and there were no error messages. Sent from my Huawei tablet

**Comment by jliljebl** [comment] 2020-04-23 11:57
Ok. Well,I'll do  Flatpak specific debugging. This may be something sandboxing related.

**Comment by jliljebl** [comment] 2020-04-23 12:00
Oh, this duplicate of #835, closing.

**Closed by jliljebl** 2020-04-23 12:00 UTC
