### ISSUE TITLE
Improve the titler

### ISSUE THREAD

**Issue by tiotrom** [jliljebl/flowblade#731] opened 2019-10-08 22:43 UTC
It would be fantastic to treat text as text, and not as images. This way you can later edit it. I've seen pretty much all video editors on Linux struggle with this aspect. Why is the reason? Cheers!

**Comment by jliljebl** [comment] 2019-10-09 12:07
This is duplicate of https://github.com/jliljebl/flowblade/issues/667, closing.

All video editors handle text as images, but e.g. Flowblade does not hide this fact inside some "Text Clip" construct. There may be developments on this later, see last comment on the earlier Issue.

**Closed by jliljebl** 2019-10-09 12:07 UTC
Labels: duplicate

**Comment by tiotrom** [comment] 2019-10-09 13:13
I see. SVG would also be a good option then. Cheers!

**Comment by jliljebl** [comment] 2019-10-09 13:57
We are going to do some "text clip" thing ...some time, but it just is has not crystallized what to best approach should be and there are many other thing ś that need attention.

**Comment by tiotrom** [comment] 2019-10-09 14:03
I understand. I think the best outcome would be to:
1. have a good quality (when scaling, or effects are applied to it) - for this probably you need SVG
2. be able to edit it later on - simply edit the text and it will be updated in the timeline
3. maybe in the future add some text-specific effects

I used Sony Vegas for many years on Windows and the tool text, even in 2011, was revolutionary compared to anything I've seen on Linux. It was as simple as adding a text, then edit it anytime from timeline, add effects to it, the quality was great, and so forth. Of course they are a huge team and lots of money behind, but I'm just saying I would love to see something similar on a video editor in Linux. You already did a fantastic job with flowblade.
