### ISSUE TITLE
Preview not possible

### ISSUE THREAD

**Issue by schuessm** [jliljebl/flowblade#178] opened 2015-11-30 09:00 UTC
I don't see all previews on the media tab in flowblade, and I got no success with the rebuild function.

**Comment by jliljebl** [comment] 2015-11-30 10:06
Could you run Flowblade from terminal (usually with command "flowlblade") post output of trying the rebuild function.

**Comment by schuessm** [comment] 2015-11-30 16:34
Hi,

thats the result in terminal

failed to make icon from: /home/martin/Flowblade/5328f226c9098763749a04bb175041b6.png
[swscaler @ 0x7fbcffb02ea0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fbcc081f040] deprecated pixel format used, make sure you did set range correctly       
[swscaler @ 0x7fbcc1b9c920] deprecated pixel format used, make sure you did set range correctly       
[png @ 0x7fbcc089f040] Provided packet is too small, needs to be 3961942
[consumer avformat] error with video encode 0

failed to make icon from: /home/martin/Flowblade/82705645a6646c4c5fbb0fa3f398c29e.png
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcfc1b1f20] unsupported color_parameter_type aclc
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcffa4a7e0] unsupported color_parameter_type aclc                      
[swscaler @ 0x7fbcffdc0c60] deprecated pixel format used, make sure you did set range correctly       
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcffc557c0] unsupported color_parameter_type aclc                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcc09805e0] unsupported color_parameter_type aclc                      
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcc0899840] unsupported color_parameter_type aclc                      
[swscaler @ 0x7fbcc07e8da0] deprecated pixel format used, make sure you did set range correctly       
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcc0899e80] unsupported color_parameter_type aclc                      
[swscaler @ 0x7fbcc1e00920] deprecated pixel format used, make sure you did set range correctly       
[png @ 0x7fbcc06e2960] Provided packet is too small, needs to be 4246891
[consumer avformat] error with video encode 0

**Comment by jliljebl** [comment] 2015-11-30 18:29
I may have miscommunicated, please post the full terminal print out from from program launch all thought an attempt to rebuild thumbnails. Which OS you are using? Did you build some of dependencies from source?

**Comment by schuessm** [comment] 2015-11-30 19:11
OS: Mint 17.2 (Ubuntu 14.04 LTS) KDE4-Desktop. I installed the deb package, I'm build nothing from the source.
The print out is attached in txt-File. Hope it helps.
[flowblade.txt](https://github.com/jliljebl/flowblade/files/47665/flowblade.txt)

**Comment by jliljebl** [comment] 2015-11-30 19:39
Why did you cut out the start from the printout that shows the MLT version and all the available codecs? Which MLT version you are using? 

Anyway Ubuntu 14.04 LTS is not supported, if Mint 17.2 is based on that, then your OS is not supported. I'm leaving this open to see if other OSes display similar problems.

It is highly unlikely that any code changes in Flowblade would help with this issue, it probably some version problem between MLT/ffmpeg/swscaler in Mint 17.2.

**Comment by schuessm** [comment] 2015-11-30 20:19
OK. Thank you. Can I use an older flowblade for my distro

**Comment by schuessm** [comment] 2015-12-01 07:14
What linux version with which UI to you support?

**Comment by jliljebl** [comment] 2015-12-01 07:52
In principle any 64-bit system with GTK 3.12 and MLT 0.9.2 or higher. (Ubuntu 14.04 for example has GTK 3.10)  

However, with hundreds of distributions running on any type of hardware available it is impossible for me to support and fix any other types of bugs then those that are caused by problems in Flowblade source code, and I'm 99.5% sure that your problems are not caused by bugs in Flowblade source code, but rather by having incompatible versions of libraries installed.

The 1.4 release was tested on Ubuntu 15.10, 14.10, Linux Mint 17 (MATE 'Qiana' version) and Debian 8...but now you're telling me that Linux Mint 17 is not working for you. In my VirtualBox installation Mint 17 works very well, but maybe you have problems because of using the KDE version, or maybe you have a 32bit version... I do not know.

This Issue provides information that can be useful in the long term, but as far as I can see,  there is nothing I can do to fix it.

**Comment by faridosc** [comment] 2015-12-01 08:44
@jliljebl maybe we could consider providing a binary executable ala shotcut, but dont know how hard would that be...

**Comment by jliljebl** [comment] 2015-12-01 08:59
Creating and distributing binary executable would be quite hard and is really not in my area of expertise.

Dan already provides the script to build and install Flowblade - http://www.mltframework.org/bin/view/MLT/BuildScripts - but I do not recommend it to non-expert users. I would rather see some widely accepted application container solution like xdg-app become available and then use that.

**Comment by faridosc** [comment] 2015-12-01 09:05
@jliljebl +1 for xdg-app

**Comment by schuessm** [comment] 2015-12-01 12:04
@jliljebl: Thank you for the Information, I thought also that my problem ist perhaps kde. Now I'll try it with Cinnamon the standard ui for Linux mint 17. And by the way I'm on 64-bit version. I hope I can change my installation so easy. ;-) Thank you for your great work. Perhaps you can switsch to RELINK mode if I open a project and some files are deleted. At the beginning of my work with flowblade I was confused that the program closed by itself when i open my project. then I remeber that I've deleted a title file which I had created and used in the project.

**Comment by jliljebl** [comment] 2015-12-02 09:27
Perhaps you mean that it should open the Media Relinker tool automatically if not all media is present? Yes, that could be an useful idea.

Hopefully you find a solution that enables you to run Flowblade successfully. I'm closing this now, I can always re-open, if I get similar reports.

**Closed by jliljebl** 2015-12-02 09:27 UTC

**Comment by schuessm** [comment] 2015-12-04 15:05
I have a solution: I updated my melt to actual version and upgraded all what is written there:

https://answers.launchpad.net/openshot/+faq/1861

**Comment by jliljebl** [comment] 2015-12-04 20:40
Gerat that you found a solution. I'll add reference to this in F.A.Q later for other mint users.

**Comment by schuessm** [comment] 2015-12-05 11:32
And one more I found out today, never change the default tumbnail, rendered folder, thats perhaps the reason. Today I changed it to another folder on a other drive, and all the tumbnails was gone ;-)
