### ISSUE TITLE
Keyboard Shortcuts for Overwrite (and other) Tools

### ISSUE THREAD

**Issue by kaerfredoc** [jliljebl/flowblade#408] opened 2017-06-11 18:11 UTC
After selecting a clip and switching to overwrite mode, the arrow keys control the playback head not the clip position. None of the modifiers appear to move the clip either. For tools like overwrite you'd want to use the keyboard to make fine-grained adjustments one frame at a time (and possibly 5/10 at a time).

**Comment by jliljebl** [comment] 2017-06-11 18:52
I'll look what Avid/Premiere/Final Cut x do here and implement something similar if there is some solution fitting our design.

**Comment by jliljebl** [comment] 2017-06-11 19:19
Premiere does:

     Move Selection Left                    Left
     Move Selection Right                  Right
    Step Forward	                         Left
    Step Backward	                         Right

...so Premiere seems to have key function depending on context.. Others do not seem to have similar function.

I'm not sure at this point. Maybe we could follow Premier or maybe make  "Windows" + Arrow move clips when selected with overwrite tool.

I'll leave this open and do decisions later, this could be bit difficult to do, not quite sure.

**Comment by kaerfredoc** [comment] 2017-06-12 04:04
Looks like FCP uses the following. Not sure which is the best option.

To nudge the clips, do any of the following:
- Move the selection left by one frame: Press Comma (,)
- Move the selection left by 10 frames: Press Shift-Comma (,)
- Move the selection right by one frame: Press Period (.)
- Move the selection right by 10 frames: Press Shift-Period (.)

**Comment by jliljebl** [comment] 2017-06-14 09:11
After thinking about this I have come to the conclusion that Premiere type "arrow-key-function-is-state-dependant" is the right way to go here, mostly because we already have that for "Trim" tools. Making "Move" tools behave similarly would be logical.

So I'd have no problem with this feature magically appearing in Flowblade.

The problem is that doing this will require adding new internal state, managing transitioning to/from it across multiple modules and modifying multiple overlay functions. This will be a midsize investment in development time. ATM I feel that many other features are more important so this will not be done in near future.

I'll add "in feature queue" label but I may take some time before we get to this.

**Comment by jliljebl** [comment] 2019-02-26 17:00
We can do this easier by just doing an edit per key event, and not involve any state stuff, which may actually be better approach.

**Comment by jliljebl** [comment] 2019-02-26 18:46
We did almost as suggested, except that we used Control instead Shift for 10 frame nudges, will be in 2.2.

* Move the selection left by one frame: Press Comma (,)
* Move the selection left by 10 frames: Press Control-Comma (,)
* Move the selection right by one frame: Press Period (.)
* Move the selection right by 10 frames: Press Control-Period (.)

**Closed by jliljebl** 2019-02-26 18:46 UTC
Labels: in feature queue - low priority
