### ISSUE TITLE
User Profile Editing confirmation dialog windows hidden behind Profiles Manager

### ISSUE THREAD

**Issue by DellAnderson** [jliljebl/flowblade#437] opened 2017-09-22 08:32 UTC
Problem:
Hidden Dialog box
Steps to reproduce: 
When Creating (Save New Profile) or Deleting (Delete Selected) a User Profile in the Profiles Manager, the screen appears to lock up, but after some searching it was discovered that a confirmation window is popping up invisibly _behind_ the Profiles manager.  Moving the Profiles Manager out of the way each time allows one to click the OK on the confirmation box and resume control of computer.

No other installed software behaves this way and google search found only rare mention of other apps doing this (e.g. Firefox) and the official solution for that (OpenBox configuration for applications <focus>yes</focus>) did not work for Flowblade.  No known setting found oin Flowblade to control placement of open box confirmation dialogs to allow their Z layer to be in front of other windows.

System:
Lubuntu 16.04 (OpenBox windows manager)
Flowblad 0.14.0 (from official Ubuntu Repository via Synaptics Package manager).

**Comment by jliljebl** [comment] 2017-09-22 11:21
Ok, I'm closing this as *invalid* because:
* this does not reproduce in my Ubuntu 17.04
* version 0.14 is 3+ years old and we cannot accept any reports based on it.

I would suggest that you download the latest version from here: https://github.com/jliljebl/flowblade/releases (it's the file flowblade-1.12.0-1_all.deb)

If that does not help, I would file a bug against OpenBox WM.

**Closed by jliljebl** 2017-09-22 11:21 UTC
Labels: invalid

**Comment by DellAnderson** [comment] 2017-09-22 19:52
Thanks for the quick reply. In my defense, I will say that 16.04 is an LTS version (supported for 5 years , or 2021) and flowblade is THE only app out of dozens that I have had the hidden window experience with so far (I have read about Firefox having it but never experienced it).

Thank you for your suggestion of an updated version (although I prefer PPA's over manual .deb installs).  If that does not work, is there anything special about the flowblade confirmation window for User Profile creation that I could report against OpenBox WM?   Or should I just say:   I love your manager for (infinity-1) uses --- the only one it does not work with is flowblade's User Dialog confirmation box?    I think they would laugh me off the internet!   ;-)
