### ISSUE TITLE
Crash when adding some files

### ISSUE THREAD

**Issue by All-The-Foxes** [jliljebl/flowblade#1101] opened 2023-07-03 00:44 UTC
Flowblade version: 2.8
MLT version: 7.12.0
Your distribution: Ubuntu 23.10

I'm not sure what's going on here. I have edited several webm videos in 1440p with the exact same properties but today one of them throws this error when I try to add it to Flowblade.

![Screenshot from 2023-07-02 20-23-58](https://github.com/jliljebl/flowblade/assets/116322192/479b1e6f-12a0-4042-981d-28b3a149f2b7)

**Comment by jliljebl** [comment] 2023-07-03 15:32
So there is another report on this #455 where you commented. Maybe we can find some common factor here. I thought is that meybe ffmpeg/avformat has changed somehow, but the older report is from a few years back, so probably not that.

**Comment by All-The-Foxes** [comment] 2023-07-03 18:40
> Okay, the "fps_den" property that is 0 is what MLT reports, and info originally comes from avformat.
> 
> The relevant line in program is:
> 
> ```
>     info["fps_den"] = frame.get_double("meta.media.frame_rate_den")
> ```
> 
> This should be non-zero if information is available. I'm initially thinking here that the file is maybe corrupted. You can try opening the file in VLC and what it says in _Tools/Media Information/Codec_.

I did that immediately when I got the error. VLC correctly reports 60fps and the file plays normally.

**Comment by All-The-Foxes** [comment] 2023-07-04 06:39
> Okay, the "fps_den" property that is 0 is what MLT reports, and info originally comes from avformat.
> 
> The relevant line in program is:
> 
> ```
>     info["fps_den"] = frame.get_double("meta.media.frame_rate_den")
> ```
> 
> This should be non-zero if information is available. I'm initially thinking here that the file is maybe corrupted. You can try opening the file in VLC and what it says in _Tools/Media Information/Codec_.

Here's a screenshot of the output for reference.
![image](https://github.com/jliljebl/flowblade/assets/116322192/d356defb-9122-4401-8e59-b2aa54e91ed1)

**Comment by jliljebl** [comment] 2023-07-04 07:19
Thanks. If the clip is of kind that you could make available for download I could try to reproduce this here.

**Comment by All-The-Foxes** [comment] 2023-07-04 07:50
Here's the file that's causing the error.
[Derpalerp.webm](https://github.com/jliljebl/flowblade/assets/116322192/6da4dfb4-d40a-4e5c-b1db-42e18aadfa82)

**Comment by jliljebl** [comment] 2023-07-04 08:03
Thanks, it reproduced exactly like in your system. Not sure yet what is going on, but we can probably at least do some workaround type fix if I can't find the root cause.

**Comment by jliljebl** [comment] 2023-07-18 20:59
This crashes Shotcut and KDEnlive too. MLT won't be able to handle this, so making efforts to load the file won't be useful. I'll add code to detect this issue on load, and then refuse to load it so that app does not crash.

**Comment by All-The-Foxes** [comment] 2023-07-18 21:36
Do you have any idea what about the file is causing the crash?

**Comment by jliljebl** [comment] 2023-07-19 07:03
I think MLT and ffmpeg(libavformat) are working ok, but something went wrong when creating the file, wrong metadata maybe, don't know.

**Comment by jliljebl** [comment] 2023-07-19 07:40
I added code to not load files with 'fps_den' == 0. Closing as fixed.

**Closed by jliljebl** 2023-07-19 07:40 UTC
Labels: bug
