### ISSUE TITLE
Font Roboto used for font Roboto Condensed

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#976] opened 2021-01-22 15:04 UTC
Please include the following information.
1) Flowblade version (Help->About): 2.6.3
2) MLT version (Help->Runtime Environment): 6.22.1
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.10 (Pop!_OS)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Install Roboto font and Roboto Condensed font and text with Roboto Condensed font in the Titler. Probably because of the space in the font name, the font Roboto (not the condensed version) is used.

**Comment by jliljebl** [comment] 2021-01-24 09:48
Ok, will try reproduce/fix during next cycle.

**Comment by jliljebl** [comment] 2021-05-02 15:30
Confirmed, lets see if there is a fix.

**Comment by jliljebl** [comment] 2021-05-02 15:58
When creating fonts using my code:

    self.font_desc = Pango.FontDescription(layer.get_font_desc_str())

the strings I got were:

    Roboto Regular 40
    Roboto Condensed Regular 40

so the descriptions were good, but the condensed font didn't show up. The I tried:

    if "Condensed" in layer.get_font_desc_str():
        self.font_desc.set_stretch(Pango.Stretch.CONDENSED)
            
but that didn't help either. I'll close this for now because I have no idea on how to proceed. If I get an idea on what to try next, I'll give this another go.

**Closed by jliljebl** 2021-05-02 15:58 UTC
Labels: bug

**Comment by PanderMusubi** [comment] 2021-05-19 09:19
Probably related to a space in the name.
