### ISSUE TITLE
Stop Render + Quit leaves some processes running

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#318] opened 2017-01-27 10:42 UTC
Hi,

Version 1.10
After doing a direct render (i.e. no batch) I hit 'Stop Render' and then quit the program without saving the project.
The result is that on the command line where I started flowblade I see 'Exiting app...' but I don't get my prompt back.

A ps -ef | grep flow gives me the following:
$ ps -ef | grep flow
user   9288  5802 38 11:37 pts/1    00:00:20 python /usr/bin/flowblade
user   9329  9288 28 11:37 pts/1    00:00:12 /usr/bin/python /usr/share/flowblade/Flowblade/launch/flowbladeaudiorender #&#file:/media/movie.ts HD 720p 25 fps /usr/share/flowblade/Flowblade

The second process keeps on running until I manually kill it (Or probably until rendering has finished - but I was not that patient).

**Comment by jliljebl** [comment] 2017-01-27 13:39
I was unable to reproduce with:

1. Load a Project
2. Start render
3. Press "Stop Render"
4. Close application as fast as possible

Audio waveform rendering has something to do with this because */usr/share/flowblade/Flowblade/launch/flowbladeaudiorender* is launch script for background audio waveform rendering process.

Not sure yet where the problem is.



/flowbladeaudiorender

**Comment by dvdlvr** [comment] 2017-01-28 13:32
Thanks. I'll do some further testing.

**Comment by dvdlvr** [comment] 2017-01-30 13:26
Update:
The lingering flowbladeaudiorender is started when you add a clip - without starting any render yet.
If the clip you add is very long, that process will run for some time.
If you do quick testing, rather than actual work, this running process will not allow you to quit flowblade unless it's killed.

So, during testing, using smaller clips will avoid the problem. During 'normal' editing you probably won't notice it because you don't want to quit after just a few seconds.

I would say this should be addressed at some point but right now I would personally not see this as a priority.

**Comment by jliljebl** [comment] 2017-02-01 17:14
I'm not sure this is a bug.

1. Audio levels are best created by rendering data and saving in on disk.
2. For long clips this obviously takes a long time
3. Renderer only writes data to disk once it is completely ready, so shutting down machine during render only causes the render to be attempted again later.

I'm closing this as *not a bug*, I can re-open later if needed.

**Closed by jliljebl** 2017-02-01 17:14 UTC
Labels: not a bug
