### ISSUE TITLE
No video displayed elementaryos

### ISSUE THREAD

**Issue by codecowboy** [jliljebl/flowblade#275] opened 2016-11-05 07:18 UTC
I just installed Flowblade on ElementaryOS (Loki) which is based on Ubuntu 16.04. I can add a video clip (an mkv) but nothing is shown in the video preview area?

![screenshot from 2016-11-05 07 13 25](https://cloud.githubusercontent.com/assets/178432/20028384/e50d850c-a327-11e6-84dc-8bc3965e9b26.png)

If I hit play, I can hear audio but there is no video.

**Comment by codecowboy** [comment] 2016-11-05 11:23
```
flowblade
FLOWBLADE MOVIE EDITOR repository 1.8
-------------------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.0.0
OS: elementary OS 0.4 Loki
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609]
GTK+ version: 3.18.9
User dir: /home/luke/.flowblade/
Locale: en_US
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Small height: False
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - hap
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libopenjpeg
  - libschroedinger
  - libtheora
  - libvpx
  - libvpx-vp9
  - libwebp
  - libx264
  - libx264rgb
  - libx265
  - libxvid
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - dca
  - eac3
  - flac
  - g723_1
  - mp2
  - mp2fixed
  - nellymoser
  - real_144
  - sonic
  - sonicls
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopus
  - libshine
  - libspeex
  - libtwolame
  - libvorbis
  - libwavpack
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - bit
  - caf
  - cavsvideo
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffm
  - ffmetadata
  - filmstrip
  - flac
  - flv
  - framecrc
  - framemd5
  - g722
  - g723_1
  - gif
  - gxf
  - h261
  - h263
  - h264
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - oma
  - opus
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - caca
  - fbdev
  - opengl
  - oss
  - pulse
  - sdl
  - v4l2
  - xv
...
MLT detection succeeded, 152 formats, 84 video codecs and 65 audio codecs found.
341 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service ladspa.1210 not found.
Brightness dropped, MLT version too low for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  DV/DVD PAL
Selected color detected
BG color detected
Autosave started...
Save project autosave_a43674503f627a6c6d459b955233dfc5
[swscaler @ 0x7fc49023fb40] Warning: data is not aligned! This can lead to a speedloss

```

**Comment by oluja1973** [comment] 2016-11-05 19:47
What about another video? Have you tried several formats? Can you upload a video which is not working and i will try it under ubuntu.

**Comment by codecowboy** [comment] 2016-11-07 08:45
yes I tried an mp4 - example here : https://dl.dropboxusercontent.com/u/72795/599A7539-E477-4323-B8DD-9A362D6A9B99.MP4

**Comment by jliljebl** [comment] 2016-11-07 11:52
The video plays on Flowblade on Ubuntu 16.04.

**Comment by jliljebl** [comment] 2016-11-07 11:55
I'm closing this as duplicate of Issue #228. I'll post a further comment there with a possible solution.

**Closed by jliljebl** 2016-11-07 11:55 UTC
Labels: duplicate
