### ISSUE TITLE
Correct luma range support for the preview needed

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#662] opened 2019-05-10 20:26 UTC
Please include the following information.
1) Flowblade version (Help->About): 2.0.0 (latest git clone)
2) MLT version (Help->Runtime Environment): 6.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian 10 (Buster) with Gnome 3.30
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Here are two screenshots of the Flowblade interface and the (approximately) corresponding frames from resulting H264 file taken from SMPlayer: https://yadi.sk/d/22C3633K1s9dXg

As you can see the image displayed in Flowblade is slightly, but quite noticeably lighter than the frames of the resulting file. It is especially noticeable on the black clip I used in the fadeout. I guess this has something to do with color management, either system's or MLT's, may be rec601-rec709 conversion. Or may be it is caused by Gnome. In general, of course, it wouldn't be much of a problem if it would not spoil all the luma curve corrections: some clips really need those to make certain details more pronounced and the corrections should be rather precise.

**Comment by jliljebl** [comment] 2019-05-21 12:05
Yes, this needs attention and has been on back burner for a while https://github.com/jliljebl/flowblade/issues/309

At this point we will just need to get off SDL 1.2 somehow and make sure the replacement works properly.

But Python 3 comes first, the this comes top of the line item. This could prove *very* difficult for me to do and can have effect on development velocity of the application but there are many possible approaches, the problem is that none are very straight forward.

I'll leave this open because #309 title may not have a very good title but this is a full duplicate of that.

**Comment by jliljebl** [comment] 2023-06-16 06:43
Fixed upstream. This was always an MLT thing and at least MLT 7.12 or higher this is now fixed.

**Closed by jliljebl** 2023-06-16 06:43 UTC
Labels: in feature queue
