### ISSUE TITLE
Unable to display video on elemetaryOS

### ISSUE THREAD

**Issue by danielroehrig** [jliljebl/flowblade#228] opened 2016-04-06 10:04 UTC
When I use the `xserver-xorg-video-nouveau` driver, flowblade works as expected. But when I enable any NVIDIA binary driver (I tried several), the preview video remains black and blank. Audio works, preview images work, but no video.

I am using elementary OS (Ubuntu 14.04), nvidia 364.12, flowblade 1.6.0, mlt 0.9.3, Python 2.7.6

When I start flowblade from the terminal, I get this warnings:
`*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
`

**Comment by jliljebl** [comment] 2016-04-07 06:43
Thanks for the detailed information. It seems probable the the problem is either in MLT or in  the elementaryOS packaking of MLT.

As such it unlikely that I can fix this problem by doing source code changes to Flowblade. I'm still leaving this open to provide the information for other users experiencing this problem.

Filing bug reports on MLT or elementaryOS bug systems would likely be the way to move forward in getting this bug fixed.

**Comment by danielroehrig** [comment] 2016-04-07 07:03
I am using the "sunab kdenlive release" repository (trusty) for mlt, so there is no elementary OS packaging involved. Also, kdenlive and OpenShot are working fine. Strangely enough, if I reboot using the standard open source video driver, flowblade has no problem showing my videos. So, I assume it's either a bug in flowblade or some problems with the nvidia driver.

**Comment by jliljebl** [comment] 2016-04-07 07:19
Okay, thanks.  Another user wrote an email to me:

"""
The video preview is black. I contacted you directly because I wasn't sure it was a bug since a bug of this type would be critical.

In case you are wondering, I am running elementary os freya (based on ubuntu 14.04) and the latest version of flowblade.
"""

so this may still be some Issue that is somehow related to elementaryOS environment. But I'll try to look into this somehow.

**Comment by danielroehrig** [comment] 2016-04-07 16:18
That would be great. If it turns out to be elementary OS related, I am more than happy to try to fix it. Or at least report to the elementary OS guys.

**Comment by jliljebl** [comment] 2016-04-08 16:55
From user Stephen K Owusu (SK) who may be suffering from the same problem:


Terminal output:
FLOWBLADE MOVIE EDITOR repository 1.6
-------------------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 0.9.0

** (flowblade:3310): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-t9kQJLfqG5: Connection refused
OS: elementary OS Freya
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
GTK+ version: 3.14.15
User dir: /home/blipskr/.flowblade/
Locale: en_GB
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Small height: True
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - asv1
  - asv2
  - bmp
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - qtrle
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v410
  - wmv1
  - wmv2
  - xbm
  - xwd
  - zlib
  - zmbv
  - libopenjpeg
  - libschroedinger
  - libtheora
  - libvpx
  - libx264
  - libxvid
...
---
audio_codecs:
  - comfortnoise
  - aac
  - ac3
  - ac3_fixed
  - alac
  - eac3
  - flac
  - mp2
  - nellymoser
  - real_144
  - vorbis
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s16be
  - pcm_s16le
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s32be
  - pcm_s32le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopencore_amrnb
  - libopus
  - libspeex
  - libvo_aacenc
  - libvo_amrwbenc
  - libvorbis
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - asf
  - ass
  - asf_stream
  - au
  - avi
  - avm2
  - cavsvideo
  - crc
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - ffm
  - ffmetadata
  - filmstrip
  - flac
  - flv
  - framecrc
  - framemd5
  - g722
  - gif
  - gxf
  - h261
  - h263
  - h264
  - hls
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ismv
  - ivf
  - latm
  - m4v
  - md5
  - matroska
  - matroska
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - null
  - nut
  - ogg
  - oma
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtsp
  - sap
  - segment
  - smjpeg
  - smoothstreaming
  - sox
  - spdif
  - srt
  - swf
  - 3g2
  - 3gp
  - truehd
  - rcv
  - voc
  - wav
  - webm
  - yuv4mpegpipe
  - alsa
  - oss
...
MLT detection succeeded, 112 formats, 59 video codecs and 52 audio codecs found.
372 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service lumakey not found.
Brightness dropped, MLT version too low for this filter.
MLT service frei0r.cairoimagegrid not found.
Loading transitions...
MLT transition frei0r.cairoaffineblend not found.
MLT transition frei0r.cairoblend not found.
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  HD 1080p 30 fps

(flowblade:3310): Gtk-WARNING **: Theme file for Adwaita has no name


(flowblade:3310): Gtk-WARNING **: Theme file for Adwaita has no directories


(flowblade:3310): Gtk-WARNING **: Theme file for Adwaita has no name


(flowblade:3310): Gtk-WARNING **: Theme file for Adwaita has no directories

maximize
Selected color detected
BG color detected
Autosave started...
Save project autosave_bcb3a1fef57fba84042c69b65020dc5f﻿

**Comment by codecowboy** [comment] 2016-11-05 11:24
did anyone find the cause of this? I am not using nvidia drivers but am using elementaryOS and I get a blank video window

**Comment by jliljebl** [comment] 2016-11-07 11:57
Ok, does Flowblade installed from this appimage make any difference?

https://bintray.com/probono/AppImages/Flowblade_Movie_Editor/_latestVersion#files

**Comment by codecowboy** [comment] 2017-03-08 08:15
@jliljebl sorry for the delay in replying. This _didnt_ resolve things for me.

**Comment by codecowboy** [comment] 2017-03-08 08:22
@danielroehrig did you find a solution to this?

**Comment by danielroehrig** [comment] 2017-03-08 18:50
Unfortunately not. I just tried the AppImage file but the video monitor stays black.

**Comment by jliljebl** [comment] 2017-03-23 11:23
@danielroehrig Ok, I think there is a good change that this is related to https://github.com/jliljebl/flowblade/issues/309

See this: https://bugs.freedesktop.org/show_bug.cgi?id=27222

 There are indications that this might go away with xorg-server-1.19.0, does anyone have that?

**Comment by amsheppard** [comment] 2017-03-23 11:33
Wow. That was quick. Thanks!

I saw that other issue on eOS 14.04 but saw no further followup.

Here's my X.Org packages

```
ii  python3-xkit                                   0.5.0ubuntu2                                              all          library for the manipulation of xorg.conf files (Python 3)
ii  xorg                                           1:7.7+13ubuntu3                                           amd64        X.Org X Window System
ii  xorg-docs-core                                 1:1.7.1-1ubuntu1                                          all          Core documentation for the X.org X Window System
ii  xserver-xorg                                   1:7.7+13ubuntu3                                           amd64        X.Org X server
ii  xserver-xorg-core                              2:1.18.4-0ubuntu0.2                                       amd64        Xorg X server - core server
ii  xserver-xorg-input-all                         1:7.7+13ubuntu3                                           amd64        X.Org X server -- input driver metapackage
ii  xserver-xorg-input-evdev                       1:2.10.1-1ubuntu2                                         amd64        X.Org X server -- evdev input driver
ii  xserver-xorg-input-libinput                    0.18.0-1                                                  amd64        X.Org X server -- libinput input driver
ii  xserver-xorg-input-synaptics                   1.8.2-1ubuntu3                                            amd64        Synaptics TouchPad driver for X.Org server
ii  xserver-xorg-input-vmmouse                     1:13.1.0-1ubuntu2                                         amd64        X.Org X server -- VMMouse input driver to use with VMWare
ii  xserver-xorg-input-wacom                       1:0.32.0-0ubuntu3                                         amd64        X.Org X server -- Wacom input driver
ii  xserver-xorg-video-all                         1:7.7+13ubuntu3                                           amd64        X.Org X server -- output driver metapackage
ii  xserver-xorg-video-amdgpu                      1.1.2-0ubuntu0.16.04.1                                    amd64        X.Org X server -- AMDGPU display driver
ii  xserver-xorg-video-ati                         1:7.7.0-1                                                 amd64        X.Org X server -- AMD/ATI display driver wrapper
ii  xserver-xorg-video-fbdev                       1:0.4.4-1build5                                           amd64        X.Org X server -- fbdev display driver
ii  xserver-xorg-video-intel                       2:2.99.917+git20160706-1ubuntu1~elementary0.4.1           amd64        X.Org X server -- Intel i8xx, i9xx display driver
ii  xserver-xorg-video-nouveau                     1:1.0.12-1build2                                          amd64        X.Org X server -- Nouveau display driver
ii  xserver-xorg-video-qxl                         0.1.4-3ubuntu3                                            amd64        X.Org X server -- QXL display driver
ii  xserver-xorg-video-radeon                      1:7.7.0-1                                                 amd64        X.Org X server -- AMD/ATI Radeon display driver
ii  xserver-xorg-video-vesa                        1:2.3.4-1build2                                           amd64        X.Org X server -- VESA display driver
ii  xserver-xorg-video-vmware                      1:13.1.0-2ubuntu3                                         amd64        X.Org X server -- VMware display driver
```

**Comment by jliljebl** [comment] 2017-03-23 11:58
So it is not only NVidia on ElementaryOS:

https://github.com/jliljebl/flowblade/issues/358

**Comment by BurninLeo** [comment] 2018-02-17 17:48
I encounter the same problem with Ubuntu 16.04 (latest updates installed) and Flowblade 1.14 (same for 0.14, btw): No matter what video driver I select (proprietary Nvidia or the open source option), the video remains black. I have tried other videos from different sources in different formats - the videos remains black.

**Comment by BurninLeo** [comment] 2018-02-17 18:35
I encounter the same problem with Ubuntu 16.04 (latest updates installed) and Flowblade 1.14 (same for 0.14, btw): No matter what video driver I select (proprietary Nvidia or the open source option), the video remains black. I have tried other videos from different sources in different formats - the videos remains black.

**Comment by apellizcos** [comment] 2018-04-12 11:19
what is the solution? I have the same problem with nvidia and elementary os

**Comment by jliljebl** [comment] 2019-02-17 17:54
I'm merging this with #603 because I believe all elementaryOS related display issues get fixed with that.

**Closed by jliljebl** 2019-02-17 17:54 UTC
Labels: help wanted, unclear bug

**Comment by cyberbasil42** [comment] 2020-10-01 14:00
How To Fix This Error 

I Am Kali Linux User . 

![Screenshot 2020-10-01 19:29:10](https://user-images.githubusercontent.com/71592556/94819127-86143a00-041c-11eb-924d-10288c8e8708.png)

**Comment by dvdlvr** [comment] 2020-10-01 21:56
Download and install mlt 6.18 from mltframework.org or use the flatpak version of Flowblade.-------- Original message --------From: cyberbasil42 <notifications@github.com>Date: Thu, 1 Oct 2020, 16:01To: jliljebl/flowblade <flowblade@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [jliljebl/flowblade] Unable to display video on elemetaryOS (#228)
How To Fix This Error
I Am Kali Linux User .
