### ISSUE TITLE
Fast Motion Doesn't Render The Correct Thing

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#376] opened 2017-04-22 02:35 UTC
When attempting to create a time lapse I found that the fast motion tool only rendered a portion of the video of the calculated length, and not even in fast/slow motion! The portion of the video rendered appears to not be random, but as to what changes it i have yet to figure out.

Using 1.12.0 on Antergos (Arch Linux)

**Comment by benrob0329** [comment] 2017-04-22 03:13
Update: It would appear that source mark in and out cause issue with some clips, as full source render works as expected.

**Comment by jliljebl** [comment] 2017-05-14 09:49
Ok, will investigate.

**Comment by jliljebl** [comment] 2017-07-26 14:03
I did some tests to find a another way to do source mark in/out renders but that didn't work out.

I will try to improve on this eventually, the current way is a bit suspect for mark in/out renders.

**Comment by jliljebl** [comment] 2017-07-31 16:46
Marking this as bug without clearly reproducing,  I believe the report likely to be accurate.

**Comment by jliljebl** [comment] 2018-01-21 16:56
I tried an alternate method of rendering partial clips but unfortunately that didn't work. That could have fixed the issue.

However, the motion clips are now rendered with "timewarp" producer (if available) instead of the previous "framebuffer" producer, and this may have fixed the issue as the issue is quite possibly caused by the producer used.

I was still unable to reproduce his issue on my system, and  I'm closing this. I do believe that this could happen, but I do not have any way to move forward with this that I'm aware of.

If any user still hits this, then suggested work around is to render full clips. If someone is willing to make available for download a clip that makes this issue happen, I would be interested in doing further tests and maybe try a MLT level fix if seems feasible.

**Closed by jliljebl** 2018-01-21 16:56 UTC
Labels: unreproduced
