### ISSUE TITLE
Flowblade doesn't fit on laptop screen

### ISSUE THREAD

**Issue by Noah11012** [jliljebl/flowblade#467] opened 2017-12-13 19:55 UTC
I am using Flowblade version 1.14.0 on a laptop screen that is 1366 x 768 (16:9). The issue is that there is no maximize button and Flowblade doesn't fix it on my screen so I am missing a lower portion of the program. 

![screenshot from 2017-12-13 14-54-16](https://user-images.githubusercontent.com/26338478/33959459-8a13d576-e015-11e7-950c-c33ddc1573a0.png)

My distro and desktop environment is Linux Mint 18.3 and Cinnamon

**Comment by AGI-THB** [comment] 2017-12-18 15:53
Have you tried pressing the  f11-button ?
Or go to "view" and then klick on "fullscreen"

**Comment by Noah11012** [comment] 2017-12-18 16:11
@AGI-THB Yes, I already tried going into full screen mode. All it did was remove the border around the window.
![screenshot from 2017-12-18 11-10-56](https://user-images.githubusercontent.com/26338478/34115618-2affa452-e3e4-11e7-87a8-41f43dfe0ee4.png)

**Comment by jliljebl** [comment] 2017-12-24 18:50
There seems to be some kind of regression here, this definitely worked before.

**Comment by jliljebl** [comment] 2017-12-24 19:13
Confirmed and fixed, will be in 1.16. This was unfortunately a regression, using version 1.12 is recommended for small screens.

**Closed by jliljebl** 2017-12-24 19:13 UTC
Labels: fixed
