### ISSUE TITLE
keyboard shortcuts dont work under bspwm

### ISSUE THREAD

**Issue by icf20** [jliljebl/flowblade#992] opened 2021-02-18 18:58 UTC
Please include the following information.
1) Flowblade version (Help->About):

2.6.3

2) MLT version (Help->Runtime Environment):

6.24

3) Your distribution (Ubuntu, Debian, Mint etc.):

https://archlinux.org/packages/community/any/flowblade/

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

1 add a clip 2 press x 3 nothing happens

use the mouse to click the razor works, same for delete and everything else

my gut tells me i need the whole gnome desktop to make it work

**Comment by jliljebl** [comment] 2021-02-22 07:54
There has been 3-4 issues already with tiling window managers not handling keyboard events correctly, latest one being #984 where problem was *Gtk.Widget.has_focus()* not working correctly.

> my gut tells me i need the whole gnome desktop to make it work

Or patch bspwm to correctly handle GTK key events. This has worked on mainstream DEs with zero problems for years, so the problem is with bspwm, closing.

**Closed by jliljebl** 2021-02-22 07:54 UTC
