### ISSUE TITLE
Audio out of sync during playback

### ISSUE THREAD

**Issue by dpopowich** [jliljebl/flowblade#816] opened 2020-02-27 01:28 UTC
Please include the following information.
1) Flowblade version (Help->About):

**2.4.0 (flatpak)**

2) MLT version (Help->Runtime Environment):

**6.18.0**

3) Your distribution (Ubuntu, Debian, Mint etc.):

**Ubuntu 18.04.3**

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I have a number of mp4 clips (ffprobe output below) and when I play any of them (from the timeline or just the clip) the audio is out of sync.  I have a hard time imagining my hardware can't keep up
(AMD Ryzen 7 3800X 8-Core Processor, 32GB RAM) yet when I play this video in flowblade my cpu is pegged at 100% (or more) and I have this audio problem.

When I play the mp4 in vlc, it plays as expected and the cpu usage of its process sits around 45%.

Goes without saying, but it's rather impossible to edit when the audio/video are out of sync.  Is there something obvious I'm missing?

Thanks for any help!

***
```console
$ ffprobe foo.mp4
...
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'foo.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2017-03-27T21:44:13.000000Z
  Duration: 00:01:20.79, start: 0.000000, bitrate: 16166 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 15851 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2017-03-27T21:44:13.000000Z
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2017-03-27T21:44:13.000000Z
      handler_name    : Alias Data Handler
```

**Comment by dpopowich** [comment] 2020-02-27 15:07
I should have added, I have a high-performing nvidia card:

```console
$ lspci -v -s 2d:00.0 
2d:00.0 VGA compatible controller: NVIDIA Corporation TU116 [GeForce GTX 1660 Ti] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: eVga.com. Corp. Device 1263
	Flags: bus master, fast devsel, latency 0, IRQ 124
	Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at f000 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Legacy Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [250] Latency Tolerance Reporting
	Capabilities: [258] L1 PM Substates
	Capabilities: [128] Power Budgeting <?>
	Capabilities: [420] Advanced Error Reporting
	Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Capabilities: [900] #19
	Capabilities: [bb0] #15
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
```

**Comment by jliljebl** [comment] 2020-02-27 15:45
Hi, is it possible for you to make an affected clip available for download? Testing with the same input that you are using would be much more informative.

**Comment by dpopowich** [comment] 2020-02-27 16:49
PM'd a link to a video clip.

**Comment by jliljebl** [comment] 2020-02-27 17:42
@dpopowich Thanks you, got the clip. The problem is in playback, if one renders clip from timeline then everything is in sync.

I will first do testing to see how widely this reproduces.

Currently still doing heavy feature development but focus will turn to issues on this list once I have beta versions of everything that goes in next release. It may take week or two before first follow up on this.

**Comment by dpopowich** [comment] 2020-02-27 18:07
> @dpopowich Thanks you, got the clip. The problem is in playback, if one renders clip from timeline then everything is in sync.

Of course, this begs the question of how one edits with audio/video out of sync if I'm making subtle cuts.  Any hints on doing so until this issue can be resolved are most welcome.

Thank you!

**Comment by jliljebl** [comment] 2020-02-27 18:36
**Proxy editing workflow** is the standard approach when having playback issues, see here: http://jliljebl.github.io/flowblade/webhelp/proxy.html

Unfortunately we seem to have some outdated info in the docs, item  1-3 should read: Press hamburger menu and select item *Render Proxy Files For Selected Media*.

**Comment by jliljebl** [comment] 2020-05-05 06:39
Closing this as a bug, work on this issue will be related to larger long term effort on getting better playback performance.

**Closed by jliljebl** 2020-05-05 06:39 UTC
Labels: unresolved
