### ISSUE TITLE
playback lag with title clip

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#151] opened 2015-08-28 14:17 UTC
whenever there is a title clip a small playback lag happens...

**Comment by jliljebl** [comment] 2015-08-28 18:39
Do you mean a png file produced by the Titler -tool? Could you post a screenshot of timeline showing the configuration causing the playback lag?

This is likely a hardware performance/mlt related issue, and as such cannot be fixed within Flowblade application, but it is always possible that there are problems with Flowblade in this particular situation.

**Comment by faridosc** [comment] 2015-08-28 19:00
yep, done by the titler...

what i found strange is that this lag doesn't happen when there is an image sequence (unlike in kdenlive). 

over at the g+ page there is an image of a post where you commented.

**Comment by jliljebl** [comment] 2015-09-07 12:04
I completely unable to reproduce this. Only possible conclusion is that there are some performance issues here that are not present in my system, but become a factor on other systems. I'm leaving this open for further reports for now, but no action is currently planned on this.

**Comment by faridosc** [comment] 2015-09-07 18:15
testing here i saw that with Affine Blend the lag doesn't happen but woth Affine it does...

**Comment by jliljebl** [comment] 2015-09-07 20:51
Yes, "Affine" slows down. This is too much, now its gonna go.

**Comment by jliljebl** [comment] 2015-09-07 21:01
Creating new "Affine" compositors is no longer possible. It is considered that stable and predictable functionality is more important than the additional functionality (non-planar rotations and shears) that "Affine gives". 

Existing projects with "Affine" compositors will continue to function as before.

No further action on any "Affine" related issues will be taken.

**Closed by jliljebl** 2015-09-07 21:01 UTC
