### ISSUE TITLE
Proxy out of sync

### ISSUE THREAD

**Issue by deedos** [jliljebl/flowblade#150] opened 2015-08-21 11:49 UTC
Hi. I tried to use a proxy editing of a mov/xdcam422 file on Ubuntu 14.04 64bits deb package (flowblade-1.0.0-1_all.deb)  but got sync issues with both codec options (mpeg2 and mpeg4).
Is there anythin I could do to overcome ?

thanks in advance

**Comment by jliljebl** [comment] 2015-08-21 12:28
Which project Profile you used?. You can get the Profile info in the Project tab and then post it here in a comment.

Also, would it be possible for you to make a single clip of material available for download using Dropbox or some other method? Those files are typically too big to be attached here, and if we're looking at sync issues, it would be better to have a long clip with audio.

I have had recently some other problems with render syncs, so this may be related.

**Comment by faridosc** [comment] 2015-08-21 15:56
i can't reproduce the error using a .mov from a 5d.

**Comment by deedos** [comment] 2015-08-25 00:21
That's the transporte stream clip https://dl.dropboxusercontent.com/u/31495718/2198131d585eaa5ca2862047a886593c.m2t

**Comment by jliljebl** [comment] 2015-08-25 00:55
The sound and video are definitely out of sync here, so something is going wrong.

However, to try to _fix_ this I need your original mov/xdcam422 files from which the proxy file was rendered so that I can _reproduce_ the error on my system and then try to _change the program_ in a way that the error goes away.

I actually didn't doubt that you had the error, I never do, but to be able to fix it I need to reproduce it on my system, and so far I have not been able to do so with various clips that I have.  So I would like to have your original clip and try to reproduce to the error. I hope that the clip isn't too big to upload.

**Comment by deedos** [comment] 2015-08-25 13:38
I' ll send  you the original asap.. It ' s about 300MB. Uploadable. (Even
if brazilian bad upload speed..)
Cheers
Em 24/08/2015 21:55, "jliljebl" <notifications@github.com> escreveu:

**Comment by deedos** [comment] 2015-08-28 14:52
@jliljebl  here we are http://we.tl/nkDmmGm3we

**Comment by deedos** [comment] 2015-09-02 15:40
@jliljebl the wetransfer download is about to expire. cheers

**Comment by jliljebl** [comment] 2015-09-02 17:33
Ah, I downloaded one clip that was mute and didn't realize that a new download was available. I got the clip now, I'll look at this sometime this week.

**Comment by jliljebl** [comment] 2015-09-02 17:51
Ok, I can reproduce this, finding a fix may take a while.

**Comment by deedos** [comment] 2015-09-02 22:24
Good to know you reproduce . cheers
Em 02/09/2015 14:51, "jliljebl" <notifications@github.com> escreveu:

**Comment by jliljebl** [comment] 2015-10-08 21:51
I've forwarded information on this to MLT people, but haven't heard from  them yet, and it seems likely that they are not taking action on this. 

I will test with the clip I have if situation has changed every now and ten, but there is no fix for this coming right now. The file was very unusual with 50000kbps video rate on mpeg2, this may be the cause that this hasn't been noticed/fixed by MLT or ffmpeg people.

**Comment by jliljebl** [comment] 2016-05-10 20:31
I'm closing this and added a known Issue item for this. Fixing this would require major effort,  and I do not believe it justified for this rare issue.

**Closed by jliljebl** 2016-05-10 20:31 UTC
Labels: bug
