### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by lfinston** [jliljebl/flowblade#1131] opened 2023-10-23 12:32 UTC
Hello,

Flowblade version:  
MLT version:  7.4.0
Distribution:  Ubuntu

I've been using Flowblade for making animated YouTube videos.  I have not been using any live-action footage but rather I've been making individual images that I import as PNG files.  I often have occasion to change the graphics default length when inserting images onto the timeline.  However, each time I do, using this:  Edit/Preferences/Editing/Graphics Default Length
I get a pop-up window with a message about how a restart is required after changing some preferences. 

However, this change doesn't require a restart and it is annoying to get this warning each time and to have to click on the pop-up window in order to get rid of it.

Would it be possible to add a "Don't show this warning again" checkbox or to make it possible to disable this warning in some other way?

It would also be nice to be able to change the length of frames after the images are already on the timeline.  For example, if I inserted 20 images with a default length of 2 frames, to select a number of images on the timeline and have the lengths of all of the images in the selection changed to 4.  Would it be possible to implement such a feature or is it already possible to do this in another way?

Thanks.

Laurence Finston

**Comment by dvdlvr** [comment] 2023-10-23 12:50
I think I can implement the first part of this.It'll be a good way to get back into development on Flowblade after a long period of inactivity.My thought is this: add an internal flag to each preference that will trigger the message or not.If any preference is changed that needs a restart the message will pop up.If all of the modified preferences do not need a restart the message won't pop up.Will need a bit of examination of the preferences but the coding should be pretty straightforward.Not sure about the second part of the email regarding the images, so I'll leave that bit to someone else.Regards,StevenSent from my Huawei tablet-------- Original message --------From: Laurence Finston ***@***.***>Date: Mon, Oct 23, 2023, 14:33To: jliljebl/flowblade ***@***.***>Cc: Subscribed ***@***.***>Subject: [jliljebl/flowblade] "Restart required" warning:  Can it be disabled? (Issue #1131)
Hello,
Flowblade version:
MLT version:  7.4.0
Distribution:  Ubuntu
I've been using Flowblade for making animated YouTube videos.  I have not been using any live-action footage but rather I've been making individual images that I import as PNG files.  I often have occasion to change the graphics default length when inserting images onto the timeline.  However, each time I do, using this:  Edit/Preferences/Editing/Graphics Default Length
I get a pop-up window with a message about how a restart is required after changing some preferences.
However, this change doesn't require a restart and it is annoying to get this warning each time and to have to click on the pop-up window in order to get rid of it.
Would it be possible to add a "Don't show this warning again" checkbox or to make it possible to disable this warning in some other way?
It would also be nice to be able to change the length of frames after the images are already on the timeline.  For example, if I inserted 20 images with a default length of 2 frames, to select a number of images on the timeline and have the lengths of all of the images in the selection changed to 4.  Would it be possible to implement such a feature or is it already possible to do this in another way?
Thanks.
Laurence Finston

**Comment by jliljebl** [comment] 2023-10-23 15:10
> I think I can implement the first part of this.It'll be a good way to get back into development on Flowblade after a long period of inactivity.

@dvdlvr Great, it would nice to have you back. This can perhaps get a bit annoying, and could be improved.

> It would also be nice to be able to change the length of frames after the images are already on the timeline.  For example, if I inserted 20 images with a default length of 2 frames, to select a number of images on the timeline and have the lengths of all of the images in the selection changed to 4. 

@lfinston This might be possible, I'll look into this for 2.14 latest.

**Comment by lfinston** [comment] 2023-10-23 16:04
Thank you both for your answers.  I've been using the version supplied by Ubuntu.  I'll clone the repository and see if I can start using a more recent version, if any, or the development version.

There are a couple of other things I've noticed and/or had problems with.  I might be able to solve some problems by myself, with the help of the documentation.  However, I'm not sure how much the specific requirements of animation were considered in the design of Flowblade.  I've noticed a couple of things that could possibly be made easier.

One problem is that it's not possible to include the same file more than once.  This makes sense for a single bin, but for my purposes, it's a problem that it's not allowed for different bins.  It's not really convenient to copy the file or use symbolic links.  I haven't tried using symbolic links yet.  I assume it would work but theoretically Flowblade could disallow this, too.   

With animation, you're working with individual images rather than film clips and typically you'll have 1 to 5 frames per image, so if you're working "on twos" (two frames per image), for one minute, that would already be 15 * 60 = 900 images.  (None of my animations are that long.)  I've been using bins to organize my images, that is, one bin per sequence (in the generic sense, not a Flowblade sequence), but if I want to use an image in more than one sequence, which is a common case, I have to copy it (or possibly use a link).

I was also rather surprised to find out that Flowblade only stores references to the images, unless you save a backup snapshot.  Most of the time, I write programs for GNU 3DLDF to generate the (PNG) images (using MetaPost) and they are numbered.  If I change the program, the numbering and hence the filenames will also change.  It's possible that a couple of my Flowblade projects are no longer reproducible for this reason.

I started making backup snapshots, but I think it may have failed in a couple of cases where I had a very large number of images.  I would have to check this, however, as I am not completely sure.

Would it be possible to implement a feature where the images can optionally be stored with the project without making a backup snapshot?  This would be like the behavior of GIMP and Audacity (which I also use for my animation projects).

Thanks again.

Laurence

**Comment by lfinston** [comment] 2023-10-23 17:24
I did try installing from the git repository, but it didn't work and nor did the version that was pre-installed.  Currently, I have no working version.  I tried reinstalling from synaptic.  When that didn't work, I rebooted and tried again.  It still didn't work.  I then completely uninstalled Flowblade, which is supposed to remove any configure files.  I then reinstalled it, but it still didn't work.  I rebooted and it still didn't work.

Whether I call flowblade from the command line or click on the icon in the dock, processes are started (which I have to kill by hand), but no window appears.  With the version from git, a window would briefly appear before the program crashed.

Does anyone have any suggestions?  I don't know anything else to try.

Thanks.

Laurence

**Comment by lfinston** [comment] 2023-10-23 17:25
Typo:  I meant "configuration files".

**Comment by dvdlvr** [comment] 2023-10-23 18:28
I'm not on my computer so can't check, but if I remember right you should have a .flowblade directory, probably in your home directory.Rename it and reinstall and that hopefully solves the problemSent from my phone-------- Original message --------From: Laurence Finston ***@***.***>Date: Mon, 23 Oct 2023, 19:25To: jliljebl/flowblade ***@***.***>Cc: dvdlvr ***@***.***>, Mention ***@***.***>Subject: Re: [jliljebl/flowblade] "Restart required" warning:  Can it be disabled? (Issue #1131)
I did try installing from the git repository, but it didn't work and nor did the version that was pre-installed.  Currently, I have no working version.  I tried reinstalling from synaptic.  When that didn't work, I rebooted and tried again.  It still didn't work.  I then completely uninstalled Flowblade, which is supposed to remove any configure files.  I then reinstalled it, but it still didn't work.  I rebooted and it still didn't work.
Whether I call flowblade from the command line or click on the icon in the dock, processes are started (which I have to kill by hand), but no window appears.  With the version from git, a window would briefly appear before the program crashed.
Does anyone have any suggestions?  I don't know anything else to try.
Thanks.
Laurence

**Comment by lfinston** [comment] 2023-10-23 18:49
There were three directories below my home directory:

.local/share/flowblade
.cache/flowblade
.config/flowblade

I deleted them and reinstalled (from synaptic) and it works again now.

Thanks.

Laurence

**Comment by dvdlvr** [comment] 2023-10-23 20:23
GreatSent from my Huawei tablet-------- Original message --------From: Laurence Finston ***@***.***>Date: Mon, Oct 23, 2023, 20:49To: jliljebl/flowblade ***@***.***>Cc: dvdlvr ***@***.***>, Mention ***@***.***>Subject: Re: [jliljebl/flowblade] "Restart required" warning:  Can it be disabled? (Issue #1131)
There were three directories below my home directory:
.local/share/flowblade
.cache/flowblade
.config/flowblade
I deleted them and reinstalled (from synaptic) and it works again now.
Thanks.
Laurence

**Comment by lfinston** [comment] 2023-10-24 06:17
> I started making backup snapshots, but I think it may have failed in a couple of cases where I had a very large number of images. I would have to check this, however, as I am not completely sure.

I just confirmed that it did indeed fail.  I just made a backup snapshot from a project with only 24 images with 3 iterations on fives = 12 seconds and the directory contains a subdirectory named `media' and an flb file.  When I tried this before with a project with a lot of images (probably > 100), the pop-up window "Save Project Backup Snapshot" never closed and no flb file was written.  I didn't check that all the media files had been written, but it would appear that Flowblade got stuck at this point and that they weren't.

It would also be nice if Flowblade would remember the path to the backup directory and set its parent directory to be the default for the next backup snapshot and/or to include it in the list presented.  The way it is now, I always have to click on "Choose" and work my way through my directory structure.

Another nice feature would be if it were possible to store the images in a compressed form.  Depending on the file type, this may not make much difference, but it might work for some.  However, I don't know whether it would work for any that Flowblade can import.

Thanks.

Laurence

**Comment by lfinston** [comment] 2023-10-24 08:11
> I can add a preference for that, default being current the behavior, and user can then select to allow multiple instances of same file.

Great.

> Yes, with video editors this feature is called **'Ingest'** and it makes a copy (and optionally transcodes media files) into a project data folder on import. This makes project data folder possibly take up large fractions of available disk space and therefore requires user to able to decide where project data is saved. This feature is coming for 2.12 and will be called _'Data Stores'_. After that we can build up to make completely movable projects.

I can understand that.  I deliberately bought a computer for the purposes of making videos with a lot of storage but for many people that would be a problem.

> > Another nice feature would be if it were possible to store the images in a compressed form. Depending on the file type, this may not make much difference, but it might work for some. However, I don't know whether it would work for any that Flowblade can import.
> 
> This does not seem doable.

Okay.

> Note that using repository version is _not_ data safe, we do tests before release against previous version to make sure everything goes smooth, but during development cycle some problems may occur.

I wouldn't expect it to be "bullet-proof" and I can always use the stable version, if necessary.

Another nice feature would be to make it possible to reverse the order of the image files in the bins for purposes of appending to the timeline.  For example, this video starts with a repeated iris effect:  https://www.youtube.com/watch?v=hu8jTnfbC7o

Each time, the iris expands and contracts.  I realized this by copying the files <filename>001.png, <filename>002.png, etc., and giving the copies descending numbers instead of ascending ones.  Then I put them all on the bin and appended all of them to the timeline.  In order for the project to be reproducible, I have to keep the copies.  If I could have just reversed the order of the files before appending, I could save some space by deleting them.  It wouldn't be practicable to insert them individually by hand in reverse order.

I've also had some problems with selecting items in the bins and appending them to the timeline.  If I only want to append one image, I have to make sure that only that image is selected.  Otherwise, sometimes a single image is appended, but not the one I wanted.  This happens fairly often.

I had a look around but didn't find any way of reducing the playback speed in the preview.  This would make it a lot easier to synchronize the visuals with the audio.  In the video cited above, I thought I'd found a better way of doing the synchronization, but the results didn't turn out very well.  I thought it had looked better in the previewer and in the VLC Player, but on YouTube and DeviantArt, it's obviously not so great.  I could do it better even without slowing down the playback, but that would make it much easier.

It would also be nice if there was a way of refreshing the thumbnails.  As I mentioned, the filenames of my image files can change if I change the program that generated them.  I had one project where they changed so much, that I had to delete the Flowblade project and start again, because it wasn't possible to tell what the image files looked like.   

Thanks.

Laurence

**Comment by lfinston** [comment] 2023-10-24 08:50
> I've also had some problems with selecting items in the bins and appending them to the timeline. If I only want to append one image, I have to make sure that only that image is selected. Otherwise, sometimes a single image is appended, but not the one I wanted. This happens fairly often.

I meant by dragging with the mouse, not by using "Append selected media to the timeline".

I also haven't been able to get it to work to select media and then delete the selected ones.  Pressing the "delete" key causes the files to no longer be selected but doesn't delete them.  It would also be nice if it were possible to delete a range, as on the timeline.

**Comment by jliljebl** [comment] 2023-10-24 16:42
I'm having some trouble here extracting individual actionable issues from the your text. It greatly helps communication when presenting multiple issues if they are presented as numbered list so issues can be individually referred by 1), 2) etc.  

I'll try to get compose a list as I understand the issues and comment each item. 

> 1) Another nice feature would be to make it possible to reverse the order of the image files in the bins for purposes of appending to the timeline...I meant by dragging with the mouse, not by using "Append selected media to the timeline".

So you would like to have menu action *Append all Media to Timeline In Reversed" *Append Selected Media to Timeline Reversed".

> 2) I've also had some problems with selecting items in the bins and appending them to the timeline. If I only want to append one image, I have to make sure that only that image is selected. Otherwise, sometimes a single image is appended, but not the one I wanted. This happens fairly often.

This I have not experienced. Are you using version 2.10? For release 2.10 there was item *Make Media Panel Shift + Mouse selection work in standard way* that changed the item are selected items in Media Panel.

> 3) I had a look around but didn't find any way of reducing the playback speed in the preview. 

That's true, MLT does not support slo-mo playback. Currently when keeping Left/Right Arrow keys down we get 'playback' with audio if Audio Scrubbing is on. It would possible to ignore key repeat events and make the that playback slower if e.g. some modifer key is held down. We can get improivement here for 2.14, 2.12 is quite closed for new features now.

**Comment by lfinston** [comment] 2023-10-24 17:35
> I'm having some trouble here extracting individual actionable issues from the your text. It greatly helps communication when presenting multiple issues if they are presented as numbered list so issues can be individually referred by 1), 2) etc.

Okay.  I'll be glad to write down a numbered list as soon as I get a chance.

> > 1. Another nice feature would be to make it possible to reverse the order of the image files in the bins for purposes of appending to the timeline...I meant by dragging with the mouse, not by using "Append selected media to the timeline".
> 
> So you would like to have menu action *Append all Media to Timeline In Reversed" *Append Selected Media to Timeline Reversed".

No, I was thinking more of being able to reverse the ordering of the files in the bin and then just using "Append All Media" or "Append Selected Media".  By the way, it would be nice to have a keyboard shortcut for this, and especially for changing the default graphics length, which requires some clicking through menues.  However, I will put this on the numbered list.

> 
> > 2. I've also had some problems with selecting items in the bins and appending them to the timeline. If I only want to append one image, I have to make sure that only that image is selected. Otherwise, sometimes a single image is appended, but not the one I wanted. This happens fairly often.
> 
> This I have not experienced. Are you using version 2.10? For release 2.10 there was item _Make Media Panel Shift + Mouse selection work in standard way_ that changed the item are selected items in Media Panel.

I am currently using 2.8 but I will make another attempt at using the development version from the git repository.

The problem occurs when I click on a thumbnail in the bin, drag it to the timeline, and insert it (normally at the end).  Then I go back to the bin, and click on another thumbnail.  Now both are selected or maybe more than just the two.  When I drag the thumbnail I want to the timeline, a different one is inserted, but only one and not all of the selected ones.  That is, just clicking on a thumbnail once doesn't set the selection to just that thumbnail.  If I do it twice, it works the way I want, but I don't always remember to do this.
 
> > 3. I had a look around but didn't find any way of reducing the playback speed in the preview.
> 
> That's true, MLT does not support slo-mo playback. Currently when keeping Left/Right Arrow keys down we get 'playback' with audio if Audio Scrubbing is on. It would possible to ignore key repeat events and make the that playback slower if e.g. some modifer key is held down. We can get improivement here for 2.14, 2.12 is quite closed for new features now.

I don't mind waiting.  I appreciate that you're willing to consider implementing my feature requests.

The problem is that I don't have video material from a camera with a soundtrack that I could use to synchronize with a separate track on an audio file.  I have a single audio file and I have to insert the images at the correct places.  At first, I did this by playing back and listening because I hadn't noticed that the graphic for the audio track shows a "wave form" corresponding to the soundtrack.  I also figured out if I use a single track with just the melody as a reference, the "wave form" is clearer.  I delete this track later and keep the mixed track.  On mixed tracks, the "wave form" isn't necessarily clearly readable.  However, in my last music video, I counted on this working and didn't check it carefully when I was finished, so the result wasn't too good.

It is very tedious to do this by listening and stopping the playback, because it requires a lot of backtracking.  It would be much easier if I could just slow down the playback, but I understand that this might not be an easy feature to implement.

Thanks.

Laurence

**Comment by lfinston** [comment] 2023-10-26 05:52
This is my list of feature requests:

1.  Graphics default length:  Disable warning.

2.  Graphics Default length:  Make settable per sequence.

3.  Change the number of frames for selected images on the timeline.

4.   Save image files along with project.

5.  Remove conflicts between different versions of Flowblade on same system
    (configuration directories).

6.   Make it possible to include the same file in different bins.

7.   Reverse order of image files in the bins for purposes of appending to the
     timeline.

8.   Make it possible to reorder image files in bins by dragging and dropping.

9.   Fix problem with selecting items in the bins and appending them to the timeline.
     That is, clicking on an image should change the selection to only that image.
     When clicking on an image and dragging it to the timeline, only that image
      should be appended or inserted.

10.  Possible bug:  Upper- and lowercase letters are not distinguished when adding files to bins.
     For example, Huge_001.png couldn't be added because huge_001.png was present.
     In timeline, all caps is used.  Is there a connection?

11. Make it possible to refresh the thumbnails for the images.

12.  Make it possible to reorder the bins in the list at the left side of the screen.

13.  Change playback speed for purposes of editing and synchronization with audio.

14.  Increase possible magnification on timeline.  With images with length of one frame:
     If window is too small, even with maximum magnification, the mouse can't be used to select it
     or lengthen it by clicking and dragging the sides.  Arrows are displayed but nothing happens.

     When the window size is increased, it becomes possible, but it isn't convenient.

15.  In the timeline:  Make it possible to shift by x frames instead of just 1, where x can be
     chosen using a menu.  Currently, it's only possible to play or shift by a single frame.

16.  Make it possible to set keyboard shortcuts, especially for
    "Append all media to timeline"
    "Append selected media to timeline"
    "Edit default graphics length"

Thanks.

Laurence

**Comment by jliljebl** [comment] 2023-10-26 12:30
Thanks, I'll change the Issue title to *Multiple Issues* and categorize and comment on the items below.

#### Possible bugs
*10) Possible bug: Upper- and lowercase letters are not distinguished when adding files to bins.
    For example, Huge_001.png couldn't be added because huge_001.png was present.
    In timeline, all caps is used. Is there a connection?*

This one I'll look at and fix if confirmed for 2.12.

*9) Fix problem with selecting items in the bins and appending them to the timeline.
    That is, clicking on an image should change the selection to only that image.
    When clicking on an image and dragging it to the timeline, only that image
    should be appended or inserted.*
    
This needs to be confirmed on the latest version. Comment here or file new Issue if still present in 2.10 or 2.12. For my taste the media selection + Drag'n'Drop is fine, but there may be some subtle behavioral issues that I have not thought about.


#### Can do for 2.14

*1) Graphics default length: Disable warning*
*2) Graphics Default length: Make settable per sequence.*
*3) Change the number of frames for selected images on the timeline.*
*6) Make it possible to include the same file in different bins.*
*7) Reverse order of image files in the bins for purposes of appending to the
    timeline.*
*13) Change playback speed for purposes of editing and synchronization with audio.*
*17  Make it possible to set keyboard shortcuts, especially for
    "Append all media to timeline"
    "Append selected media to timeline"
    "Edit default graphics length"*
*14)   Increase possible magnification on timeline. With images with length of one frame:
    If window is too small, even with maximum magnification, the mouse can't be used to select it
    or lengthen it by clicking and dragging the sides. Arrows are displayed but nothing happens. When the window size is increased, it becomes possible, but it isn't convenient.*

Some may get postponed to later releases, but these mostly look doable in the near future.

#### Ongoing concerns
*4)  Save image files along with project.*

This is part of multirelease effort to make projects fully movable, starting with implementin 'Ingest' feature.

*5)  Remove conflicts between different versions of Flowblade on same system
    (configuration directories).*

These happening are bugs and will be tested for before 2.12, hopefully no problems occur. After 2.12 there will hopefully never be any additional changes in data layout once we've added Data Stores functionality.

#### Long term

*8) Make it possible to reorder image files in bins by dragging and dropping.*

The current code does not support doing this at all. I'll revist after GTK4 port (as GTK4 may have this available), but that is still several releaseses away.

#### Already working

*11)  Make it possible to refresh the thumbnails for the images.*

In 2.10  we have *Add Recreate Icon feature for Media Items* done so this is available now.

*16) In the timeline: Make it possible to shift by x frames instead of just 1, where x can be
    chosen using a menu. Currently, it's only possible to play or shift by a single frame.*

Select for app menu Edit->Preferences->Playback->Fast Forward / revers Speed for Shift key etc. and change the value. 

*12) Make it possible to reorder the bins in the list at the left side of the screen.*

Mouse Right click on Bin, use the Move submenu.

**Comment by lfinston** [comment] 2023-10-26 13:05
> _9) Fix problem with selecting items in the bins and appending them to the timeline. That is, clicking on an image should change the selection to only that image. When clicking on an image and dragging it to the timeline, only that image should be appended or inserted._
> 
> This needs to be confirmed on the latest version. Comment here or file new Issue if still present in 2.10 or 2.12. For my taste the media selection + Drag'n'Drop is fine, but there may be some subtle behavioral issues that I have not thought about.

This problem caught me again today:  I had appended an image to the timeline, I went back to the bin, where several icons were selected.  I clicked on another icon, which may or may not have been in the selection, the selection wasn't changed, I dragged the icon to the timeline and a different image from the selection was appended to the timeline and it was a single image.  I caught it later, when I previewed a portion of the sequence. 

> #### Already working

> _16) In the timeline: Make it possible to shift by x frames instead of just 1, where x can be chosen using a menu. Currently, it's only possible to play or shift by a single frame._
> 
> Select for app menu Edit->Preferences->Playback->Fast Forward / revers Speed for Shift key etc. and change the value.

That's not what I meant.  I haven't actually used fast-forward or reverse and wouldn't normally need it.  What I would like to be able to do is to use the single-frame advance and reverse icons on the previewer or media player, or whatever it's called, to advance image-by-image rather than frame-by-frame.  The number would usually be the same as the default graphics length.

For example, in my current project, I have one sequence of length approx. 46 sec. and all of the "clips" are single images that take up 8 frames.  For animation, one often needs single-frame advance but in this case it's very tedious to click the button 8 times for each image.  On the other hand, 1/30 sec. is a very short timespan, so animating "on ones" isn't likely to be that common (for my projects). 

> 
> _12) Make it possible to reorder the bins in the list at the left side of the screen._
> 
> Mouse Right click on Bin, use the Move submenu.

Sorry, hadn't noticed that.  I don't have a thorough grasp of Flowblade yet and there are a lot of features I haven't tried yet.

Thanks.

Laurence

**Comment by jliljebl** [comment] 2023-10-26 19:52
> This problem caught me again today: I had appended an image to the timeline, I went back to the bin, where several icons were selected. I clicked on another icon, which may or may not have been in the selection, the selection wasn't changed, I dragged the icon to the timeline and a different image from the selection was appended to the timeline and it was a single image. I caught it later, when I previewed a portion of the sequence.

Like I said, there was a change in 2.8 to 2.10 for this exact behavior, so this one needs to be reported against 2.10 because what you are experiencing is not the way things currently work.  Almost all all Linux distros have Flatpak available, so you can install 2.10 from there, info: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md#installing-flatpak-from-flathub


> That's not what I meant. I haven't actually used fast-forward or reverse and wouldn't normally need it. What I would like to be able to do is to use the single-frame advance and reverse icons on the previewer or media player, or whatever it's called, to advance image-by-image rather than frame-by-frame. The number would usually be the same as the default graphics length.

> For example, in my current project, I have one sequence of length approx. 46 sec. and all of the "clips" are single images that take up 8 frames. For animation, one often needs single-frame advance but in this case it's very tedious to click the button 8 times for each image. On the other hand, 1/30 sec. is a very short timespan, so animating "on ones" isn't likely to be that common (for my projects).

Up / Down Arrows move playhead to next/previous cut, that seems like the behavior you are looking for?

**Comment by lfinston** [comment] 2023-10-26 20:09
> Like I said, there was a change in 2.8 to 2.10 for this exact behavior, so this one needs to be reported against 2.10 because what you are experiencing is not the way things currently work. Almost all all Linux distros have Flatpak available, so you can install 2.10 from there, info: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md#installing-flatpak-from-flathub

Sorry, I thought it might have been unclear what exactly was happening.  To be honest, I want to finish my current project with 2.8 and then try to switch over to the repository version.  It's no big deal if something doesn't work, these projects aren't work-related.

> Up / Down Arrows move playhead to next/previous cut, that seems like the behavior you are looking for?

Yes, thanks.  That's exactly what I want.  I started using Flowblade without reading the manual first and since then I've only ever referred to it.  Sorry, it was bad form on my part for not checking for this myself.

**Comment by jliljebl** [comment] 2023-10-27 07:05
> Sorry, I thought it might have been unclear what exactly was happening. To be honest, I want to finish my current project with 2.8 and then try to switch over to the repository version. It's no big deal if something doesn't work, these projects aren't work-related.

Ok, we'll return to this at a later time if needed.

> Yes, thanks. That's exactly what I want. I started using Flowblade without reading the manual first and since then I've only ever referred to it. Sorry, it was bad form on my part for not checking for this 

No problem, users missing existing features happens. Also, the manual is not fully comprehensive, so it is good idea to look *Edit->Keyboard Shortcuts* window to see if there is something you would find useful.

**Comment by jliljebl** [comment] 2023-10-28 11:39
> 10) Possible bug: Upper- and lowercase letters are not distinguished when adding files to bins.
For example, Huge_001.png couldn't be added because huge_001.png was present.
In timeline, all caps is used. Is there a connection?

This does not reproduce on my system. I don't think there has been changes in this behavior since basically forever. Unfortunately I have no idea how it is possible for you experience this problem.

**Comment by lfinston** [comment] 2023-10-28 11:51
> > 10. Possible bug: Upper- and lowercase letters are not distinguished when adding files to bins.
> >     For example, Huge_001.png couldn't be added because huge_001.png was present.
> >     In timeline, all caps is used. Is there a connection?
> 
> This does not reproduce on my system. I don't think there has been changes in this behavior since basically forever. Unfortunately I have no idea how it is possible for you experience this problem.

It applied to 2.8 and since I finished my project, I plan on using the repository version in the future.  I'll test it when I start a new project.  I suppose it's possible that Huge_001.png was already present in the project and that I was mistaken.

**Comment by lfinston** [comment] 2023-10-30 03:51
I installed the package from the git repository but the program failed to launch:

commit 9afbe5643a174c9b9b80f42ee6ab365cc82925b7

I've attached a file containing the output.  The exit status of the script was 0.  The only things that appeared to be error messages were these lines:

AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'. Did you mean: 'get_width'?
AttributeError: 'Player' object has no attribute 'consumer'

[00LOG.txt](https://github.com/jliljebl/flowblade/files/13200529/00LOG.txt)

Laurence

**Comment by jliljebl** [comment] 2023-10-31 05:59
From F.A.Q:

[Wayland](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/FAQ.md#wayland)

Flowblade does not run natively on Wayland yet, but there are few ways to get Flowblade running.

    Start Flowblade from terminal with command:

    GDK_BACKEND=x11 flowblade

    Use X11 session when running Flowblade

**Comment by lfinston** [comment] 2023-10-31 07:20
Thanks.  This is the first time I've heard the term Wayland.  I'll have to look it up.  Flowblade started without any problem, even though I was using 2.8 and didn't delete any directories with configuration files.  I'll look at the FAQ first before posting in future.

**Comment by jep-fa** [comment] 2023-11-12 11:26
Hello.
For the 5 : Remove conflicts between different versions of Flowblade on same system
(configuration directories).

I made this with each version of Flowblade in different directories:
The file /home/user/.config/flowblade/prefs becomes /home/user/.config/flowblade/prefs_nameOfDirectory. The file /home/user/.config/flowblade/prefs is used by the distribution version.

App.py
```
main()
#change the order of userfolders et respaths
    # Create user folders if needed and determine if we're using xdg or dotfile user folders.
    userfolders.init()

    # Set paths.
    respaths.set_paths(root_path)

```
````
editorpersistance.py
# ------------------------- preferences file for each instance of Flowblade
import respaths
# ------------------------- preferences file for each instance of Flowbladeload()

#Modify prefs path
load()
    # ------------------------- Preferences file for each instance of Flowblade
    root_pref_path = "_" + respaths.ROOT_PATH.split("/")[-4]  # directory of flowblade git clone 
    prefs_file_path = userfolders.get_config_dir() + PREFS_DOC + root_pref_path
#    prefs_file_path = userfolders.get_config_dir() + PREFS_DOC
    # ------------------------- End of Preferences file for each instance of Flowblade
save()
    # ------------------------- Preferences file for each instance of Flowblade
    root_pref_path = "_" + respaths.ROOT_PATH.split("/")[-4] # directory of flowblade git clone 
    prefs_file_path = userfolders.get_config_dir()+ PREFS_DOC  +  root_pref_path
#    prefs_file_path = userfolders.get_config_dir()+ PREFS_DOC
    # ------------------------- End of Preferences file for each instance of Flowblade`

```

**Comment by jliljebl** [comment] 2023-11-18 10:58
> The backgrounds are watercolor and gouache mattes that I scanned and scaled. The original images used in these videos are 1726x982 pixels at 600dpi. The files are typically around 2.5 MB. Previously, I was using images that were about half the width and height but the results were a little blurry and the PostScript fonts in the titles had noticeably jagged edges and blank spots.

I'll have to look at if I can find some particular and fixable Issues after I get the opportunity to do the remaining sessions required for a release.

> I read somewhere that all the code is "currently" in Python. Are there any plans to rewrite it in another language?

No currently about it, its about 70k lines of code and cannot be ported with reasonable amount of effort. We would **not get any noticeable performance improvements by switching to another implementation** language, all performance sensitive code is in MLT and is written is C.

Most major future performance improvements require porting code from CPU to GPU in MLT. There are a couple of things I can do prior to that but those are not going to get us to current commercial performance standard.

**Comment by lfinston** [comment] 2023-11-18 13:33
For what it's worth, I've settled on the image size mentioned above, 1726 x 982, which is not quite in the proportion 16:9.  The difference makes it possible to have the videos displayed in whatever viewers are used in Firefox when viewing them at YouTube or DeviantArt without white edges.  I haven't gotten this to work perfectly yet, but these values give me pretty good results.

If image files are somewhat larger than this, most of the software I use starts to run noticeably more slowly, e.g., GIMP and ImageMagick.  The originals of the watercolor and gouache mattes are all approx. DIN A4 (210x297mm) and I have scans at 600dpi and 1200dpi.  The ones at 600dpi are approx. 7000x5000 px and the ones at 1200dpi are (as one would expect) approx. 14000 x 10000px.  It has turned out to be  impractical to use the images at full size so I always scale them down.   Even just scanning at 1200dpi is very slow and impractical for a large number of mattes.  As a rule of thumb, it seems that a width of about 2000 (and a corresponding height) is okay, 3000 is pushing it and more than 3000 is impractical.

I'm not sure whether there's a difference in performance when handling a file containing large areas of pixels with identical RGB values and handling one like the scans, where there are pixels with many different RGB values spread over the whole raster.  My impression is that there is, but I haven't tested this.

With the videos I mentioned as examples, it would probably be better to render them in parts and then composite the parts.  It didn't work well to have all of the image files in separate bins in a single project.

Thanks.

Laurence

**Comment by dvdlvr** [comment] 2024-02-08 19:18
For info:I've worked on the restart required issue.I've tested quite a few scenarios trying to figure out the best way to program it and make it easy to maintain and code it efficiently.I'm now in the phase where most of the code is adapted.I only have to test each option if restart is actually required or not.After that, the 'restart required' message will only pop up when a restart is actually required.I hope to finish this within 2 weeks.Regards,StevenSent from my phone-------- Original message --------From: Laurence Finston ***@***.***>Date: Mon, 23 Oct 2023, 14:33To: jliljebl/flowblade ***@***.***>Cc: Subscribed ***@***.***>Subject: [jliljebl/flowblade] "Restart required" warning:  Can it be disabled? (Issue #1131)
Hello,
Flowblade version:
MLT version:  7.4.0
Distribution:  Ubuntu
I've been using Flowblade for making animated YouTube videos.  I have not been using any live-action footage but rather I've been making individual images that I import as PNG files.  I often have occasion to change the graphics default length when inserting images onto the timeline.  However, each time I do, using this:  Edit/Preferences/Editing/Graphics Default Length
I get a pop-up window with a message about how a restart is required after changing some preferences.
However, this change doesn't require a restart and it is annoying to get this warning each time and to have to click on the pop-up window in order to get rid of it.
Would it be possible to add a "Don't show this warning again" checkbox or to make it possible to disable this warning in some other way?
It would also be nice to be able to change the length of frames after the images are already on the timeline.  For example, if I inserted 20 images with a default length of 2 frames, to select a number of images on the timeline and have the lengths of all of the images in the selection changed to 4.  Would it be possible to implement such a feature or is it already possible to do this in another way?
Thanks.
Laurence Finston

**Comment by jliljebl** [comment] 2024-02-12 08:04
> For info:I've worked on the restart required issue.I've tested quite a few scenarios trying to figure out the best way to program it and make it easy to maintain and code it efficiently.I'm now in the phase where most of the code is adapted.I only have to test each option if restart is actually required or not.After that, the 'restart required' message will only pop up when a restart is actually required.I hope to finish this within 2 weeks

Ok, thanks for the info, missed this message when going through gmail first time.

**Comment by jliljebl** [comment] 2024-05-06 08:22
I have implement a couple of additional features that will be in release 2.16 that address some requests here:

1)  A favorites system. Bin media files can now be filtered to show 1) all File , 2) only Favorites 3) exclude Bad files.

2) Method of moving files around in Bins.

I'm closing this Issue now as 'fixed' even if not all concerns have been addressed. 

Over the years I have come to find out that working on an Issue describing multiple problems and feature request is very difficult, and I usually close those after I have addressed some of the items.

After next release 2.16 comes out, please file **multiple** Issues each describing a **single** bug or feature request if you feel you would like to see further changes in the application, thanks.

**Closed by jliljebl** 2024-05-06 08:22 UTC
Labels: in feature queue
