### ISSUE TITLE
JKL Scrubbing 1.8 speed not working

### ISSUE THREAD

**Issue by timbze** [jliljebl/flowblade#808] opened 2020-01-20 12:51 UTC
Please include the following information.
1) Flowblade version (Help->About): 2.4.0 (installed with Flatpak)
2) MLT version (Help->Runtime Environment): 6.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10

While playing, I press L for scrub, the timeline under video shows 1.8 but the speed keeps running at 1x. When I press L again it jumps to 3.0 and plays at 3x

**Comment by jliljebl** [comment] 2020-01-24 14:33
Ok, I've tested this on my system and this does not reproduce. Some times 1.8 and 1.0 look very similar depending on material but it also possiblethe issue is somehow system dependent . I need more info from additional systems to if there are additinal reproductions of this issue, please post here info MLT version and OS.

**Comment by timbze** [comment] 2020-01-24 14:51
I uninstalled and reinstalled just to see if that would make any difference but it does not. 1x or 1.8x plays at exactly same speed, but 3x works fine.

MLT version is 6.18.0
OS is Ubuntu 19.10

**Comment by jliljebl** [comment] 2020-05-05 06:59
This really does not reproduce here and I'm closing this as *unreproduced*.

**Closed by jliljebl** 2020-05-05 06:59 UTC
