### ISSUE TITLE
Some keyboard shortcut not working

### ISSUE THREAD

**Issue by Haleycarl** [jliljebl/flowblade#984] opened 2021-01-30 07:52 UTC
1) Flowblade version:2.6.3
2) MLT version :6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.):Arch
Keyboard shortcuts not working such as the following
- Space
- Arrow keys
- I and O (for in and out points)
- Y (insert clip)
- U (appened clip)
- Delete button
- Home
- End
- and some others

**Comment by jliljebl** [comment] 2021-01-30 08:12
These keyboard shortcuts without modifier keys and thus need to observe if timeline has keyboard focus.

Put Clip on timeline, click it and test again. Do shortcuts work now?

**Comment by Haleycarl** [comment] 2021-01-30 10:02
It doesn't work here is a video:
https://efss.qloud.my/index.php/s/PWxqQD2piSJSaJL

**Comment by jliljebl** [comment] 2021-01-30 11:38
Ok, thanks. This does not reproduce here.

With 25+ straight releases and this never having been a problem on any system I'm 100% sure that the issue is not with Flowblade application code and instead we need to find an system environment reason.

1) You seem to be running some tiling window manager. Can you try to reproduce the issue on some mainline DE like Gnome?
2) What is source of your installation: Arch repo, Flatpak or manual install from Github repo?
3) Which GTK version you are running?

**Comment by jliljebl** [comment] 2021-01-30 11:40
Also, which tiling WM you are using?

**Comment by Haleycarl** [comment] 2021-01-30 11:45
> Also, which tiling WM you are using?

I'm currently using DWM(suckless)

**Comment by jliljebl** [comment] 2021-01-30 11:50
We have had Issues with tiling window managers like Awesome not handling/emitting GTK events correctly. Can you try some other WM or DE? We need rule DWM out first.

**Comment by Haleycarl** [comment] 2021-01-30 12:09
I already tried using gnome which end up the same 
- GTK2 version 2.24.33-1
- GTK3 version 1:3.24.24-2

**Comment by Haleycarl** [comment] 2021-01-30 12:11
Source of install is from arch repo

**Comment by jliljebl** [comment] 2021-01-30 12:21
Well you do have a later version of GTK, I have 3.24.23. It is possible that GTK has broken the app on PATCH version level but I doubt it. That would be insane.

The reason why this happening is quite clear, *Gtk.Widget.has_focus()* for timeline widget is returning *False* after mouse click on your system when it should return *True* as it does on every other system.

I'm leaving this open for further info but I do not know how to fix this, the application is being provided wrong info by the platform and there is no patch to fix that.

**Comment by Haleycarl** [comment] 2021-01-31 23:08
When do you think it will be fixed?

**Comment by ony2020** [comment] 2021-02-04 17:20
the solution is to install Flatpak, I have similar problem on Manjaro when I installed it from the store.
once I installed it from flat-hub it worked flawlessly, it will download the appropriate version of gnome libraries and don't worry will not effect your system

**Comment by Haleycarl** [comment] 2021-02-05 00:12
I have a good news, flowblade-git package in AUR works properly with the keyboard shortcuts.

**Comment by Haleycarl** [comment] 2021-02-05 00:14
> the solution is to install Flatpak, I have similar problem on Manjaro when I installed it from the store.
> once I installed it from flat-hub it worked flawlessly, it will download the appropriate version of gnome libraries and don't worry will not effect your system

Thanks for the advice, when you said about Flatpak I remembered that there is an AUR version in Arch.

**Comment by jliljebl** [comment] 2021-02-07 18:46
Ok, great, closing this then.

**Closed** 2021-02-08 16:36 UTC
Labels: not an issue
