### ISSUE TITLE
Render proxy files using ffmpeg CLI with GPU encoding

### ISSUE THREAD

**Issue by wolfgangr** [jliljebl/flowblade#1120] opened 2023-10-04 06:57 UTC
I succeeded to tweak `renderencoding.xml` so that I can select `nvidia nvenc` **GPU rendering** for generating **proxies**.
(see here https://github.com/jliljebl/flowblade/issues/1035#issuecomment-1744613904)
However, it **takes 10 times as long** as with `ffmpeg` on console, using the same parameters.
I'm afraid that this is due to **mlt overhead**, so it's deeply woven into flowblade.

What approaches do we have to overcome this?

- is there some kind of "**close to** ffmpeg **metal**" config available **in mlt**?
- may I **screw flowblade** code (`FileRenderPlayer` in `renderconsumer.py`?) to be able to **bypass mlt** and **call ffmpeg directly**?
- may I generate a **initial project outside of flowblade** with (maybe precompressed) input videos, proxies and thumbnails and a .flb file in skd of **batch** skript?

My current preference is the last option.
I can convert the `pickle`d .flb to `yaml` which is readable by human and by PERL (sorry ;-) ....)
So I hope to go the way back and produce a prefilled initial project.

Any better ideas? 

---------------

Please include the following information.
1) Flowblade version (Help->About): 2.10/2.11
2) MLT version (Help->Runtime Environment): 7.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): debian 10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
see here: https://github.com/jliljebl/flowblade/issues/1035#issuecomment-1744613904

**Comment by jliljebl** [comment] 2023-10-04 12:08
Hi, seems a complex issue, and I don't have any immediate definite answers, but getting proxies rendered in GPU is certainly a worthy goal. I'll need to do some testing on my own to provide you with better answers, but here are some initial thoughts.

> However, it takes 10 times as long as with ffmpeg on console, using the same parameters.
I'm afraid that this is due to mlt overhead, so it's deeply woven into flowblade.

Basically, MLT should just pass provided parameters directly to ffmpeg call then some *now_render_it()* function, so in my view no 10x differences *can* be caused by MLT. My understanding is that MLT is not in pipeline after in starts rendering, ffmpeg encodes and writes results to disk without further MLT intervention. I will read to MLT code to confirm this view and comment here later. 

> What approaches do we have to overcome this?

    is there some kind of "close to ffmpeg metal" config available in mlt?

This should not be needed, see above.

> may I screw flowblade code (FileRenderPlayer in renderconsumer.py?) to be able to bypass mlt and call ffmpeg directly?

Correct approach is *not* to interfere with existing functionality, but copy *FileRenderPlayer* to something like *FileProxyRenderPlayer*, then make it so that the new class is used only for creating proxies, and then hack on the new class to see if improvement can be done. This the standard way to avoid regressions, add stuff on the side, don't change existing working stuff.

 >   may I generate a initial project outside of flowblade with (maybe precompressed) input videos, proxies and thumbnails and a .flb file in skd of batch skript?

This seems very hacky, we really should fix MLT if there is indeed some reason that it fails to use available GPU resources correctly.

I'll look into this and get back with more feedback on the weekend. Getting proxies rendered as fast as possible is an important performance issue, so I'll return to this.

**Comment by wolfgangr** [comment] 2023-10-04 21:46
I just try to get warm on github again ;-)
here you see my test `<proxyrenderoption>`s
https://github.com/wolfgangr/flowblade/commit/2fa8f5aca8205a127e31595d072a09e996a7f2ef

`name="H.264 NVENC fastest"` is the simplest, preferred for testing.
The others just add írrelvant complexity, imho; I could not see any difference in speed

**Comment by wolfgangr** [comment] 2023-10-04 22:11
I agree to **prefer integration in flowblade.**
Sad to say, I'm not fit in python nor your code structure neither UI programming.

Anyway .. my approach would be sth along this way:
- find a working command such as
 `ffmpeg -i somevideofile.mp4 -c:a aac -vf scale_npp=960:540 -c:v h264_nvenc -rc vbr -cq 28 -pix_fmt yuv420p somevideofile_h264_cq28_yuv420p.mp4`
- create a template from it, such as
 `<profile syscall="ffmpeg -i %INFILE% -c:a aac -vf scale_npp=%WIDTH%:%HEIGHT% -c:v h264_nvenc -rc vbr -cq %QUALITY% -pix_fmt yuv420p %OUTFILE% >`
 which matches the syntax of `renderencoding.xml`
- somewhere down the rabbit hole (`renderconsumer.py`?) check for a trigger (`syscall` clause in my example) to switch from `mlt` to `ffmpeg`direct rendering
- ... and call the alternative renderer with data required (e.g. INFILE, OUTFILE, WIDTH, HEIGHT; maybe QUALITY)
- .... which may reside (as class, I suppose?) in a separate module like `ffmpeg_bare_metal.py`, of course

**Comment by jliljebl** [comment] 2023-10-05 07:23
On second thought I *do* believe there can be 10x differences between MLT and ffmpeg when doing simple re-encoding. The issue is not encoding itself, it what happens between decode and encode.

We have something like this happening:

**ffmpeg**: decode -> resize -> encode

**MLT**: decode -> some processing -> resize -> some processing -> encode 

When doing a simple re-encode and resize MLT is going to do some additional work compared to ffmpeg that enables it achieve the functionality of a full blown video editor, whereas processing pipeline of *ffmpeg* is going to be much simpler, and *there would be no context switches and data copying between processes*. Hell, it is even possible that with *ffmpeg* the data never leaves GPU if the resize is a GPU filter also. That would really make the whole pipeline very fast.

I did a test, and yes, resize/re-encode really is blazing fast, didn't believe my eyes. Maybe not 10x, but 5x looked quite likely. 

> I agree to prefer integration in flowblade.
Sad to say, I'm not fit in python nor your code structure neither UI programming.

Absolutely, providing much faster proxy rendering as integrated part of the application is well worth looking into.

There interplay between jobs, proxy code, and rendering pipeline is not simple combination, but is absolutely needed to present user with an integrated UX.

>Anyway .. my approach would be sth along this way:

>  *    find a working command such as
    ffmpeg -i somevideofile.mp4 -c:a aac -vf scale_npp=960:540 -c:v h264_nvenc -rc vbr -cq 28 -pix_fmt yuv420p somevideofile_h264_cq28_yuv420p.mp4
>  * create a template from it, such as
    <profile syscall="ffmpeg -i %INFILE% -c:a aac -vf scale_npp=%WIDTH%:%HEIGHT% -c:v h264_nvenc -rc vbr -cq %QUALITY% -pix_fmt yuv420p %OUTFILE% >
    which matches the syntax of renderencoding.xml
>  * somewhere down the rabbit hole (renderconsumer.py?) check for a trigger (syscall clause in my example) to switch from mlt to ffmpegdirect rendering
>  * ... and call the alternative renderer with data required (e.g. INFILE, OUTFILE, WIDTH, HEIGHT; maybe QUALITY)
> * .... which may reside (as class, I suppose?) in a separate module like ffmpeg_bare_metal.py, of course

The correct approach is to have the data never enter MLT at all, but use Python **subprocess.Popen** with e.g. your *ffmpeg -i somevideofile.mp4 -c:a aac -vf scale_npp=960:540 -c:v h264_nvenc -rc vbr -cq 28 -pix_fmt yuv420p somevideofile_h264_cq28_yuv420p.mp4*

The only problem is how do I get the progress display working for user, but we even can omit that is that turns out be necessary. *ffmpeg* does display progress info on terminal, so it might be possible to tap into that, even if a bit hacky.

I'll add this into feature list. Doing this the right way within Flowblade will be a bit complex and require getting to know app code structure quite well, so I can do this myself. This very probably wont make the next release, but for the release after that I think we will get this if everything goes well.

**Comment by wolfgangr** [comment] 2023-10-05 08:56
maybe worth a look:
https://pypi.org/project/ffmpeg-python/
Python bindings for FFmpeg

**Comment by jliljebl** [comment] 2023-10-05 16:43
Thanks, looked at the bindings, but is does not look that they add value to us over *subprocess.Popen* with args.

**Comment by wolfgangr** [comment] 2023-10-05 20:21
agree.
I expected them to call right into the libs of ffmpeg, so this might ease your challenge of progress reporting.
But if they end up in simple .Popen,  that' just another layer of opacity and dependency.

I found another project using swig bindings of ffmpeg / libav libraries, but from a first glance, I don't see much of added value there, too.
https://github.com/avTranscoder/avTranscoder

**Comment by wolfgangr** [comment] 2023-10-05 22:37
I this the point where we had too hook in?

https://github.com/jliljebl/flowblade/blob/f109e8a8265e460aff4d8da4194f44c1fdbe7a07/flowblade-trunk/Flowblade/tools/proxyheadless.py#L73
`class ProxyClipRenderThread(threading.Thread):`

**Comment by jliljebl** [comment] 2023-10-06 11:14
I would do it differently. The *proxyheadless.py* is complex enough as is, so I would do this by creating another class doing the rendering. 

We also do not want to risk regressions by removing any existing proxy render options, instead we will add new one and implement that. I would do it roughly like this:

1. Add new items into *renderencoding.xml* with a new attribute to mark them as being rendered by ffmpeg with new attribute called e.g. 'ffmpeggpuenc', so maybe.

```
---
    <proxyencodingoption name="Apple ProRes 422 Proxy / .mov" extension="mov" type="av" audiodesc="pcm" resize="True" qgroup="not_settable">
        <profile args="f=mov acodec=pcm_s24le ac=2 vcodec=prores vprofile=0 vendor=ap10 pix_fmt=yuv422p10le" />
    </proxyencodingoption>
    <proxyencodingoption name="FFMPEG NVENC H.264  / .mp4" extension="mp4" type="av" audiodesc="pcm" resize="True" qgroup="not_settable"  ffmpeggpuenc="h264_nvenc ">
        <profile args="%SOURCEFILE -c:a aac -vf scale=%SCREENSIZE -c:v h264_nvenc -rc vbr -cq 28 -pix_fmt yuv420p %PROXYFILE "/>
    </proxyencodingoption>
    <proxyencodingoption name="VAAPI SOMETHING" ..." ffmpeggpuenc="vaapi">
        <profile args=".... "/>
    </proxyencodingoption>
```
Update *renderconsumer.EncodingOption* to use 'ffmpeggpuenc'.  

2. *rendergputest.py* runs tests on startup to determine if GPU rendering is available. Based on results filter out the *ffmpeg* GPU proxy render options not available on system. Typically we have either VAAPI or NVENC options working on a system.
3. *proxyediting.ProxyRenderItemData* and *proxyediting.ProxyRenderRunnerThread* probably don't need updating.
4. Next change *jobs.ProxyRenderJobQueueObject.start_render()* to optionally launch new rendering path based on *enc_index* value available there if *ffmpeg* rendering is used.
Use *self.render_data* (its a *proxyediting.ProxyRenderItemData* object) to do string substitutions for *%SOURCEFILE, %SCREENSIZE , %PROXYFILE* specified in *renderencoding.xml* to create the final ffmpeg command string.
5. Add to *renderconsumer* a new object that does the *subprocessPopen*. Object has to launch a thread and do blocking on that thread like to get completion information, like: 
```
self.completed = False
p = subprocess.Popen(...stuff...)
p.wait()
self.completed = True
```
 6. Update *jobs.ProxyRenderJobQueueObject._update_from_gui_thread()* to optionally do updates based new render object status because we are not using *proxyheadless.py* now.

This is just rough outline, in practice there could be some additional complications. But I have to say I don't want additional complexity in *proxyheadless.py*, it does the MLT rendering thing it is designed to do and doing *ffmpeg* rendering needs to be on a different code path.

If you want to give this a a go I can wait for a pull request. It would not be completely straight forward, but probably not super complex either.

**Comment by jliljebl** [comment] 2023-10-17 16:05
@wolfgangr I'll start working on this, should not be too difficult to get into next release.

**Comment by jliljebl** [comment] 2023-10-18 08:31
Ok, this is master now. We are getting atleast 5x speedups. I don't have VAAPI supporting card, so now I only have NVENC proxy render option. If anyone has VAAPI card and can test HEAD and add VAAPI proxy encoding option in *renderencoding.xml* that would be great.

**Comment by Disaster2life** [comment] 2023-10-18 10:19
I have an AMD gpu, Ill try and follow the thread and run a test for it later in the evening for the VAAPI proxy render

**Comment by jliljebl** [comment] 2023-10-18 13:24
Try:
1) Add the following XML snippet as last item in file *renderencoding.xml*.

```
<proxyencodingoption name="FFMPEG VAAPI H.264  / .mp4" extension="mp4" type="av" audiodesc="pcm" resize="True" qgroup="not_settable" ffmpeggpuenc="h264_vaapi">
        <profile args="%SOURCEFILE -vaapi_device /dev/dri/renderD128 -vf 'format=nv12,hwupload' scale=%SCREENSIZE -c:v %PROXYFILE"/>
    </proxyencodingoption>
```

2) Open from app menu *Project->Proxy Manger*

3) The *FFMPEG VAAPI H.264  / .mp4* option should be selectable from combobox(dropdown menu)  in *Proxy Encoding* panel.

4) Select that and try to render a proxy file.

**Comment by Disaster2life** [comment] 2023-10-18 17:50
Couldn't get the development Flowblade to not quit after startup, so I can't try this right now, but I'll file a bug on why it's not working tomorrow, hopefully this can be in the project real soon.

**Comment by Disaster2life** [comment] 2023-10-23 17:46
Finally was able to try this out, just tried to transcode a personal "big" mpeg video clip I had lying around from an av1 video I had to get something out of, and on the CPU it took about a minute and a half while on the GPU it reported taking a fraction of a second, ... I use reported because I am on wayland, the monitor didn't work, so I couldn't playback the clip (though the audio seemed to work) and when I switched to using proxy clips, Flowblade just dropped all my video layers, I think for that I should open another issue, but at least transcoding worked super well, it took such little GPU time that I couldn't exactly spot a spike on radeontop, which has me a bit suspicious, I'll hopefully pull myself to boot into x11 and try to see if the transcoding works properly.

**Comment by jliljebl** [comment] 2023-10-24 07:40
Ok, thanks I'll add the VAAPI transcoding option into repo. I hope to Wayland system running sometime in near future to test Wayland myself.

**Comment by jliljebl** [comment] 2023-11-13 18:40
I got the VAAPI proxy encoding working and tested on system with VAAPi instead of NVENC. Feature will be in 2.12.

**Closed by jliljebl** 2023-11-13 18:40 UTC
Labels: in feature queue
