### ISSUE TITLE
frequent crashes when splicing

### ISSUE THREAD

**Issue by notklaatu** [jliljebl/flowblade#163] opened 2015-09-30 08:13 UTC
I'm cutting some footage. It's been going swimmingly for most of the edit, but with some clips, Flowblade freezes up if I cut too frequently.

When launched from a terminal, this is the output I get at the time of the crash:

<pre>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/Flowblade/cairoarea.py", line 113, in _enter_notify_event
    self.enter_notify_func(event)
  File "/usr/lib64/python2.7/site-packages/Flowblade/editorwindow.py", line 1011, in tline_cursor_enter
    self.set_cursor_to_mode()
  File "/usr/lib64/python2.7/site-packages/Flowblade/editorwindow.py", line 944, in set_cursor_to_mode
    self.set_tline_cursor(editorstate.EDIT_MODE())
  File "/usr/lib64/python2.7/site-packages/Flowblade/editorwindow.py", line 954, in set_tline_cursor
    cursor = Gdk.Cursor.new_from_surface(display, INSERTMOVE_CURSOR, 0, 0)
AttributeError: type object 'Cursor' has no attribute 'new_from_surface'
</pre>

What is happening, exactly, is that I make some cuts, and then play. The first few cuts play fine, but the playhead stops at one splice and simply refuses to continue. The only way to recover is to kill Flowblade; this zombifies it, so I have to kill -9 `pgrep flowblade` to fully recover.

This was happening on 0.18, so I switched to a git pull 30 September; same issue.
OS: Slackware 14.1

**Comment by notklaatu** [comment] 2015-09-30 08:14
![flowcrash](https://cloud.githubusercontent.com/assets/2211671/10187929/29f64f20-67b8-11e5-8a9e-c339a95cc56d.png)

**Comment by jliljebl** [comment] 2015-09-30 08:39
Thanks for filing, this actually seems very much like application bug, so no gdb needed for this. 

This line:

  File "/usr/lib64/python2.7/site-packages/Flowblade/cairoarea.py", line 113, in _enter_notify_event
    self.enter_notify_func(event)

means that bug happens as a result for mouse moving into the timeline area from outside. If this happens during playback I think you're pressing play button (or space) and after that moving mouse pointer into the timeline area.

Does 1) moving mouse pointer quickly in and out of timeline area or 2) completely keeping it away from it make a difference to the crashes appearing?

**Comment by jliljebl** [comment] 2015-10-21 09:37
Hi notklaatu,

Does installing package 'python-gi-cairo' (or similar) on your system fix the issue, see here: https://github.com/jflesch/paperwork/issues/283  ?

**Comment by jliljebl** [comment] 2015-10-21 09:50
My current theory on this is that on some systems like Ubuntu 14.04 and earlier package 'python-cairo' (that the 1.2 .deb this project distributes depends on) does not pull in all needed dependencies and package 'python-gi-cairo' needs to be installed manually. Ubuntus 14.10 and later pull everything needed with just installing  'python-cairo'.

The proposed fix for Ubuntu 14.04 is to do 'sudo apt-get install python-gi-cairo'. Please comment here on results of this proposed solution.

**Comment by jliljebl** [comment] 2015-10-21 10:00
It seems that this may actually be a different problem. Function 'Gdk.Cursor.new_from_surface' has only been available from GTK version 3.10 onwards, so Flowblade version 1.2 and onwards require version 3.10 of GTK.

**Comment by jliljebl** [comment] 2015-11-05 17:21
I'm closing this as the problem is very likely caused by available GTK library in the system and therefore not a Flowblade bug. Ubuntu 14.04 or OpenSUSE are not supported anymore.

**Closed by jliljebl** 2015-11-05 17:21 UTC
Labels: invalid, wontfix
