### ISSUE TITLE
dark theme doesn't apply with all desktop environments.

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#144] opened 2015-08-03 20:31 UTC
in gnome and cinnamon it works fine, but when i try it with mate and pekwm only the light theme works. (even after restarting.)

**Comment by jliljebl** [comment] 2015-08-10 20:24
I'm working on improving the dark theme support and will comment on this more after that work is completed.

**Comment by faridosc** [comment] 2015-08-14 17:01
just built flowblade and saw that you added a new feature to the view panel... eitherway i can't seem to change to the dark theme anymore on cinnamon. also the buttons can't be changed.

**Comment by jliljebl** [comment] 2015-08-14 17:38
Ok, will try to see what's problem next week, might caused a bug with last
commits.

**Comment by jliljebl** [comment] 2015-08-19 21:21
This maybe caused by me doing updates to prefs that cause prefs to not be loaded correctly. Does deleting hidden file <YOUR_HOME_FOLDER/.flowblade/prefs help?

**Comment by faridosc** [comment] 2015-08-19 21:31
nope nothing changed,

i tried it on two machines, one running gnome and the other cinnamon. (both 64bit archlinux)

cheers

**Comment by jliljebl** [comment] 2015-08-19 21:40
Hmm, this may take a while, I'm in "works on my system" state now, so I will probably need to test on Virtual Box to which is always a hassle.

Does terminal  command: _ GTK_THEME=Adwaita:dark ./flowblade_ in your repository folder that has the start-up script do anything useful?

**Comment by faridosc** [comment] 2015-08-19 21:46
running GTK_THEME=Adwaita:dark flowblade does start with the dark theme.

**Comment by jliljebl** [comment] 2015-08-19 22:01
My current understanding is that from with in the application you can request a dark variant of the theme the user is using, but if the theme does not have dark variant then this request does nothing. I haven't yet this request and will post here once that is done.

Are there any other problems, can you select the from Edit->Preferences "Icons and Colors.." = "Dark Theme" and does the "Theme detection fail fallback..." thing have effect? With dark theme the button option does not have effect and I should probably disable it when dark theme selected

**Comment by faridosc** [comment] 2015-08-19 22:10
from the preferences i change the button to simple, the theme to dark and tried all the variants and nothing changes... also don't know if it helps but also i have the arc theme installed.

i think i found the issue though, under gnome using gnome-weak-tool if i turn on the dark global theme option, then i can get the dark theme in flowblade after setting it in the preferences. the solution should be irrelevant of having the global dark theme turned on or not.

**Comment by jliljebl** [comment] 2015-08-19 22:45
I added the GTK dark theme request and it worked here with Adwaita which has Dark theme, but not with Ambient which does not. Can you pull from repository and test?

**Comment by faridosc** [comment] 2015-08-20 13:06
i kind of works, but flowblade starts in a different language, and even when choosing to make it in english that language stays the same. i am wild guessing that it is your system language...

**Comment by jliljebl** [comment] 2015-08-20 13:58
Heh, yes, I had Finnish hard coded for testing and that got pushed. I'm working on the issue with translations and the translations may be off for a while. I pushed a patch that removes hard coded Finnish.

 I'm closing this as dark theme is now supposed to work, comment if more problems arise.

**Closed by jliljebl** 2015-08-20 13:58 UTC

**Comment by faridosc** [comment] 2015-08-20 14:17
it works now. just a suggestion, since you have to restart to the settings to apply, maybe the program could have a popup with a restart button.

**Comment by jliljebl** [comment] 2015-08-20 14:21
Yeah, restart button could be useful.
