### ISSUE TITLE
Muting A2 silences A1

### ISSUE THREAD

**Issue by tenleftfingers** [jliljebl/flowblade#362] opened 2017-03-26 18:43 UTC
I have vocal on A1 and music on A2. 

if I mute A2, I cannot hear A1 anymore. The GUI shows A1 as not muted.
If I mute A1, A2 still plays correctly.

1.12 on Ubuntu 16.04 64-bit. Logs etc available on request.

**Comment by jliljebl** [comment] 2017-03-27 05:30
Ok, this is the second report of this...but I still can't reproduce it. The cause has to have some non-obvious causes that are not present in all systems.

Are you using some other audio system than PulseAudio?

**Comment by jliljebl** [comment] 2017-03-27 05:32
This is the other report: https://github.com/jliljebl/flowblade/issues/234.

**Comment by tenleftfingers** [comment] 2017-03-27 07:49
I didn't see the other thread, apologies. I'm using Pulseaudio, the default with Ubuntu. I do have Jack installed but not running. Happy to provide any logs, video, or filesystem archives that will help.

**Comment by jliljebl** [comment] 2017-03-27 09:43
Do different Project Profiles or audio file types make any difference?

**Comment by empee0** [comment] 2017-03-27 10:14
Same issue here on Ubuntu 16.10 and Debian 8 (both master and pulseaudio)

**Comment by jliljebl** [comment] 2017-03-27 10:29
Saving and opening a project with mutes set didn't make this happen here. I thought that might be possible because the mute system gets created on load, but no, still working correctly here.

If you give command:

    cat /proc/asound/cards

...what do you get? I got:

 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xc1310000 irq 51
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xc1314000 irq 50
 2 [S150           ]: USB-Audio - SteelSeries Siberia 150
                      SteelSeries SteelSeries Siberia 150 at usb-0000:00:14.0-3, full speed

**Comment by tenleftfingers** [comment] 2017-03-27 10:43
Correct, it's not related to saving. I didn't even save the project - I ran into this issue immediately.

cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                           HDA Intel PCH at 0xd4720000 irq 32

**Comment by ahangarha** [comment] 2017-04-05 15:28
I also don't face with this problem. Otherwise I could help for solution.
Which version do you use?

**Comment by tenleftfingers** [comment] 2017-04-06 09:23
Strange. Still same version as above: Ubuntu 16.04 with FlowBlade 1.12. Maybe I should zip up my project and share it with you to see if you can reproduce that way.

**Comment by jliljebl** [comment] 2017-04-06 11:15
@tenleftfingers Yes, it would be useful to make sure that there are no structural differences in the created projects.

So if you could:
- make a small project with video and audio and mutes set so that the problem is present
- do "Save Backup Snapshot", archive the created folder and make it available for download somewhere

I'm not sure if you can attach such data here, so you might need to give a Dropbox link or something

**Comment by tenleftfingers** [comment] 2017-04-12 13:27
I can't find my original project. It must have been deleted. I'll be starting a new project in the coming weeks. If it's possible to leave this report open I'll update it with the result.

**Comment by jliljebl** [comment] 2017-04-13 09:09
I'll keep the report open until issue is understood, something is going on here.

**Comment by dvdlvr** [comment] 2017-04-15 08:31
I can reproduce this problem on my system, using the latest version from github.

cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7a00000 irq 35
 1 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xf7080000 irq 17

Project file can be found here:
https://www.dropbox.com/s/qsfwnq123hlpbfc/Flowblade-A2.tar.gz?dl=0

**Comment by jliljebl** [comment] 2017-05-14 10:02
Allright, this project file DOES reproduce the issue. Sorry for the long reaction time, I somehow missed this and haven't super active lately.

**Comment by jliljebl** [comment] 2017-09-20 10:43
This is unfortunately going for 1.16. Fixing this may break project files and cannot be attempted this late in the cycle.

**Comment by jliljebl** [comment] 2018-03-28 08:12
Fixed, will be in 1.16.

**Closed by jliljebl** 2018-03-28 08:12 UTC
Labels: bug
