### ISSUE TITLE
Crash when changing alpha mode of Dissolve compositor

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#205] opened 2016-02-13 23:17 UTC
**Steps to reproduce:**
1. Insert a video on V1.
2. Insert a full-frame PNG with transparency (watermark) on V2.
3. Change Alpha mode from _over_ to anything else.
4. Flowblade unresponsive then crash.

**Comment by jliljebl** [comment] 2016-02-17 08:46
Confirmed. This is an MLT bug, so the fix hitting Linux repos will take awhile.

**Comment by jliljebl** [comment] 2016-02-17 08:52
There exists a workaround for the time being:

*Crash only happens if playhead is on a frame affected by the Dissolve compositor*, so moving playhead of the area of the dissolve compositor makes possible to change alpha modes.

**Comment by jliljebl** [comment] 2016-02-17 09:26
This has been "fixed" by removing the alpha mode functionality from compositors. It is more important to have solid "over" compositing then to provide an illusion of functionality by making possible to select broken options.

Functionality may be re-activated once: a) problem has been fixed in MLT, b) the fix is widely available in Linux repos.

I'm leaving this open for the time being so that the information here is more visible.

**Comment by AGI-THB** [comment] 2016-09-22 18:38
Can you check if it has been fixed by now?

[click here](https://github.com/mltframework/mlt/commit/f6cdcb8709393ace6d3be316dddaff67e678ee6c)

[click here 2](https://github.com/mltframework/shotcut/issues/304)

**Comment by jliljebl** [comment] 2016-09-22 19:51
Thanks for info, the second link seems to be the fix for this.

I won't be reactivating this feature until the fix hits the Ubuntu repos.

I'm currently in heavy application development mode and I prefer to do that against vanilla Ubuntu 16.04 environment, so I wont install repo MLT now, but if Dan says it is fixed it very likely is.

**Comment by jliljebl** [comment] 2017-07-26 07:57
The alpha mode is not coming back in the short to medium term, closing this as *wontfix*. If alpha mode is to be reactivated it will be as a new feature.

**Closed by jliljebl** 2017-07-26 07:57 UTC
Labels: bug, wontfix
