### ISSUE TITLE
Issue: Blend compositor does not work with video clips without alpha

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#541] opened 2018-08-18 20:44 UTC
Flowblade version (Help->About): 1.16.0
MLT version (Help->Runtime Environment): 6.8.0
Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

I add two video clips, add a Blend compositor between them, change Opacity and nothing changes. I select a blend mode and nothing changes. The only way to actually make it work is to add an alpha effect, such as "Alpha modify" to the top clip. I don't think it is the intended behaviour.

**Comment by jliljebl** [comment] 2018-08-21 10:47
This does not reproduce here. There was an issue with Blend with ->1.16 because upstream broke us once again, but patch https://github.com/jliljebl/flowblade/commit/c5dba8bb8c6b2641007d34f1914f5024b6daddac fixed that, so I'm assuming for now that this was fixed with that too.

i'm leaving this open for further clarification.

**Comment by jliljebl** [comment] 2019-02-18 13:17
Is this still happenig with 2.0?

**Comment by jliljebl** [comment] 2019-09-27 07:09
No new info to direct investigation and this really does not happen here, closing.

**Closed by jliljebl** 2019-09-27 07:09 UTC
Labels: unreproduced

**Comment by Efenstor** [comment] 2020-02-10 09:35
Sorry for the late reply: the problem is fixed! It's all fine in v2.0.
