### ISSUE TITLE
Undefined constant or missing '(' in 'dct8x8'

### ISSUE THREAD

**Issue by denjello** [jliljebl/flowblade#116] opened 2015-06-08 15:04 UTC
I was getting a few errors (and render crash) when using the lossless h264 render format. 
(i am using 0.18)

```
[libx264 @ 0x7f1f64809a40] [Eval @ 0x7f1f69335140] Undefined constant or missing '(' in 'dct8x8'
[libx264 @ 0x7f1f64809a40] Unable to parse option value "dct8x8+mixed_refs"
[aac @ 0x7f1ff55af9a0] [Eval @ 0x7f1f693350f0] Undefined constant or missing '(' in 'dct8x8'
[aac @ 0x7f1ff55af9a0] Unable to parse option value "dct8x8+mixed_refs"
```

I deleted that line in the renderargs and it stopped throwing errors. Probably not the most elegant fix, but ffmpeg stopped complaining.

**Comment by jliljebl** [comment] 2015-06-14 21:34
Confirmed. I need to see what the arg is about, but if it does not recognize it, I can probably just delete it like you did, because it does not do anything.

**Comment by jliljebl** [comment] 2015-08-12 15:28
Fixed in repository.

**Closed by jliljebl** 2015-08-12 15:28 UTC
Labels: bug
