### ISSUE TITLE
editing takes keyboard prisoner from filenames and other input fields

### ISSUE THREAD

**Issue by grinapo** [jliljebl/flowblade#411] opened 2017-06-17 10:00 UTC
I wonder why this isn't in the FAQ or the docs since seems to be always the first problem of mine with flowblade: while editing the keyboard is bound to keyboard shortcuts even in the input fields, so for example I cannot rename "sequence_1" to "what2" since "t" and "2" is bound to editing feature shortcuts. There seem to be no obvious way to release edit mode (or to actually get my keys back for input).
I can live with that but beginners may get bitten hard, considering they actually activate a lots of "unknown" functions in the backgound (fox => sets out mark and cut sequence) while trying to type a filename.

**Comment by jliljebl** [comment] 2017-06-17 10:27
What the hell, this is absolutely not the case. These keys are only used as timeline shortcuts when timeline has keyboard focus. If you click on "sequence_1" with mouse it now has the keyboard focus and you can absolutely use all keys anter text.

I'm using 1.12 +git and Gnome Shell on Ubuntu 17.04 and this is not the case here nor has it ever been on any of my development systems.

Which desktop environment and distro you are using?
Which version of the Flowblade you are using?

**Comment by grinapo** [comment] 2017-06-20 17:31
Believe me, I would happily agree with you, but I can't, since this is what repeatedly happening. I have tried to figure out what happens, since _sometimes_ they work. It seems that when I can switch the focus between input fields (however stupid this sounds) it releases the keys, but it's really hard to see the specific behaviour. Definitely the keys are captured wen renamind whatever (bins, sequences, media, ...).

This is xfce4 v4.12 (debian/sid), the wm is xfce4's own xfwm4.
Flowblade is v1.12.0 (debian packaged).

I will gladly make you any test which may help (within my time limits).

For example, I started a new FB, and went to timeline (click on it), press 1, 2, cursor changes. Then I move over to bins, 1, 2 and the cursor changes (I'm not sure what should happen: the timeline was clicked last but the mouse moved off the box), and stays the same when mousing around bins, media or the range log window. Still, I can enter a filename. 

YES, **I believe I got it now:** when I start a movie clip in the **monitor** the keys stay captured everywhere, even after stopping the playback. I cannot get back my keys until I cut the clip (and change the timeline cursor), for example, while the monitor is stopped. Anything I do to the monitor (even next frame) captures the keyboard again.

**Comment by jliljebl** [comment] 2017-06-21 20:20
OK  thanks, with additional information I will try reproduce,  not at home
currently,  may take a bit.

20.6.2017 7.31 ip. "Peter Gervai" <notifications@github.com> kirjoitti:

**Comment by jliljebl** [comment] 2017-07-26 07:50
Ok, I still can't reproduce. It should be noted that keyboard focus STAYS in timeline until you click with mouse somewhere else.

What happens if you do:

1) Put something on timeline so monitor has image displayed
2) Click on play button and then monitor stop button
3) Press 1, 2, 3 the tool changes if mouse is on top of timeline, This is how it is supposed to be.
4) Click on "bin_1" text and start inputting text. 1, 2, 3 etc. now output text.

Do you experience something different?

Could post a similar step-by-step guide on how you get the problem as the one above?

**Comment by Efenstor** [comment] 2017-08-07 11:06
There is no such problem in Mate. Possibly it's only in Xfce.

**Comment by grinapo** [comment] 2017-08-09 20:36
@jliljebl 4. doesn't output text, it changes the mouse.

**Comment by grinapo** [comment] 2017-08-09 20:38
If I am at that state, and click on view mode in the lower right corner of monitor, then select basically anything, then I get my keyboard back, and I can type into bin_1 again, until I start monitor by play.

**Comment by jliljebl** [comment] 2017-08-10 08:40
So far seems that xfce may have issues with keyboard focus handling, @grinapo if you have some other desktop environment on your system you  could test if the issue is xfce specific.

**Comment by ohli** [comment] 2017-09-04 19:41
Hi, same here.
I'm using flowblade 1.12 with i3wm and got the same issue (all other programs work).
It only occurs when **using the 2-window mode** and can only be set back by using grinapo's method.
@grinapo can you approve that this only occurs in 2-window mode? Thanks.
@jliljebl if you need sth else, tell me (impressive work, btw 👍 )

**Comment by jliljebl** [comment] 2017-09-05 08:24
Confirmed for 2 window mode, needs fixing. 

When adding this it seems I was just concerned that shortcuts still worked, and failed to test that my global key event listener also needs to  stop eating every key press on window 1. Bugs happen more easily on features that are not part of my regular work flow, so thanks for nice words and pointing out the difference to my work flow.

**Comment by jliljebl** [comment] 2017-09-06 09:27
Fixed in repo, will be oin 1.14.

The problem was that I was using *is_focus()* function that only gives focus component within a top level window. As soon as I added a second top level  window I needed to start using *has_focus()* function (as the patch does) which gives the global focus component across multiple top level windows.

**Closed by jliljebl** 2017-09-06 09:27 UTC
Labels: fixed

**Comment by Efenstor** [comment] 2017-09-08 11:16
After applying this fix all the shortcuts ceased to work for me, and clicking Edit > Keyboard Shortcuts did not evoke any window. I have deleted the $HOME/.flowblade directory and it fixed the issue (though I suppose deleting $HOME/.flowblade/prefs would be enough).

**Comment by jliljebl** [comment] 2017-09-08 12:04
Ok, thanks a lot, this didn't happen to me. I need to figure this out before doing a release, its actually a really surprising error and has makings of major a catastrophe for next release.

**Comment by jliljebl** [comment] 2017-09-11 17:01
Tested 1.12 -> 1.14(beta) upgrade and it worked fine. Your problem was likely because of  the default value for pref I changed here: https://github.com/jliljebl/flowblade/commit/221084a1c449a74c1d509ed9acf5842d96cff1e5

Users installing 1.14 should not experience this problem.

**Comment by grinapo** [comment] 2017-09-13 18:36
@jliljebl do you have a tentative plan about release dates? (1.14) The question is whether debian-multimedia should patch it or wait for the release. Thanks!

**Comment by jliljebl** [comment] 2017-09-14 08:05
The current target is 25 September 2017.
