### ISSUE TITLE
Error in "Add Media Folder..."

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#935] opened 2020-11-17 17:06 UTC
commit 5a8670f284d4f1585fdac598b2cc259226853383
Flowblade crashes when trying to add a folder with media.

The output terminal:
(flowblade:37217): Gdk-ERROR **: 19:53:03.803: The program 'flowblade' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 155970 error_code 143 request_code 139 (RENDER) minor_code 7)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trap trace/breakpoint (the stack memory is flushed to disk)

**Comment by jliljebl** [comment] 2020-11-17 17:15
Ok, thanks. You had Fedora 33, if I remember correctly? 

This is not visible on my system but I will try to reproduce with virtual machine once i get around after adding the couple more features i still have for coming for this cycle.

**Comment by smolnp** [comment] 2020-11-17 17:30
Yes Fedora 33 (KDE Plasma)

**Comment by jliljebl** [comment] 2021-01-09 18:58
I tested this with Linux Mint 20 (Mate) and Fedora 33(Gnome) on VMs and it worked on both just fine. This is either some system related issue particular to one single system or Fedora 33 (KDE Plasma) issue,.  I'm closing this as *unreproduced* because this works on multiple tested systems.

**Comment by smolnp** [comment] 2021-01-17 17:20
I do not understand what is going on. First, I launched the English version, the multimedia folder was added correctly, then I tried the Russian version, the multimedia folder was added again without problems. I tried again, now neither the English version nor the Russian version want to copy the media files and Flowblade freezes.
This is a very strange and difficult to reproduce error.
I made a video from the screen: https://youtu.be/HHoiG_8jw7A
I waited for three minutes, but nothing happened. Flowblade just froze.
Sometimes Flowblade crashes after a short freeze, sometimes it has to be closed forcibly.
(Fedora 33 Cinnamon)

**Comment by jliljebl** [comment] 2021-01-18 16:07
Ok I have an idea. We are doing stuff like *os.walk(add_folder)* in GTK callback while holding GDK lock and this could be unstable if operation takes too long as some other GTK updates could be requested. I'll move the stuff into thread to return quickly and after you can try if stability has improved.

**Comment by jliljebl** [comment] 2021-01-18 17:47
Oh, it is crashing here now too. I tried multiple ways of doing this but it is crashing in an unusual way even if I'm in my view doing everything correctly with GDK lock.

I'm dropping feature from this release and re-open the feature request.

**Comment by jliljebl** [comment] 2021-01-18 21:11
Closing this one as we have this feature as new Issue. I will retry this in next cycle, the problems might take some time to figure out.

**Closed by jliljebl** 2021-01-18 21:11 UTC
