### ISSUE TITLE
Titler don't work!

### ISSUE THREAD

**Issue by osha-p** [jliljebl/flowblade#417] opened 2017-07-01 08:02 UTC
flowblade 1.12.0 archlinux x86_64 
When I run Titler a video instead of a grey background and nothing more. In the window I pressed all available buttons but nothing changed. What should I do?

![2017-07-01-105809_1920x1080_scrot](https://user-images.githubusercontent.com/21018863/27760280-36b819b4-5e4c-11e7-90df-1716d53ce333.png)

**Comment by jliljebl** [comment] 2017-07-01 12:12
Start Flowblade from terminal with command 'flowblade' and go to Titler and
post the terminal print out here so we can see the
possible errors. This does not reproduce on my system.

1.7.2017 11.02 ap. "osha-p" <notifications@github.com> kirjoitti:

**Comment by osha-p** [comment] 2017-07-02 03:41
I did. This is what I see in the terminal:
...
MLT detection succeeded, 156 formats, 96 video codecs and 68 audio codecs found.
529 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too low for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron found
Player initialized with profile:  HD 720p 23.98 fps
Selected color NOT detected
BG color detected
Autosave started...
Save project autosave_e17e22e4febc7b94ad29f20c0d97d874
Traceback (most recent call last):
  File "/usr/share/pyshared/Flowblade/cairoarea.py", line 81, in _draw_event
    self._draw_func(None, cr, (a.x, a.y, a.width, a.height)) # 'None' is event 
object that was used to pass through here. Can be removed.
  File "/usr/share/pyshared/Flowblade/vieweditor/vieweditor.py", line 214, in 
_draw
    if self.bg_buf != None:
ValueError: The truth value of an array with more than one element is ambiguous. 
Use a.any() or a.all()
Traceback (most recent call last):
  File "/usr/share/pyshared/Flowblade/cairoarea.py", line 81, in _draw_event
    self._draw_func(None, cr, (a.x, a.y, a.width, a.height)) # 'None' is event 
object that was used to pass through here. Can be removed.
  File "/usr/share/pyshared/Flowblade/vieweditor/vieweditor.py", line 214, in 
_draw
    if self.bg_buf != None:
ValueError: The truth value of an array with more than one element is ambiguous. 
Use a.any() or a.all()
Traceback (most recent call last):
  File "/usr/share/pyshared/Flowblade/cairoarea.py", line 81, in _draw_event
    self._draw_func(None, cr, (a.x, a.y, a.width, a.height)) # 'None' is event 
object that was used to pass through here. Can be removed.
  File "/usr/share/pyshared/Flowblade/vieweditor/vieweditor.py", line 214, in 
_draw
    if self.bg_buf != None:
ValueError: The truth value of an array with more than one element is ambiguous. 
Use a.any() or a.all()
Save project autosave_e17e22e4febc7b94ad29f20c0d97d874
Exiting app...

**Comment by jliljebl** [comment] 2017-07-02 07:48
I'm getting none of this. Are you using some some Python 3 version of numpy?

2.7.2017 6.41 ap. "osha-p" <notifications@github.com> kirjoitti:

**Comment by osha-p** [comment] 2017-07-02 08:51
No, I use python2-numpy v 1.13.0-1 What I should to do?

**Comment by jliljebl** [comment] 2017-07-02 09:07
I don't know, I do not understand or reproduce the issue. I'll look at this more after I end my summer break.

**Comment by osha-p** [comment] 2017-07-02 10:10
all dependencies installed. Don't even know where to look for the cause.With impatience I shall wait for the decision. Thank you.

**Comment by osha-p** [comment] 2017-07-02 12:39
I tested the titler, the package from AUR does not work on x64 archlinux. Neither archlinux nor on manjaro linux. Both the primary and the git version.

**Comment by Efenstor** [comment] 2017-07-02 13:13
**osha-p**, did you try the trunk version (git clone https://github.com/jliljebl/flowblade.git)? What is your version of libcairo? Looks like a problem with libcairo to me, especially considering the errors.

**Comment by osha-p** [comment] 2017-07-03 03:42
I use python-cairo 1.13.3-1, cairo 1.14.10-1 and lib32-cairo 1.14.6-2. Yes I tried git version but this leads to the same errors with different distributives based on archlinux.

**Comment by jliljebl** [comment] 2017-07-26 08:18
Ok, I think this is a numpy problem, not cairo problem. The error message is numpy trying to compare array *values* not the object to None.

I have earlier version *numpy 1.12.1* so the behaviour may have changed.

Because I can't reproduce I can't test this but could some one edit the *vieweditor.py* file and change line 214 from:

    if self.bg_buf != None:

to:

    if self.bg_buf is not None:

and see if this helps.

**Comment by osha-p** [comment] 2017-07-26 17:33
@jliljebl  Finely! I do that and It's work very well! I'm so happy! Thankyou!

**Comment by jliljebl** [comment] 2017-07-26 17:37
Thanks, I will fix this in repo next.

**Comment by jliljebl** [comment] 2017-07-26 18:12
Fixed in repo, will be 1.14.

These kind of upstream changes are *really* bad for app developers.

**Closed by jliljebl** 2017-07-26 18:12 UTC
Labels: fixed

**Comment by Zabbel** [comment] 2022-12-12 19:40
I have to reactivate this issue.... I've got the same here now on 2.8.0.2.....

MLT detection succeeded, 180 formats, 117 video codecs and 81 audio codecs found.
650 MLT services found.
Loading render profiles...
Loading filters...
Loading transitions...
MLT transition region not found.
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Selected color NOT detected
BG color detected
Create SDL1 consumer...
Launching io.github.jliljebl.Flowblade dbus service
Autosave started...
Saving project...
No user folders actions needed.
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 864, in <lambda>
    ('Titler', None, _('Titler'), None, None, lambda a:titler.show_titler()),
  File "/usr/share/flowblade/Flowblade/tools/titler.py", line 97, in show_titler
    _titler.show_current_frame()
  File "/usr/share/flowblade/Flowblade/tools/titler.py", line 666, in show_current_frame
    rgbdata = PLAYER().seek_and_get_rgb_frame(frame)
  File "/usr/share/flowblade/Flowblade/mltplayer.py", line 284, in seek_and_get_rgb_frame
    rgb = frame.get_image(int(mlt.mlt_image_rgb24a), int(self.profile.width()), int(self.profile.height()))
AttributeError: module 'mlt7' has no attribute 'mlt_image_rgb24a'. Did you mean: 'mlt_image_rgba'?

What more information do you need?

Thank you...
