### ISSUE TITLE
Proxy files are always garbled

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#381] opened 2017-05-16 13:20 UTC
Here is the screencast of what I do and how it looks: https://youtu.be/IG8_nooZAHs. It is no matter whether I use MPEG-4 or MPEG-2 for proxy. The source files are AVC, 2K and 4K. I assume it's the problem with the H.264 decoder used for making proxy files, as all of the video players on my system play the same source files perfectly, but play the proxy files made with Flowblade with exactly the same artifacts in the same places.

Flowblade version is 1.12.2. I use the deb-multimedia.org build but it is not the reason as I tried the official build and the problem was there. My system is Debian Linux Stretch x64. My video card is Radeon R7 240, using the free drivers. GStreamer version is 1.10.4 (if that matters).

**Comment by jliljebl** [comment] 2017-05-17 09:03
Ok, so I'm unable to reproduce here, we need to find the meaningful differences at play.

Which MLT version you are using, it shows it if you select 'Help-Runtime environment'? I have MLT 6.2.0.

if you give command 'ffmpeg' it prints info on library versions, I get:
---
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
----
What do you get?

**Comment by Efenstor** [comment] 2017-05-17 11:03
Thanks for the prompt reply!
My MLT version is 6.4.1 (from the deb-multimedia.org repos), and here is the output of FFMPEG:

  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100

**Comment by Efenstor** [comment] 2017-05-25 14:54
So any change of fixing this? I'm in desperate need of proxies as my footage is almost completely 4K.

**Comment by jliljebl** [comment] 2017-05-25 15:18
Have not been working on project in the past week.

You can do 2 things now:

1) Start application from terminal with command 'flowblade', then go through your proxy workflow and if you get an error message, post full output here.

2) Find from your system file 'renderencoding.xml' which is installed as part of Flowblade, path is ../<flowblade_install_root>/res/render/renderencoding.xml

In this file there are lines:

    
    <proxyencodingoption name="MPEG-4 Preset Ultrafast" extension="mp4" type="av" audiodesc="mp2, 192kb/s, 48000Hz" resize="True" qgroup="qgroup1">
        <profile args="f=mp4 acodec=mp2 ab=192k ar=48000 vcodec=mpeg4 preset=ultrafast"/>
    </proxyencodingoption>
    <proxyencodingoption name="MPEG-2 Transport Stream" audiodesc="mp2, 384kb/s, 48000Hz"  extension="m2t" type="av" resize="True" qgroup="qgroup1">
       <profile args="f=mpegts acodec=libmp3lame ac=2 ab=128k ar=48000 vcodec=mpeg2video g=5" />
   </proxyencodingoption>

Try to change  e.g. line "<profile args="f=mp4 acodec=mp2 ab=192k ar=48000 vcodec=mpeg4 preset=ultrafast"/>" contents to some other ffmpeg encoding to see if that helps.

**Comment by jliljebl** [comment] 2017-05-25 16:04
Some other questions that would be useful to have answered to fix this:

1) Does the error occur only with 4K original files?
2) Does the error occur only with 4K Project Profile being used?

**Comment by Efenstor** [comment] 2017-05-25 16:38
> Does the error occur only with 4K original files?
> Does the error occur only with 4K Project Profile being used?

No no no, neither is the case here. I have garbled files with any source and profile.

Just tried running from the command line and I can see the following suspicious error messages when making a proxy:
```
proxy render started, items: 1, dim: 480x264
FileRenderPlayer started, start frame: 0, stop frame: 375
[mp2 @ 0x7fdc448814e0] Channel layout not specified
[mp4 @ 0x7fdc4487c3c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x7fdc4487c3c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[h264 @ 0x7fdc45d6e500] QP 4294967285 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967279 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967286 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967285 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967284 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967285 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967281 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967279 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967285 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967284 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[h264 @ 0x7fdc45d6e500] QP 4294967286 out of range
[h264 @ 0x7fdc45d6e500] decode_slice_header error
[h264 @ 0x7fdc45d6e500] no frame!
[producer avformat] /media/PEER_GYNT/Video Archives/2008.11.23 - Uval/00006.MTS
    video decoding error -1094995529
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 4 0, bytestream 17601
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 6 1, bytestream 21215
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 4 0, bytestream 21075
[h264 @ 0x7fdc45d6e500] top block unavailable for requested intra mode
[h264 @ 0x7fdc45d6e500] error while decoding MB 4 1, bytestream 17060
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 81141
[h264 @ 0x7fdc45d6e500] Increasing reorder buffer to 2
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 1, bytestream 57166
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 6 0, bytestream 13619
[h264 @ 0x7fdc45d6e500] Increasing reorder buffer to 3
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 16 1, bytestream 15284
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 4 0, bytestream 14925
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 3 1, bytestream 9589
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 11 0, bytestream 80234
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 1 1, bytestream 39892
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 10 0, bytestream 10416
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 1, bytestream 2596
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 0, bytestream 21884
[h264 @ 0x7fdc45d6e500] Reference 7 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 41 1, bytestream 22016
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 1 0, bytestream 96014
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 1 1, bytestream 35700
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 2166
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 0, bytestream 26314
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 1, bytestream 899
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 42 0, bytestream 21065
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 20 1, bytestream 16982
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 5 0, bytestream 81053
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 7 1, bytestream 57050
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 13647
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 5 1, bytestream 15274
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 14979
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 1 1, bytestream 9625
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 6 0, bytestream 80502
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 1, bytestream 39914
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 10 0, bytestream 10430
[h264 @ 0x7fdc45d6e500] Reference 5 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 29 0, bytestream 21800
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 64 1, bytestream 22024
[h264 @ 0x7fdc45d6e500] Reference 5 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 96016
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 3 1, bytestream 35694
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 76 0, bytestream 2118
[h264 @ 0x7fdc45d6e500] Reference 4 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 41 1, bytestream 23597
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 17 0, bytestream 26290
[h264 @ 0x7fdc45d6e500] Reference 4 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 3 1, bytestream 899
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 10 0, bytestream 10416
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 1, bytestream 2596
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 0, bytestream 21884
[h264 @ 0x7fdc45d6e500] Reference 7 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 41 1, bytestream 22016
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 1 0, bytestream 96014
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 1 1, bytestream 35700
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 2166
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 0, bytestream 26314
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 2 1, bytestream 899
[h264 @ 0x7fdc45d6e500] Reference 5 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 96016
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 3 1, bytestream 35694
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 76 0, bytestream 2118
[h264 @ 0x7fdc45d6e500] Reference 4 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 41 1, bytestream 23597
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 17 0, bytestream 26290
[h264 @ 0x7fdc45d6e500] Reference 4 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 3 1, bytestream 899
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 1993
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 4 1, bytestream 12178
[h264 @ 0x7fdc45d6e500] Reference 2 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 37 1, bytestream 1014
[h264 @ 0x7fdc45d6e500] Missing reference picture, default is 2147483647
[h264 @ 0x7fdc45d6e500] Missing reference picture, default is 2147483647
[h264 @ 0x7fdc45d6e500] Reference 5 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 0 0, bytestream 12057
[h264 @ 0x7fdc45d6e500] Missing reference picture, default is 2147483647
[h264 @ 0x7fdc45d6e500] Missing reference picture, default is 2147483647
[h264 @ 0x7fdc45d6e500] Reference 3 >= 2
[h264 @ 0x7fdc45d6e500] error while decoding MB 5 1, bytestream 15906
...
FileRenderPlayer stopped, producer frame: 375
proxy render done
```
There's FFMPEG used for encoding, right? Then this is quite weird, because when I run FFMPEG manually on the very same file I'm getting it encoded properly:
```
ffmpeg -i 00006.MTS -f mp4 -acodec mp2 -ab 192k -ar 48000 -vcodec mpeg4 -preset ultrafast output.mp4
ffmpeg version 3.3.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-17) 20170510
  configuration: --disable-decoder=amrnb --disable-decoder=libopenjpeg --disable-mips32r2 --disable-mips32r6 --disable-mips64r6 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-msa --disable-libopencv --disable-podpages --disable-stripping --enable-avfilter --enable-avresample --enable-gcrypt --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libzvbi --enable-nonfree --enable-opengl --enable-openssl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --incdir=/usr/include/x86_64-linux-gnu --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --toolchain=hardened --enable-frei0r --enable-chromaprint --enable-libx264 --enable-libiec61883 --enable-libdc1394 --enable-vaapi --disable-opencl --enable-libmfx --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mpegts, from '00006.MTS':
  Duration: 00:00:12.54, start: 0.509033, bitrate: 16848 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(top first), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 59.94 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 256 kb/s
Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (output.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (ac3 (native) -> mp2 (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'output.mp4':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: mpeg4 ( [0][0][0] / 0x0020), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 29.97 fps, 30k tbn, 29.97 tbc
    Metadata:
      encoder         : Lavc57.89.100 mpeg4
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: mp2 (i[0][0][0] / 0x0069), 48000 Hz, stereo, s16, 192 kb/s
    Metadata:
      encoder         : Lavc57.89.100 mp2
frame=   41 fps=0.0 q=31.0 size=    1074kB time=00:00:01.57 bitrate=5591.5kbits/frame=   91 fps= 90 q=31.0 size=    1707kB time=00:00:03.25 bitrate=4296.3kbits/frame=  142 fps= 94 q=31.0 size=    2369kB time=00:00:04.90 bitrate=3952.1kbits/frame=  194 fps= 96 q=31.0 size=    3026kB time=00:00:06.70 bitrate=3693.9kbits/frame=  247 fps= 98 q=31.0 size=    3654kB time=00:00:08.38 bitrate=3568.0kbits/frame=  298 fps= 98 q=31.0 size=    4545kB time=00:00:10.11 bitrate=3679.6kbits/frame=  345 fps= 98 q=31.0 size=    5422kB time=00:00:11.70 bitrate=3795.9kbits/frame=  375 fps= 98 q=31.0 Lsize=    6049kB time=00:00:12.54 bitrate=3950.8kbits/s speed=3.26x    
video:5745kB audio:294kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.153063%
```

**Comment by jliljebl** [comment] 2017-05-25 18:05
if you open "Help->Runtime Environment" what does panel 'Render Options' say, is everything marked AVAILABLE?

I'll try to install Debian Stretch on VM next week to see if this reproduces.

**Comment by Efenstor** [comment] 2017-05-25 18:13
Yes, everything seems available.
![screenshot at 2017-05-26 01-12-08](https://cloud.githubusercontent.com/assets/11175574/26464021/89133c42-41b0-11e7-8ebd-2c36ec0dc53a.png)

**Comment by Efenstor** [comment] 2017-05-25 18:16
I don't think the reason is in Debian, more likely it's something with the newer versions of the libav components.

May be those lines
```
[mp4 @ 0x7fdc4487c3c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x7fdc4487c3c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```
Can tell something about the cause of the issue?

**Comment by Efenstor** [comment] 2017-05-26 07:10
Added the new encoding option for MJPEG as follows
```
<proxyencodingoption name="Motion JPEG" extension="avi" type="av" audiodesc="mp2, 192kb/s, 48000Hz" resize="True" qgroup="qgroup1">
    <profile args="f=avi acodec=mp2 ab=192k ar=48000 vcodec=mjpeg q:v=2"/>
</proxyencodingoption>
```
And the result is identical for 2K and 4K AVC sources, shot with different camcorders. That proves the problem is with decoding, not encoding. And, judging from those skewed frames, it has something to do with the frame resolution, like it's not multiple of 4, 8, 16, etc, whatever usually needed.

The first frame is completely green, and searching for that, I've found an old-and-fixed bug reported for ffmpeg, which looks quite similar: https://trac.ffmpeg.org/ticket/4535

**Comment by Efenstor** [comment] 2017-05-31 18:43
I have got cleaned my system of the deb-multimedia.org repository (because after the today's upgrade it broke up mplayer), so it is now a "pure" Debian Stretch. Unfortunately, the problem persists. I've installed Flowblade using the official deb package. The versions of the components on my system now are these:

  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100

MLT v6.4.1, all the codecs are marked as available in the "Runtime Environment" dialog.

Interestingly enough, the way mplayer was broken after the aforementioned upgrade resembles the artifacts I see in the Flowblade's proxy files - the same stuttering playback, blockiness and green frames, but much worse.

**Comment by jliljebl** [comment] 2017-06-01 08:11
Ok, I installed Debian Stretch RC 4 on Virtualbox, and then installed Flowblade 1.12 and did a proxy file test, but I was not able to reproduce the problem, everything worked as they are supposed to.

I was not getting the error printouts on the terminal that you are getting.

I will keep this open and try to think another approaches to find the problem but basically the libav* + MLt + Flowblade stack seems to work on Debiian Strech, so it is not clear at this time where your problem is.

**Comment by Efenstor** [comment] 2017-06-01 11:05
Try this file: https://yadi.sk/i/Ssi7CDOu3Jj79G

**Comment by Efenstor** [comment] 2017-06-01 12:01
This is crazy. I've installed FlowBlade on my brother's PC, who also has Debian Stretch with very similarly configured environment and even quite similar hardware and there is no problem there! Proxy is encoded and played perfectly. I've compared the libav and MLT versions, those are the same. Every riddle has an answer, and this one must have one as well. I'll dig further.

**Comment by jliljebl** [comment] 2017-06-01 12:05
Does not reproduce here either with your test file.

Proxies are created and played back from your file S2230089.MP4 with no artifacts displayed, both in my Ubuntu 17.04 development system and on Debian Stretch RC 4 virtual box test system.

This is probably some hard to fix hardware related issue.

**Comment by Efenstor** [comment] 2017-06-01 12:18
> This is probably some hard to fix hardware related issue.
Nope. I've just managed to fix the problem on my own PC, by simply moving $HOME/.flowblade folder to a temporary folder (I wonder why I didn't try it before). Now I'll gradually configure it the way it was, may be the problem will reappear. Anyway, I've saved the problem configuration, so I can compare it with the clean one.

**Comment by jliljebl** [comment] 2017-06-01 12:38
Ok, I'll still leave this open for a while. If we discover the root cause this might have some wider relevance.

**Comment by Efenstor** [comment] 2017-06-01 15:35
I think I've managed to localize it. In Preferences you have to check "Allow Frame Dropping" _and_ set "Render Threads" to more than 1. I tried twice and it seems that it is the cause.

**Comment by jliljebl** [comment] 2017-06-01 15:46
Great, I'll do tests to confirm weekend/nextweek.  This is an easy fix then, just force working options on proxy rendering using a module flag.

**Comment by jliljebl** [comment] 2017-06-01 15:53
I decided to try right away, and yes you are right changing performance settings causes the problem, excellent work.

**Comment by jliljebl** [comment] 2017-06-01 16:18
This is fixed in repository

This bug is only present in 1.12. This is caused by having changed the default "Performance" settings in Preferences dialog.

The work around is to set  "Performance" settings to:

Render Threads: 1
Allow Frame Dropping: Off

**Comment by jliljebl** [comment] 2017-10-07 12:13
1.14 fixes this, closing.

**Closed by jliljebl** 2017-10-07 12:13 UTC
Labels: fixed, workaround in comments
